### ISSUE TITLE
switch to ssb-manifest?

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#108]
right now, sbot's manifest is split between each of its plugins, so we use `getManifest()` on a running instance to generate the correct listing. now that we have https://github.com/ssbc/ssb-manifest, how do we want to do this? should we remove the manifest pieces from the plugins and just use `ssb-manifest`?

**Comment by dominictarr** [comment]
ssb-manifest should probably contain the logic that is used to combine the plugin manifests.

**Comment by pfraze** [comment]
how would that work outside of sbot?

**Comment by dominictarr** [comment]
hmm, I don't really know... lets just wait and see how it turns out.

**Comment by dominictarr** [comment]
this issue is stale, closing
