### ISSUE TITLE
crash error experienced intermittently

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#110]
reported by @ralphtheninja. Here's the dump: https://gist.github.com/ralphtheninja/e45e41f5fe2e5a00655d

**Comment by pfraze** [comment]
I suspect this was due to an outdated dependency

**Comment by ralphtheninja** [comment]
Things that can't be reproduced will only litter the issue list. Kill it! :) I'll report it if it happens again.

**Comment by pfraze** [comment]
Ok, thanks!
