### ISSUE TITLE
sbot invite.addMe crashes

### ISSUE THREAD

**Issue by ralphtheninja** [ssbc/scuttlebot#113]
```
$ sbot invite.addMe "ralphtheninja.info,55eHs2t9xT9hAQ3ln5PueRXllrxZIVhGhtCP2bL/IY0=.blake2s,0owmW8rCTQ5slb3fbY4YvXnPaN/mjCHNVOBJagdN+0w="

/usr/local/lib/node_modules/scuttlebot/bin.js:205
        if(err) throw err
                      ^
Error: unexpected end of parent stream
    at Object.p.destroy (/usr/local/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:189:15)
    at Object.p.write (/usr/local/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:179:24)
    at source (/usr/local/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:34:15)
    at /usr/local/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/pull-goodbye/endable.js:6:7
    at /usr/local/lib/node_modules/scuttlebot/node_modules/pull-stream/throughs.js:13:5
    at /usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/node_modules/pull-stream/throughs.js:123:12
    at cancel (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/node_modules/pull-abortable/index.js:13:5)
    at Function.reader.abort (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/node_modules/pull-abortable/index.js:47:5)
    at abort (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/index.js:32:17)
    at null.<anonymous> (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/index.js:39:7)
```

Fired up an `sbot` at work and used a one time invite code. Not sure if it's related to that or not.

I get the following output in the terminal running `sbot server`

```
info ZRUA SBOT 10 incoming-connection 
info ZRUA AUTH 10 req "ZRUAZND59Bxahx6z0R03LwWvfX+I3O08+1TUROaqirs=.blake2s"
info ZRUA REMO 10 remote-authed {"granted":true,"type":"client","role":"master"}
info ZRUA SBOT 10 client-authed "ZRUAZND59Bxahx6z0R03LwWvfX+I3O08+1TUROaqirs=.blake2s"
info ZRUA SBOT 10 authed {"type":"server"}
info ZRUA SBOT 11 connect {"host":"ralphtheninja.info","port":2000}
warn ZRUA SBOT 11 unauthed {}
```

**Comment by pfraze** [comment]
Was there a long delay before the "unexpected end" error, or was it relatively quick?
Are you certain that log output was from your connection, or is it possible no connection was made, perhaps due to DNS failing to resolve?
Are both devices running the latest sbot?
Did you see any signs of gremlins, possibly their skin sheddings or loose fur?

**Comment by ralphtheninja** [comment]
Yes it was a long delay. Felt like a timeout.
Yes I'm certain that was from my connection.
Both devices are running latest code (both using npm install -g).
Gremlins all over the place! :)

**Comment by pfraze** [comment]
Classic gremlins.
Is it possible that the operation succeeded but the RPC session failed to report back? Did the pub server follow the client node, and/or did the client node publish a `pub` message for `ralphatheninja.info`?

And unrelated, you know there's a `.ninja` TLD now, right? `ralphthe.ninja` is wide open!

**Comment by ralphtheninja** [comment]
The scenario was as follows. I ran my pub server at home (ralphtheninja.info), ran one peer on my local machine (`sbot server`) and then issued the `sbot invite.addMe` command in another terminal.

Let me see if I can reproduce it again. If not, I'll start following that stack trace to see if I can get some more information.

LOL Nope I didn't know that :) Hush now before some korean person goes of and registers it and wants all my bitcoins for it.

**Comment by pfraze** [comment]
Ok. Did you see any sign of the published messages I referred to? If you look in Phoenix, there's a raw feed view to check - http://localhost:2000/#/feed

> LOL Nope I didn't know that :) Hush now before some korean person goes of and registers it and wants all my bitcoins for it.

:)

**Comment by dominictarr** [comment]
this operation depends on requesting to the local, and to the remote.
(the local sbot will connect to the remote for you) suggestion: test that you can connect to the remote.
```
ssb_host=ralphtheninja.info sbot whoami
```
it will give you an auth error, but it will let you know it's alive and online though

**Comment by dominictarr** [comment]
actually, connecting to remote hosts is currently broken. todo: fix that.

I tried your invite code, it took a few seconds, but it worked:

``` js
./bin.js invite.addMe "ralphtheninja.info,55eHs2t9xT9hAQ3ln5PueRXllrxZIVhGhtCP2bL/IY0=.blake2s,0owmW8rCTQ5slb3fbY4YvXnPaN/mjCHNVOBJagdN+0w="

[
  {
    "key": "yM8IbSape+kM+UKalrCERQQx1T3JSZhKYm23qcdaDIA=.blake2s",
    "value": {
      "previous": "C4fAr+KMzYcQhmw7zVwFyTHTFz2QY1OZMzZYqu2jdrc=.blake2s",
      "author": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s",
      "sequence": 105,
      "timestamp": 1423511842404,
      "hash": "blake2s",
      "content": {
        "type": "follow",
        "feed": "55eHs2t9xT9hAQ3ln5PueRXllrxZIVhGhtCP2bL/IY0=.blake2s",
        "rel": "follows"
      },
      "signature": "M0OPAqPsxR/vV9fb/LnlT3P2d/Mmme0u4aVTKE+MP1QmlawJI03aFcMwV5JXkHSVP4CgOQzImaIw4WKpb1uGLg==.blake2s.k256"
    }
  },
  {
    "key": "n+NMJJstS21FX5vXnLlE59NcrYkQVaVs6zVc0/Uz/f8=.blake2s",
    "value": {
      "previous": "yM8IbSape+kM+UKalrCERQQx1T3JSZhKYm23qcdaDIA=.blake2s",
      "author": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s",
      "sequence": 106,
      "timestamp": 1423511842584,
      "hash": "blake2s",
      "content": {
        "type": "pub",
        "address": "ralphtheninja.info"
      },
      "signature": "+mTwPFdoUbZxvrsiOJyVOvWBnCNhaz2liOs7HVDojOnbP1NfsYZkEQyygUihAL7qVHxFOmw1xuthy9fU+0bstw==.blake2s.k256"
    }
  }
]
```

**Comment by pfraze** [comment]
The long delay makes me think that's what happened -- that he couldnt connect to the remote.

**Comment by ralphtheninja** [comment]
It sounds very likely. I just wonder why. I'm at home now but I'll try and reproduce tomorrow.

**Comment by pfraze** [comment]
Ok. If that is the issue, we'll need to improve on our error reporting.

**Comment by dominictarr** [comment]
this is fixed now, right?
