### ISSUE TITLE
Issues when installed -g via npm

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#119]
For me, running `sbot server` after `npm install -g scuttlebot` seemed to work well, except that phoenix would show "Message not found" every time I tried to open a message. Using my work-version of scuttlebot, I experienced no issues.

@jtremback also reported a buggy experience: phoenix web ui would not load, and his command is `scuttlebot` instead of `sbot`

**Comment by dominictarr** [comment]
what npm versions is every one using?
@jtremback @pfraze

**Comment by pfraze** [comment]
also node versions.
I'm npm 1.4.28 and node 0.10.33

**Comment by spro** [comment]
I just ran into the "Message not found" problem and it looks like the problem was just that secure-scuttlebutt was out of date (due to the seemingly recent change of using relatedMessages)
https://github.com/ssbc/scuttlebot/pull/123

**Comment by pfraze** [comment]
this appears to be solved
