### ISSUE TITLE
problems with rpc.add

### ISSUE THREAD

**Issue by ralphtheninja** [ssbc/scuttlebot#125]
I created a gist to try out the sbot rpc api:

https://gist.github.com/ralphtheninja/a41fcaad4e0827b8e70d

It works well if run stand alone but crashes if you require it and call the `rpcAdd` method:

```
/home/lms/src/ssbc/sbot-test-guard/node_modules/scuttlebot/node_modules/muxrpc/index.js:179
            ps.request({name: name, args: args}, cb)
               ^
TypeError: Cannot call method 'request' of null
    at EventEmitter.auth (/home/lms/src/ssbc/sbot-test-guard/node_modules/scuttlebot/node_modules/muxrpc/index.js:179:16)
    at rpcAdd (/home/lms/src/ssbc/sbot-test-guard/lib/rpc-add.js:13:7)
    at postMessage (/home/lms/src/ssbc/sbot-test-guard/index.js:61:5)
    at null._onTimeout (/home/lms/src/ssbc/sbot-test-guard/index.js:86:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

It happens because `ps` is set to `null` [`here`](https://github.com/ssbc/muxrpc/blob/master/index.js#L139)

Thoughts?

/cc @dominictarr @pfraze

**Comment by dominictarr** [comment]
That is not part of the public api - i think it waits for the connection to be ready before it actually creates that object... what where you trying to do?

**Comment by pfraze** [comment]
@ralphtheninja can you show me the output of `npm list` in the project you ran that code?

**Comment by ralphtheninja** [comment]
@dominictarr I'm essentially trying to mimic what `scuttlebot/bin.js` does when calling `add` to solve this https://github.com/ralphtheninja/sbot-test-guard/issues/10

**Comment by ralphtheninja** [comment]
@pfraze Added output to gist.

**Comment by dominictarr** [comment]
oh hang on, that looks ilke it should work. It doesn't make any sense that it would work as a command but not a require... can you link me to the code that requires it and doesn't work?

**Comment by pfraze** [comment]
@ralphtheninja that's the deps of the code when it fails?

The ssb dep is behind -- 8.0.0 when latest is 8.1.3. Try updating that

**Comment by ralphtheninja** [comment]
@dominictarr https://github.com/ralphtheninja/sbot-test-guard/blob/26ca0b43b6807a1e8c4e72fadbb48f5cdb82c10f/index.js#L59 Agree. It doesn't make any sense.

**Comment by ralphtheninja** [comment]
That's just a test branch. Simply run `./index.js` and it will try posting some data (config adjusted for short time intervals)

**Comment by ralphtheninja** [comment]
To summarize a bit. If I run `sbot server` in a terminal and run `node lib/rpc-add.js` in another terminal it works. But if I run `./index.js` (which runs `sbot server` as a child process) I get problems. I'm wondering if it has to do with the child process inheriting stdio. That's the only thing I can think of that is different.

**Comment by pfraze** [comment]
Are you sure youre passing the correct config and using the correct keypair? You're using ssb defaults in the rpc-add function, but sbot-test-guard has its own config files.

I suspect there's a more expressive error message that's not being shown to you -- something about a failed connection or failed auth.

**Comment by dominictarr** [comment]
RIGHT. okay now it's starting to make sense. The thing here is that the way you are doing the rpc client is from code c/p from the cli client, which totally assumes that the server is already running.

But they way you are using this, it is trying to connect to the server, while starting the server.
you should refactor this a bit so that it returns a `createClient` function that doesn't get called until the child process is properly up and running... That will fix it.

**Comment by ralphtheninja** [comment]
@pfraze Yes I am sure of the config and the keys.

@dominictarr The timing doesn't seem to matter. I have the same problem even if I set the post timer to a higher value, say 30 seconds. Running `rpc-add.js` still works fine even for low time intervals.

**Comment by ralphtheninja** [comment]
@dominictarr Oh it's the `rpc` require that does a call?

**Comment by dominictarr** [comment]
it's not the add call that is the problem, it's the creation time. since you require ./lib/rpc before you create the child process.

try moving `require('./lib/rpc')` into a set timeout...

**Comment by ralphtheninja** [comment]
Thanks for clarifying!
