### ISSUE TITLE
Keypair CLI/config param to server cmd

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#126]
Right now, it's possible to change your active ID by moving `~/.ssb/private` somewhere else. When that file disappears, Sbot generates a new identity.

We could streamline that by passing the name of the keyfile to `sbot server`, and perhaps prompting to create if not found

```
$ sbot server --feed bob
/home/pfraze/.ssb/keys/bob not found, create this feed? y
/home/pfraze/.ssb/keys/bob created.
```

**Comment by dominictarr** [comment]
This feature (multiple feeds.) has certainly been asked for before, but I think this may not be the best way todo it. I don't think you want to restart the pub server to use a different key, you want to be able to use different keys from different applications etc... maybe have a key for a specific application.

I think the way to do this would be to have a smarter client that created the signed message in the client,
and then added a valid message. That would just mean using some of the logic from secure-scuttlebutt/feed in the client, and the client having it's own keys.

**Comment by pfraze** [comment]
My aim was for something temporary for debugging, but I suppose temporary features have a way of becoming non-temporary.

The actual solution has to solve key management. The method you describe suggests the application would have to store/access the private key file? Which I like because it's simple.

Alternatively, we have sbot store all private keys and provide a key management API, particularly if we want to withhold the private key from the application or if we want centralized access to keys (eg so sbot could post to any local feed without the key's application getting involved)

**Comment by dominictarr** [comment]
okay if you just need this for debugging, it's a trivial 2 line change.

Take 'secret' from a `keyfile` parameter
which defaults to `secret`.
https://github.com/ssbc/scuttlebot/blob/master/bin.js#L16

There might be a couple of places where this needs to happen, but only 1 once we refactor it all into a `ssb-client` module

**Comment by dominictarr** [comment]
Anything with "manager" in it is probably too complicated. I'd just let the client app manage it's own key if it has it's own key. Also: todo: encrypted keys.

**Comment by pfraze** [comment]
Self-managed keys are simpler. Would web SPAs be safe putting those keys in dom storage?

I've warmed to the concept of each application maintaining its own feed. I think we should explore a permissions system where programs identify as users.

Feed IDs (blake2s hash of public key) and message keys (blake2s hash of message content) are hard to guess, correct? Could they be used as read capabilities?

**Comment by dominictarr** [comment]
There is definately a need to have multiple keys per device, so there would be nothing to stop having one client that connects with it's own key and happens to be it's own application.

**Comment by dominictarr** [comment]
since we refactored out ssb-feed this is now possible.
