### ISSUE TITLE
Occasional crash error from using closed RPC stream

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#130]
This surfaced in https://travis-ci.org/ssbc/scuttlebot/builds/51892383 and I've seen it elsewhere. I believe it stems from normal asynchronous variations in ordering, not a race condition, but I'm not 100% sure.

I suggest we handle this by patching muxrpc to not crash if a method is called after close, and then see if we get continued weirdness. @dominictarr that sound good?

**Comment by dominictarr** [comment]
but that build passes... did you mean a different build?

A race condition *is* when normal asynchronous variations in ordering produce a bug.

**Comment by pfraze** [comment]
Shoot. Pro-tip: if you restart a travis-ci build after it fails, that new build overwrites the old one. I wish I had copied out the dump!

The test that failed was the 3-way replication test, though I don't remember which (we have multiple tests with that label). `createHistoryStream` was called by the gossip plugin, but the RPC stream's internal objects had been nullified because the stream was closed, resulting a null-reference function-call.

> A race condition is when normal asynchronous variations in ordering produce a bug.

Maybe my semantics were incorrect there. I'll explain what I was thinking:

We have some cyclical behaviors which are triggered by interval timers in that code (gossip for one). What I meant by "normal asynchronous variations" was the possibility that some behavior is triggered that uses the RPC interface, but doesn't have any pre-check whether the RPC connection is still active before trying to use it. When I think of race-conditions, I think of a violated requirement on causal-dependency between two concurrent code-paths. This may just be a failure to check the world state before using it.

We'll need to guard the muxrpc methods from simply throwing when this codepath occurs. (This is another bug introduced/exposed by the deallocation fixes.) Any RPC usage in scuttlebot should be protected by the `rpc.task()` guard, and we might benefit from double-checking that and making sure it's still working, but I think this was caused by the tests calling `close()` on the DB after they'd verified their results. `test/server.js` could definitely cause that. Therefore, I suspect muxrpc simply needs to be updated with the "is open?" guards.

**Comment by pfraze** [comment]
Here we go, happened again: https://travis-ci.org/ssbc/scuttlebot/builds/52012998

```
TAP version 13
# replicate between 3 peers
info 4X8f SBOT  listening "localhost:45451"
info Kv+2 SBOT  listening "localhost:45452"
info 9wri SBOT  listening "localhost:45453"
info 4X8f SBOT  use-plugin ""
info 4X8f SBOT  use-plugin "gossip@1.0.0"
info 4X8f SBOT  use-plugin "friends@1.0.0"
info Kv+2 SBOT  use-plugin ""
info Kv+2 SBOT  use-plugin "gossip@1.0.0"
info Kv+2 SBOT  use-plugin "friends@1.0.0"
info 9wri SBOT  use-plugin ""
info 9wri SBOT  use-plugin "gossip@1.0.0"
info 9wri SBOT  use-plugin "friends@1.0.0"
info 9wri SBOT 1 connect
  {
    "port": 45451,
    "host": "localhost",
    "time": {
      "connect": 0,
      "attempt": 1424798887813
    },
    "connected": true
  }
info 4X8f SBOT 2 incoming-connection 
info 9wri AUTH 1 req
  "4X8fXQdyjYx/J5MiMk+uWg0fwaW1Se3rzY9IuqMFAOI=.blake2s"

...

info 4X8f SBOT 4 local-done 
info Kv+2 REPL 3 success
  {
    "4X8fXQdyjYx/J5MiMk+uWg0fwaW1Se3rzY9IuqMFAOI=.blake2s": 4,
    "9wriN5Hf9+ZiSFDUawJOnrlALh7F+cWGaeyA0xAHqR0=.blake2s": 4,
    "Kv+2kwntVo8gMc4eXEXs02ELojMFma71MdpIPVPJPPs=.blake2s": 4
  }
ok 1 (unnamed assert)
info Kv+2 SBOT 3 local-done 
/home/travis/build/ssbc/scuttlebot/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Cannot call method 'stream' of null
    at EventEmitter.createHistoryStream (/home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/index.js:182:25)
    at /home/travis/build/ssbc/scuttlebot/plugins/replicate.js:50:25
    at loop (/home/travis/build/ssbc/scuttlebot/node_modules/pull-stream/sinks.js:15:33)
    at drain (/home/travis/build/ssbc/scuttlebot/node_modules/secure-scuttlebutt/node_modules/pull-paramap/index.js:19:11)
    at /home/travis/build/ssbc/scuttlebot/node_modules/secure-scuttlebutt/node_modules/pull-paramap/index.js:44:13
    at /home/travis/build/ssbc/scuttlebot/node_modules/secure-scuttlebutt/index.js:260:9
    at /home/travis/build/ssbc/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:102:12
    at /home/travis/build/ssbc/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:121:19
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by ralphtheninja** [comment]
And here https://travis-ci.org/ssbc/scuttlebot/builds/52011130

**Comment by pfraze** [comment]
should be fixed by https://github.com/ssbc/muxrpc/pull/17
