### ISSUE TITLE
persist access keys (encrypted key storage)

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#132]
So that it is possible for a 3rd party client application to use, and reconnect even after a server restart.
The invite plugin already stores it's secrets. That could be refactored so that the invites are just api access keys,
and access keys are stored - this would then allow us to encrypt the private key on disk, and the user would enter a passphrase when starting scuttlebot.

https://github.com/ssbc/scuttlebot/blob/master/plugins/invite.js#L54-L60

**Comment by dominictarr** [comment]
hmm... if the threat model is other apps running on the same computer it's not really that good. There is probably all sorts of things they could do to get around this...

On the other hand, if the threat model is someone stealing your device, that is better... unless it's turned on, and the user is still logged into sbot.

The more I think about this the less I feel confidant about encrypted private keys, and the more that physical security of the device seems like the best bet for now*.

* until the post-ssb future where we have container based operating systems and every application is well separated.

**Comment by pfraze** [comment]
If we symmetrically encrypt all sensitive data, won't that stop local programs from accessing it except through sbot's api? And we can require password-auth to sbot.

**Comment by dominictarr** [comment]
there is lots of weird stuff a local program could do... like pretend to be scuttlebot and phish the password, or pretend to be another installed app. Basically, it's just hard to reason about...

basically if the problem is "prevent local apps from stealing your key" I don't think it follows that the answer is "encrypt the key" because there are other attack vectors.

That is not to say that encrypting the key isn't a good move in another threat model though. If someone stole your (powered down) computer, having an encrypted key is pretty good... provided you have a decent password.

**Comment by pfraze** [comment]
ok, fair point

**Comment by pfraze** [comment]
There's also the unsophisticated attack: sitting at somebody's desk and copying out the keyfile. I think we should protect against that.

**Comment by dominictarr** [comment]
I was thinking of using  @kumavis encrypted kv database for to encrypt that stuff.

**Comment by pfraze** [comment]
cool
