### ISSUE TITLE
ssbc crashes at startup on windows

### ISSUE THREAD

**Issue by luckcolors** [ssbc/scuttlebot#135]
i builded scuttlebot on windows without problems but when i start the server for the first time it gives me this log and it closes:
Secure scuttlebutt has undergone a major API change.
Rebuilding indexes to ensure consistency. Please wait.
Success!
info wl9D SBOT  use-plugin ""
info wl9D SBOT  use-plugin "gossip@1.0.0"
info wl9D SBOT  use-plugin "blobs@0.0.0"
info wl9D SBOT  use-plugin "invite@1.0.0"
info wl9D SBOT  use-plugin "friends@1.0.0"
info wl9D SBOT  use-plugin "local@1.0.0"
info wl9D SBOT  use-plugin "phoenix@1.0.0"
Success!
info wl9D SBOT  use-plugin "logging"
info wl9D SBOT  use-plugin ""
info wl9D SBOT  use-plugin ""
info wl9D SBOT  use-plugin "gossip@1.0.0"
info wl9D SBOT  use-plugin "gossip@1.0.0"
info wl9D SBOT  use-plugin "blobs@0.0.0"
info wl9D SBOT  use-plugin "blobs@0.0.0"
info wl9D SBOT  use-plugin "invite@1.0.0"
info wl9D SBOT  use-plugin "invite@1.0.0"
info wl9D SBOT  use-plugin "friends@1.0.0"
info wl9D SBOT  use-plugin "friends@1.0.0"
info wl9D SBOT  use-plugin "local@1.0.0"
info wl9D SBOT  use-plugin "local@1.0.0"
info wl9D SBOT  use-plugin "phoenix@1.0.0"
info wl9D SBOT  use-plugin "phoenix@1.0.0"
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
 
then when i open it again:
C:\EnvironmentPath>sbot
info wl9D SBOT  use-plugin ""
info wl9D SBOT  use-plugin "gossip@1.0.0"
info wl9D SBOT  use-plugin "blobs@0.0.0"
info wl9D SBOT  use-plugin "invite@1.0.0"
info wl9D SBOT  use-plugin "friends@1.0.0"
info wl9D SBOT  use-plugin "local@1.0.0"
info wl9D SBOT  use-plugin "phoenix@1.0.0"

it just hangs here. Also when i connect on port 2000 it says that i don't have permission to acces.

**Comment by pfraze** [comment]
That's pretty odd. The first time, it looks like a scuttlebot instance is created multiple times. That might be a bug in the index rebuilding code.

The second time seems unrelated. Are you running scuttlebot on your local device? The Web UI is only allowed to load if requested from localhost.

**Comment by pfraze** [comment]
https://github.com/ssbc/scuttlebot/blob/master/index.js#L295-L301 whoops! missed an else statement in there

**Comment by luckcolors** [comment]
ok i'm going to build ssbc again

**Comment by pfraze** [comment]
I haven't had a chance to fix that yet. I'll let you know when a fix is pushed

**Comment by luckcolors** [comment]
ok thanks i'll wait :)

**Comment by pfraze** [comment]
ok, fix published as version `3.0.1`

**Comment by luckcolors** [comment]
ok it works but it won't let me acces the page here's the log:

Rebuilding indexes to ensure consistency. Please wait...
Indexes rebuilt.
info 4lIS SBOT  use-plugin ""
info 4lIS SBOT  use-plugin "gossip@1.0.0"
info 4lIS SBOT  use-plugin "blobs@0.0.0"
info 4lIS SBOT  use-plugin "invite@1.0.0"
info 4lIS SBOT  use-plugin "friends@1.0.0"
info 4lIS SBOT  use-plugin "local@1.0.0"
info 4lIS SBOT  use-plugin "phoenix@1.0.0"
Remote access attempted by ::1
Remote access attempted by ::ffff:192.168.0.103
Remote access attempted by ::ffff:192.168.0.103
Remote access attempted by ::ffff:192.168.0.103

**Comment by pfraze** [comment]
are you running scuttlebot on your device, or is it on another device in your LAN, or in a virtual machine? if not, it could be that our [is this a local request check](https://github.com/ssbc/phoenix/blob/master/index.js#L13) is working incorrectly

**Comment by dominictarr** [comment]
that it's showing a ipv6 address may have something to do with it.

**Comment by luckcolors** [comment]
so:
using localhost:2000 doesn't work
using 192.168.0.103:2000 doesn't work
using 127.0.0.1:2000 works but the page remains blank, the page title is secure scuttlebot and here's the error log:

info 4lIS SBOT 1 incoming-connection
warn 4lIS SBOT 1 unauthed
  createPacketStream/<.request@http://127.0.0.1:2000/js/home.js:10764:23
  onRequest@http://127.0.0.1:2000/js/home.js:10994:7
  [32]</module.exports/p.write@http://127.0.0.1:2000/js/home.js:11141:33
  [42]</module.exports/<.sink/<@http://127.0.0.1:2000/js/home.js:11333:9
  next/<@http://127.0.0.1:2000/js/home.js:10094:33
  next/<@http://127.0.0.1:2000/js/home.js:10377:9
  next/<@http://127.0.0.1:2000/js/home.js:12589:9
  [68]</</exports.map/</<@http://127.0.0.1:2000/js/home.js:12513:7
  pull@http://127.0.0.1:2000/js/home.js:12178:9
  next@http://127.0.0.1:2000/js/home.js:12203:7
  next/<@http://127.0.0.1:2000/js/home.js:12205:18
  pull/<@http://127.0.0.1:2000/js/home.js:12188:11
  [74]</module.exports</<@http://127.0.0.1:2000/js/home.js:13086:1

**Comment by No9** [comment]
@luckcolors can you confirm that you are running scuttlebot in an admin console and that your antivirus is not getting in the way?

I am guessing but maybe something is preventing the creation of the required ports. 

Also the fact that localhost isn't getting mapped to 127.0.0.1 is very suspicious indeed. 
Can you look at C:\Windows\System32\drivers\etc\hosts and confirm there is no remapping of localhost occurring there 

Thanks

**Comment by luckcolors** [comment]
there's not also my win install it's very new.
tried disable windows firewall same problem.
tried with antivirus disabled same problem.

also the log it's saying:
info SBOT incoming-connection
warn SBOT unauthed 
^^^^^^^^ it's not that it's still not doing the setup the first time i load the program with a fresh db?
           i mean it seems that it's not logging me in

**Comment by pfraze** [comment]
it looks like you are successfully loading the page when you use `127.0.0.1:2000`, but then something else is going wrong. What does the web page's console say after the blank page loads?

**Comment by pfraze** [comment]
The `warn SBOT unauthed` and ensuing stack dump is not actually an error, though I know it looks like it. It's just some cruft we haven't cleaned out yet. That said, what version of node and windows are you running? That stack dump looks a bit different from mine.

As for the ip address situation...

> Also the fact that localhost isn't getting mapped to 127.0.0.1 is very suspicious indeed. 

Yeah, I agree, though one of those access attempts was `::1`, which is the correct ipv6 loopback address (so I suppose we gotta start testing that). `::ffff:192.168.0.103` is weird though.

I'm curious what the console says when `127.0.0.1:2000` loads in the browser. Maybe that will shed some light on why `localhost:2000` fails.

**Comment by luckcolors** [comment]
here's the console log hope it helps you.connecting from 127.0.0.1:2000: 
info k5cn SBOT 1 incoming-connection
warn k5cn SBOT 1 unauthed
  createPacketStream/<.request@http://127.0.0.1:2000/js/home.js:10764:23
  onRequest@http://127.0.0.1:2000/js/home.js:10994:7
  [32]</module.exports/p.write@http://127.0.0.1:2000/js/home.js:11141:33
  [42]</module.exports/<.sink/<@http://127.0.0.1:2000/js/home.js:11333:9
  next/<@http://127.0.0.1:2000/js/home.js:10094:33
  next/<@http://127.0.0.1:2000/js/home.js:10377:9
  next/<@http://127.0.0.1:2000/js/home.js:12589:9
  [68]</</exports.map/</<@http://127.0.0.1:2000/js/home.js:12513:7
  pull@http://127.0.0.1:2000/js/home.js:12178:9
  next@http://127.0.0.1:2000/js/home.js:12203:7
  next/<@http://127.0.0.1:2000/js/home.js:12205:18
  pull/<@http://127.0.0.1:2000/js/home.js:12188:11
  [74]</module.exports</<@http://127.0.0.1:2000/js/home.js:13086:1

**Comment by pfraze** [comment]
Sorry, that's the terminal console. I was hoping for the browser window's console. Can you grab that for me? It's in the developer tools.

**Comment by luckcolors** [comment]
La connessione con ws://localhost:2000/ è stata interrotta durante il caricamento della pagina. home.js:13182:0
"Connection Error" Error: Close
Analisi dello stack:
[76]</exports.connect/chan.connect/chan.wsStream.socket.onclose@http://127.0.0.1:2000/js/home.js:13217:26
 home.js:15929:2
GET http://127.0.0.1:2000/ [HTTP/1.1 200 OK 2ms]
GET http://127.0.0.1:2000/css/home.css [HTTP/1.1 200 OK 17ms]
GET http://127.0.0.1:2000/css/sweet-alert.css [HTTP/1.1 200 OK 15ms]
GET http://127.0.0.1:2000/manifest.js [HTTP/1.1 200 OK 4ms]
GET http://127.0.0.1:2000/js/sweet-alert.js [HTTP/1.1 200 OK 15ms]
GET http://127.0.0.1:2000/js/home.js [HTTP/1.1 200 OK 66ms]
Pseudo-classe o pseudo-elemento sconosciuto “-webkit-inner-spin-button”.  Insieme di regole ignorato a causa del selettore errato. home.css:145:22
Pseudo-classe o pseudo-elemento sconosciuto “-webkit-search-cancel-button”.  Insieme di regole ignorato a causa del selettore errato. home.css:155:22
Proprietà sconosciuta “-moz-osx-font-smoothing”.  Dichiarazione tralasciata. home.css:270:25
Previsto un colore, invece è stato rilevato “auto”.  Previsto un colore, invece è stato rilevato “-webkit-focus-ring-color”.  Prevista fine del valore, trovato “-webkit-focus-ring-color”.  Errore durante l’interpretazione di “outline”.  Dichiarazione tralasciata. home.css:1088:15
Prevista fine del valore, trovato “\9 ”.  Errore durante l’interpretazione di “margin-top”.  Dichiarazione tralasciata. home.css:2482:18
Previsto un colore, invece è stato rilevato “auto”.  Previsto un colore, invece è stato rilevato “-webkit-focus-ring-color”.  Prevista fine del valore, trovato “-webkit-focus-ring-color”.  Errore durante l’interpretazione di “outline”.  Dichiarazione tralasciata. home.css:2500:15
Pseudo-classe o pseudo-elemento sconosciuto “-ms-input-placeholder”.  Insieme di regole ignorato a causa del selettore errato. home.css:2539:14
Pseudo-classe o pseudo-elemento sconosciuto “-webkit-input-placeholder”.  Insieme di regole ignorato a causa del selettore errato. home.css:2543:15
Prevista fine del valore, trovato “�”.  Errore durante l’interpretazione di “line-height”.  Dichiarazione tralasciata. home.css:2565:26
Prevista fine del valore, trovato “�”.  Errore durante l’interpretazione di “line-height”.  Dichiarazione tralasciata. home.css:2572:19
Prevista fine del valore, trovato “�”.  Errore durante l’interpretazione di “line-height”.  Dichiarazione tralasciata. home.css:2579:20
Pseudo-classe o pseudo-elemento sconosciuto “-ms-fullscreen”.  Insieme di regole ignorato a causa del selettore errato. home.css:2581:2
Pseudo-classe o pseudo-elemento sconosciuto “-ms-fullscreen”.  Insieme di regole ignorato a causa del selettore errato. home.css:2591:2
Pseudo-classe o pseudo-elemento sconosciuto “-ms-fullscreen”.  Insieme di regole ignorato a causa del selettore errato. home.css:2601:2
Prevista fine del valore, trovato “\9 ”.  Errore durante l’interpretazione di “margin-top”.  Dichiarazione tralasciata. home.css:2635:18
Proprietà sconosciuta “touch-action”.  Dichiarazione tralasciata. home.css:2945:14
Proprietà sconosciuta “user-select”.  Dichiarazione tralasciata. home.css:2957:13
Previsto un colore, invece è stato rilevato “auto”.  Previsto un colore, invece è stato rilevato “-webkit-focus-ring-color”.  Prevista fine del valore, trovato “-webkit-focus-ring-color”.  Errore durante l’interpretazione di “outline”.  Dichiarazione tralasciata. home.css:2966:15
Previsto “none”, URL o una funziona filtro, invece è stato rilevato “alpha(”.  Errore durante l’interpretazione di “filter”.  Dichiarazione tralasciata. home.css:2988:10
Previsto “none”, URL o una funziona filtro, invece è stato rilevato “progid”.  Errore durante l’interpretazione di “filter”.  Dichiarazione tralasciata. home.css:3408:10
Previsto “none”, URL o una funziona filtro, invece è stato rilevato “alpha(”.  Errore durante l’interpretazione di “filter”.  Dichiarazione tralasciata. home.css:4879:10
Previsto “none”, URL o una funziona filtro, invece è stato rilevato “alpha(”.  Errore durante l’interpretazione di “filter”.  Dichiarazione tralasciata. home.css:4887:10
Pseudo-classe o pseudo-elemento sconosciuto “-ms-input-placeholder”.  Insieme di regole ignorato a causa del selettore errato. home.css:5600:8
Pseudo-classe o pseudo-elemento sconosciuto “-webkit-input-placeholder”.  Insieme di regole ignorato a causa del selettore errato. home.css:5604:9
Pseudo-classe o pseudo-elemento sconosciuto “-ms-input-placeholder”.  Insieme di regole ignorato a causa del selettore errato. home.css:5637:40
Pseudo-classe o pseudo-elemento sconosciuto “-webkit-input-placeholder”.  Insieme di regole ignorato a causa del selettore errato. home.css:5641:41
Content Security Policy: Il caricamento di una risorsa su self è stato bloccato dalle impostazioni della pagina (“default-src http://127.0.0.1:2000 data:”). 127.0.0.1:2000
GET http://localhost:2000/ [HTTP/1.1 101 Switching Protocols 3ms]
:  home.js:13270:0
Content Security Policy: Il caricamento di una risorsa su http://localhost:2000/access.json è stato bloccato dalle impostazioni della pagina (“connect-src http://127.0.0.1:2000 ws://localhost:2000”). <sconosciuto>
GET http://127.0.0.1:2000/css/home.css [HTTP/1.1 200 OK 4ms]

**Comment by luckcolors** [comment]
if you need i can translate italian to english

**Comment by pfraze** [comment]
No need, GMail helped me out there. Here's the offending line:

```
Content Security Policy: The loading of a resource on http://localhost:2000/access.json was blocked by the settings of the page ("connect-src http://127.0.0.1:2000 ws: // localhost: 2000 " ). 
```

So that's keeping you from fetching an access token you need. Give me a few minutes to try to solve that, uno momento por favor

**Comment by pfraze** [comment]
@luckcolors ok, if you could please run `npm install -g scuttlebot` again and make sure you have `phoenix` version `4.0.2`, then try again please

**Comment by luckcolors** [comment]
works :)

**Comment by pfraze** [comment]
great! for a guy named @luckcolors, you really got unlucky stumbling onto our bugs :) Thanks for being patient with me.

I'm still not sure why `localhost` doesn't work, but that's on my todolist to solve now. I'm hoping it's just an ipv6 issue.

**Comment by luckcolors** [comment]
no problem. :)
