### ISSUE TITLE
blobs test hangs

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#137]
not sure what it is, but I just noticed that the blobs test never completes,
keeps on going around and around. strange because the other tests pass.

**Comment by pfraze** [comment]
I've experienced this inconsistently

**Comment by dominictarr** [comment]
okay so looking into this, it's generally taking 38 seconds for me, which probably feels like hanging sometimes... but I think this is not actually broken just slow. closing this issue for now.
