### ISSUE TITLE
should auth be part of the api or part of the connection?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#144]
I'm beginning to think that having `auth` be an api method is bad. It's quite different from the other methods, is required to be used before any of the others are, and has complicated state (your side can auth, and the remote side can auth, and those are different things)

What might be better, is create a connection, fully authorize it (so both ends know who both ends are and that everything is cool) and then pass it around to the various plugins.

This would also allow us to use the identities as part of the point to point encryption protocol.
And would mean that it's not necessary to make stick a permissions method on the rpc handle, which is improved security.

**Comment by pfraze** [comment]
Ok, I have some questions about this but I think they'll be answered by seeing what you try instead, so I'll hang back and see what you come up with

**Comment by dominictarr** [comment]
this is solved by secret-handshake
