### ISSUE TITLE
bin.js commands are failing because it attempts to use public IP for localhost

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#148]
I remember dealing with this before, but couldnt find the issue.

The `ssb-config` module is using `non-private-ip` to set the host. On my laptop, this is causing `bin.js` to stall indefinitely on a command. Issues:
- The connect attempt should timeout at some point, right now it doesnt
- I think `bin.js` is meant to default to localhost, so the use of `non-private-ip` is a problem there

**Comment by dominictarr** [comment]
are there steps are reproduce? (like, a particular network it happens on?)

**Comment by pfraze** [comment]
It's occurring on my home network.

I'll need to dig into it a bit to be sure about this, but my guess is --

The IP coming out of `non-private-ip` is for my house, in which case a connect-attempt terminates at my router.

**Comment by pfraze** [comment]
Ah, so I have my mac configured to disable all incoming connections in the software firewall settings. When I turn the firewall off, instead of a long nothing, I get an immediate ECONNREFUSED

**Comment by pfraze** [comment]
Still not sure why that is but it's a change

**Comment by dominictarr** [comment]
right, so the problem is that it's connecting to the local network ip address, instead of localhost?

`non-private-ip` means you have to do one less thing to set up a pub server (it autodetects it's ip when hosting). We changed this one time, forcing the client to connect to localhost,
but that broke setting a remote host and connecting to a remote with `ssb_host=<ip> sbot <cmd>`

hmm, maybe servers should use the non-local ip, but clients should use localhost when you are already on the same machine?

**Comment by pfraze** [comment]
> hmm, maybe servers should use the non-local ip, but clients should use localhost when you are already on the same machine?

yeah, we might consider a `--pub` switch, which might also be useful for enabling the pub-specific frontend (if we choose to go forward with that)

**Comment by dominictarr** [comment]
hmm, that might be simple enough, although if we make the network detection slightly smarter I think we could skip that.

**Comment by aredridel** [comment]
This happens for me, on a machine with IPv6 public IPs. Server listens on 0.0.0.0, bin.js connects on the v6 public.

**Comment by dominictarr** [comment]
do we need two servers to listen on BOTH ip4 and ipv6?

**Comment by aredridel** [comment]
If on linux and `v6only` is set, yes; otherwise, no, listening on v6 will listen on v4 too.

**Comment by aredridel** [comment]
(because v4 addresses fit inside v6 ones, they show up as `::ffff:ip.add.ress.here` in the system APIs when listening on v6; node does the right thing with this and exposes it as a v4 address.)

**Comment by clehner** [comment]
Would there be any problems with having sbot listen on `::` instead of `0.0.0.0`? This should allow both ipv4 and ipv6 clients to connect.

**Comment by dominictarr** [comment]
is this still an issue?
