### ISSUE TITLE
Failing to run CLI Usage example from README

### ISSUE THREAD

**Issue by noffle** [ssbc/scuttlebot#156]
I'm running a local `sbot` instance via `sbot server`, though when I run `sbot add --type post --text "hello world"` I get the following crash on the server-side:

```
/home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/validation.js:198
      if(!pub && !prev && next.content.type === 'init') {
                                      ^
TypeError: Cannot read property 'type' of undefined
    at validate (/home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/validation.js:198:39)
    at /home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/validation.js:149:7
    at /home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/validation.js:118:16
    at continuation (/home/sww/npm/lib/node_modules/scuttlebot/node_modules/cont/node_modules/continuable-para/node_modules/continuable-list/index.js:20:21)
    at /home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/index.js:152:24
    at /home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:15
    at /home/sww/npm/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:120:1
```

**Comment by pfraze** [comment]
Hey, sorry for the bug. Try using `publish` instead of `add`, and let me know if that works.

**Comment by noffle** [comment]
Thanks for the quick response! Yep: `publish` works perfectly.

**Comment by pfraze** [comment]
Ok, we borked `add` from the cli. We should do two things here...

 1. fix validation so this situation fails gracefully instead of crashing
 2. maybe update `bin.js` to alias `add` to `publish`, to avoid confusion, @dominictarr you agree?

**Comment by pfraze** [comment]
@noffle thanks for the report!

**Comment by noffle** [comment]
I don't mind grabbing these tasks -- they seem simple enough. I've been looking for a couple of easy bugs to get my hands dirty on scuttlebot.

**Comment by pfraze** [comment]
@noffle cool, that would be much appreciated. Ping me if you have any trouble, I'll be on #scuttlebutt in freenode.

**Comment by dominictarr** [comment]
@pfraze I think an alias is a bad idea... it seems like it would be easier on the user, but once you have made that thing backwards compatible, you have to keep it that way forever. It's much better to fail fast with a helpful error message.

**Comment by pfraze** [comment]
ok, then just fixing the crash bug should be enough

**Comment by dominictarr** [comment]
hmm, okay so don't crash on a malformed `add`

**Comment by noffle** [comment]
I think we still need to bump the version of `secure-scuttlebutt` we're depending on from `9.0.1` to current to see these fixes in effect.

**Comment by pfraze** [comment]
Published sbot `4.0.5` which bumps ssb to the latest.
I created a new feed and replicated @noffle's action, new validation code caught it correctly. Can you confirm, noffle?

**Comment by noffle** [comment]
I can confirm that I now get an `Error: invalid message` when using `sbot add <blah>` or even without args. It'd be nice to not have the validator throw this as an exception though, which generates a ton of noise around the error message.

However, `sbot publish` on its own throws
```
/home/stephen/npm/lib/node_modules/scuttlebot/bin.js:199
          if(err) throw err
                        ^
TypeError: Cannot read property 'type' of null
```

**Comment by dominictarr** [comment]
what would you rather see?

**Comment by noffle** [comment]
Something more informative: `Error: invalid message` or `Error: malformed command` seem more helpful to humans than `Cannot read property 'type' of null`.

**Comment by pfraze** [comment]
Moving the "error output" discussion to another issue and closing
