### ISSUE TITLE
bin.js publishing blob error

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#168]
This was tried:

```
cat ~/Downloads/882501_10200498639882524_1848434052_o.jpg | ssb_host=pub.dinosaur.is sbot publish --type contact --contact.feed "uHn+0odK8mnTViRwVnutQkwDqwaioiMkU2eDFbNrzcI=.blake2s" --profilePic.ext "--" --profilePic.size 111907 --profilePic.type "image/png" --profilePic.width 275 --profilePic.height 275
```

The resulting message:

``` js
{
...
  "content": {
    "type": "contact",
    "contact": {
      "feed": "uHn+0odK8mnTViRwVnutQkwDqwaioiMkU2eDFbNrzcI=.blake2s"
    },
    "profilePic": {
      "ext": true
    }
  }
}
```

**Comment by ahdinosaur** [comment]
actually the above command resulted in a hang, while

```
cat ~/Downloads/882501_10200498639882524_1848434052_o.jpg | ssb_host=pub.dinosaur.is sbot publish --type contact --contact.feed "uHn+0odK8mnTViRwVnutQkwDqwaioiMkU2eDFbNrzcI=.blake2s" --profilePic.ext "--" --profilePic.size 111907 --profilePic.type "image/png" --profilePic.width 275 --profilePic.height 275
```

resulted in the above message.

**Comment by pfraze** [comment]
RE: the first usage, like https://github.com/ssbc/scuttlebot/issues/169, the double-dash doesn't work, but the dot does.

RE the second usage, I wasn't able to reproduce. It worked for me with good and bad paths, and with the `..` up segments involved.

**Comment by dominictarr** [comment]
right the `"--"` becomes just `--` when minimist sees it, and that tells it to not parse the rest of the arguments. p.s. escaping does not work how you think it does in bash.

**Comment by pfraze** [comment]
> I think `--` might work, but only at the end i'd say.

my experience with #169 was that it doesnt, minimist didnt include the `--` in the args

**Comment by dominictarr** [comment]
this should work with `.` instead.
