### ISSUE TITLE
other desirable properties

### ISSUE THREAD

**Issue by calvinmetcalf** [ssbc/scuttlebot#173]
thinking about https://github.com/ssbc/scuttlebot/wiki/desirable-properties-for-a-secure-channel, another issue is statefullness vs sensitivity to lack of good random data.

If you can never repeat a message IV you could increment it, but that would leave you open to bugs where you repeat it if there is some sort of glitch where you loose your place, you could on the other hand pick one at random, but this would leave you vulnerable if you had limited entropy in the system or the prng was compromised/backdoored

**Comment by dominictarr** [comment]
by statefullness you mean remembering a changing key per peer? (and stuff like that?)

can you elaborate on how that defends against a lack of randomness?

**Comment by calvinmetcalf** [comment]
because by incrementing the IV you can use different ones each message with no change of ever repeating them, compared to picking them randomly which would repeat the iv.

**Comment by dominictarr** [comment]
hmm... intuitively i feel a little uncomfortable about this... I'm not sure that I trust a hard drive more than a random number generator... it's easy to see that everything working right it will always produce a unique number, but it seems failours could be predictable too - if someone could crash your server they could well cause you to forget what the last number...

is there a way you could get the best of both worlds?

**Comment by calvinmetcalf** [comment]
I'm staying that pure stateullness and pure random number reliance are both probably bad ideas and ideally you'd want both + some more, but some protocols rely on one or the other

**Comment by calvinmetcalf** [comment]
[over kill solution](https://gist.github.com/calvinmetcalf/853d31446e218e28bf2a)
