### ISSUE TITLE
RPC gets blocked/backed up (during sync)

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#174]
RPC roundtrip can get pretty high sometimes

Not sure what the cause is. It's observable during sync for a new user (when lots of feeds are being downloaded) I've had sbot take 20-30 seconds to respond (to ALL rpc) but this improves after sync finishes

I previously thought the write-stream might block the thread, but my tests https://github.com/ssbc/secure-scuttlebutt/pull/109 seemed to show otherwise. Maybe something related is blocking, or maybe the RPC queue gets bottlenecked somehow

**Comment by pfraze** [comment]
I started running sbot with the node `--prof` flag and the issue disappeared (of course!)

**Comment by dominictarr** [comment]
closing, as replication has been rewritten since then.
