### ISSUE TITLE
blob sync needs to handle a larger batch volume

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#175]
Blob download only seems to pull one blob per connection. During new-user onboarding this takes a while, especially when lots of peers are being polled and only one or two of them have the blobs you want.

This sucks for avis. Ideally a new user would use an invite code, and pretty immediately receive the user list and see their avatars.

**Comment by dominictarr** [comment]
that is certainly a bug.

**Comment by dominictarr** [comment]
this is merged so closing
