### ISSUE TITLE
prefer to sync with pubs that have a lot of unique pub-announcements

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#176]
I'm working on onboarding and finding that clutter in the list of announced pubs really slows down the sync process. There are 12 pubs in my table and only 3 of them are valid

The gossip plugin chooses randomly from the peer table, but weights the probability of selection. RN the only factor is number of previous failures (it's less likely to select a peer if past connect attempts have failed). I suggest we also increase the odds for pubs which have a lot of unique users publishing announcements for them.

**Comment by dominictarr** [comment]
This is a great idea!
