### ISSUE TITLE
more instrumentation

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#180]
My logging/monitoring wishlist for my pubs
- Memory usage (total, per connection)
- CPU load (total)
- Bandwidth usage (total, per connection)
- Connections (IP, authed pubkey, how long the connection lives)
- All RPC calls (method called, who called it, RTT)
- Messages transferred up/down
- Blobs transferred up/down

Not all of this has to come from sbot but if it can, even better. Are there some good monitoring & log-viewing tools we can use? Can we hook something in with our logging system?

**Comment by dominictarr** [comment]
yes, we'll need this stuff for optimization. 
I am a little worried about privacy here, it might be better not to log some calls.
aggregated stats like connections messages and blobs moved should be fine though.
