### ISSUE TITLE
Speed up gossip at load

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#182]
Gossip goes pretty slow right now, connections are scheduled once every 15-30s by default. This is ok, except at load when you have a lot of bad peer-announcements to work through -- you can easily go a minute or two without reaching a good peer. Over time, the bad peers get a low weight, and the issue goes away

I suggest doing a rapid iteration through the peers list on load, starting with seeds, then LAN-discovereds, then in order of number of announcements, up to (say) 50 peers. That way we can quickly get updated data at startup, and discover which peers are unreachable and give them a lower weight

**Comment by dominictarr** [comment]
good plan, also maybe if a peer was bad you could go straight to testing another peer, although, make sure you don't trash if connections are failing for another reason. "bad" peers should still be called, they should just be called much less frequently.

**Comment by dominictarr** [comment]
gossip is WAY faster now, so closing this.
