### ISSUE TITLE
onboarding road bumps

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#184]
I was trying to onboard @jessykate yesterday, and we ran into a few road bumps.

the first thing was that my pub server was running old code and was listening on port 2000, but now the client assumes the default port is 8008. This meant the connection failed. 1) Invite codes should probably include the port.

2) the error message in the ui was not informative. we want something that can be copypasted into an issue. It should probably be the same as the error from the command line.

3) what does the "Sync" tab on network mean?

hmm... it seems that my pubserver was not using the correct version? it was running on port 2000, and was not displaying follows correctly...

when I clicked on activity for my pub it showed some correctly formatted follows, such as this follow for @no9

```
{
  "previous": "amu2PSw10ofSgLpkfo5bJWHw3elcr3kQVShuGyk58Tg=.blake2s",
  "author": "TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s",
  "sequence": 19,
  "timestamp": 1431825913905,
  "hash": "blake2s",
  "content": {
    "type": "follow",
    "feed": "5M9OgE0/TiZQOHbHqv4X7n2jBZKCbWQ8YlSv2znmpTc=.blake2s",
    "rel": "follows",
    "auto": true
  },
  "signature": "jE1g0+9LiS6LP4ZYKOdi4dUSR+a/t7iKamO6iaBzYK4+n8XlP/vej9rjoLIWW+zHX01WlgFuzqchmcQSSlC4Sw==.blake2s.k256"
}
```

but @jessykate showed up as

{
  "previous": "skbhsPaKFRxv5xZSR80BSPKqJmtOMDAwS2Fw6KIvnLA=.blake2s",
  "author": "TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s",
  "sequence": 18,
  "timestamp": 1428330230168,
  "hash": "blake2s",
  "content": {
    "type": "contact",
    "contact": {
      "feed": "SiNBesB0AKtYiIY40mxja8hKmd+QQY/YBL7CwXIQklg=.blake2s"
    },
    "following": true,
    "autofollow": true
  },
  "signature": "Ee8bTN6tFd7xgXCoq/7guRfKp+tcxLdXMQzVTCcPftnJnmywj3jjVea6f/n3HH0reTSVrejKNmZ4FahVv0A3PA==.blake2s.k256"
}

**Comment by pfraze** [comment]
RE 2, what error code did you receive? The invite code UI tries to give an understandable explanation, https://github.com/ssbc/phoenix/blob/master/src/app-ui/modals.js#L108, and it logs the exception in the console, https://github.com/ssbc/phoenix/blob/master/src/app-ui/modals.js#L90. If you got an opaque message, then that means it's a bug

RE 3, the sync tab organizes the known users according to peers you've established a direct connection with

`type: follow` was deprecated in favor of `type: contact` a while ago, we discussed it in an issue

**Comment by dominictarr** [comment]
@pfraze re 2) the error message was:  "Sorry, an unexpected error occurred. Please try again."

but it should be "could not establish connection to server"

 For example, try this invite code: `176.58.117.63:8001,TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s,+EQnurTDOW5hyPKiwIeDAFcN0urcxkE26cSHr1netv0=`

(which wont work because the port is wrong)

**Comment by pfraze** [comment]
ok that's a bug, the handler isn't watching for `ECONNREFUSED` yet

**Comment by dominictarr** [comment]
if we see an error we don't know it should probably just display the stack trace, and ask them to post an issue.
"sorry we weren't expecting this error, please tell us about it"
