### ISSUE TITLE
Problems during the npm install on Windows 8

### ISSUE THREAD

**Issue by Qqwy** [ssbc/scuttlebot#185]
I am having trouble installing Scuttlebot.
My system's Specifications:
-Windows 8 (x64)
-Node v0.12.3
-Python v 2.7, as well as v 3.4.1 (I tried to follow the instructions [here](https://github.com/TooTallNate/node-gyp#installation) but changing the config value to point to the Python 2.7 folder did not change the output of the script.)
-Microsoft Visual Studio C++ 2013 Express has just been installed as well.

It seems  to me that I won't be the only one with this kind of issue during the installing.
Any help to fix this issue would be appreciated. 

Below is the traceback I get:

```
$ npm install -g scuttlebot
|


> ws@0.5.0 install C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebo
t\node_modules\pull-ws-server\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\node_modules\pull
-ws-server\node_modules\ws>if not defined npm_config_node_gyp (node "c:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\
node-gyp.js" rebuild )  else (rebuild)
-
> leveldown@0.10.5 install C:\Users\gebruiker\AppData\Roaming\npm\node_modules\s
cuttlebot\node_modules\secure-scuttlebutt\node_modules\level\node_modules\leveld
own
> node-gyp rebuild


C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\node_modules\secu
re-scuttlebutt\node_modules\level\node_modules\leveldown>if not defined npm_conf
ig_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: spawn C:\Python27 ENOENT
gyp ERR! stack    at exports._errnoException (util.js:746:11)
gyp ERR! stack    at Process.ChildProcess._handle.onexit (child_process.js:1053
:32)
gyp ERR! stack    at child_process.js:1144:20
gyp ERR! stack    at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\node
_modules\secure-scuttlebutt\node_modules\level\node_modules\leveldown
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
-
> ws@0.5.0 install C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebo
t\node_modules\ssbplug-phoenix\node_modules\ssb-client\node_modules\pull-ws-serv
er\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\node_modules\ssbp
lug-phoenix\node_modules\ssb-client\node_modules\pull-ws-server\node_modules\ws>
if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  els
e (rebuild)

> ws@0.5.0 install C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebo
t\node_modules\ssbplug-phoenix\node_modules\pull-ws-server\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\node_modules\ssbp
lug-phoenix\node_modules\pull-ws-server\node_modules\ws>if not defined npm_confi
g_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "scuttlebot"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!    node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!    npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    c:\Users\gebruiker\node\scuttlebot\npm-debug.log
```

I hope you can help; I really want to try Scuttlebot out :-).

Sincerely,

~Qqwy

**Comment by pfraze** [comment]
What did you write for your python 2.7 gyp config?

this line:

```
node-gyp --python /path/to/python2.7
```

**Comment by Qqwy** [comment]
I wrote `node-gyp --python "C:\Python27"`, which is the location where Python 2.7 is stored on my computer.

**Comment by pfraze** [comment]
Try setting it to the path of the python exe

**Comment by Qqwy** [comment]
Oh... hah. That fixed the problem. The installation finished now. Thank you very much!

Another probably related thing is happening now, however. When trying to run `sbot server`, I recieve the following error stack:


    $ sbot server
    c:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\node_modules\secu
    re-scuttlebutt\node_modules\level\node_modules\leveldown\node_modules\bindings\b
    indings.js:83
            throw e
                  ^
    Error: Module did not self-register.
        at Error (native)
        at Module.load (module.js:339:32)
        at Function.Module._load (module.js:294:12)
        at Module.require (module.js:349:17)
        at require (module.js:368:17)
        at bindings (c:\Users\gebruiker\AppData\Roaming\npm\node_modules\scuttlebot\
    node_modules\secure-scuttlebutt\node_modules\level\node_modules\leveldown\node_m
    odules\bindings\bindings.js:76:44)
        at Object.<anonymous> (c:\Users\gebruiker\AppData\Roaming\npm\node_modules\s
    cuttlebot\node_modules\secure-scuttlebutt\node_modules\level\node_modules\leveld
    own\index.js:1:99)
        at Module._compile (module.js:444:26)
        at Object.Module._extensions..js (module.js:462:10)
        at Module.load (module.js:339:32)

What is going on?

**Comment by pfraze** [comment]
Ive never seen that, you might try a reinstall now that python is configured. Googling got some hits, you might try digging

**Comment by kylerschin** [comment]
Close this issue.
