### ISSUE TITLE
user invite

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#191]
currently, only pub server owners can create invite codes.

Alice wants to invite Bob to use secure-scuttlebutt. Alice joined the network by using an invite code to Paul's pub server. Paul is currently hungover in some airport, and is not available to create an invite code for Bob.

Currently, this means Alice would need to start her own pubserver, or wait for Paul to regain full consciousness. But what if Alice was able to invite Bob herself?
- this could be an invite to a specific pubserver
- an open invite, to ask any pub that follows her to follow bob... which would require multiple pub addresses in one invite code...

Bob would install the software, connect to a pub server, and post some message revealing himself to have used Alice's invite. When alice next replicates with that pub server she will get Bob's feed, see that message, and know that they used her invite. The software will prompt her to confirm whether this is Bob and officially follow him.

This would mean Alice could invite her friends to use SSB without having to ask anyone's permission.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by pfraze** [comment]
When gmail was first starting, you'd need an invite to join, and the UI would tell you "hey you have 5 invites," and you could use them from there

We could do something similar, by having pubs send the invites as encrypted messages to their members, as they have capacity.

That might generate less noisy traffic than if users polled their pubs every time they wanted an invite
