### ISSUE TITLE
Memory leak in level triggers

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#194]
Relevant to #82 
@dominictarr Im going to need your help with this one

Turns out a major memory leak is the `hooks` array in [sublevel](https://github.com/dominictarr/level-sublevel/blob/master/hooks.js). The cleanup function https://github.com/dominictarr/level-sublevel/blob/master/hooks.js#L12-L15 is, afaik, never getting called.

One cause I've found is in replication. Unfortunately I cant copy out the stack trace. The peer calls `createHistoryStream` with `live: true`. That calls pull-level's read with `live: true`, which eventually calls `live` in pull-level index.js:14 and puts the return value in a pull-cat. 

The `live` function in pull-level creates the level-sublevel hook by calling `post` in https://github.com/dominictarr/pull-level/blob/master/index.js#L19. The returned cleanup function is never called, however, which seems to indicate that an `end` signal isnt making its way to the pull-stream that `live` returns. @dominictarr you have any ideas why that might be?

**Comment by dominictarr** [comment]
yeah I could hazard a few guesses. while working on ssb replication I realized that I had made a blunder when I was originally specifying how pull streams worked, and the spec I had settled on had no way to abort live streams that had stalled. I was able to change the spec and most things still worked, with only a small rework of the various parts. So I suspect the answer is that there is some part involved,
probably https://github.com/ssbc/scuttlebot/blob/master/plugins/replicate.js#L45 that does not pass on the abort message quite right.

I have finished the crypto stuff I was working on for now, so I have bandwidth to take this on next.

**Comment by dominictarr** [comment]
okay looking into this now.

**Comment by dominictarr** [comment]
okay this is something about the chain of streams from the createHistroyStream not being cleaned up...
digging deeper...

**Comment by dominictarr** [comment]
history stream is aborted correctly when used from the cli client, but it seems to not be aborted correctly during replication... not sure why yet
