### ISSUE TITLE
remove plugins?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#198]
The only thing we actually use the pluggable nature of the plugins for is removing some functionality during a test... I'm thinking that maybe "plugins" isn't the right way to think about these

**Comment by pfraze** [comment]
Im a bit indifferent.

Removing plugins would simplify the manifest construction

If we could get away from the internal events-system, I'd be happier
(events control-flow is more difficult than function call)

**Comment by dominictarr** [comment]
@pfraze do you mean the transmitted events? (there is only "done" and blobs uses 2 events)

just tabling it for now really, I'm not sure, I just don't feel that "plugin" is a clean abstraction.

**Comment by dominictarr** [comment]
actually not sure that "plugin" is ever a clean abstraction?

**Comment by pfraze** [comment]
@dominictarr no, I'm referring to the internal events system. It'd be easier to know, for instance, what happens on a new connection if we called out to plugin methods instead of having the plugins register handlers

though we still need to secure that networked emit

**Comment by dominictarr** [comment]
@pfraze got it. yeah I'm just gonna kill the muxrpc emit, because the permissions system is otherwise good enough right now.
