### ISSUE TITLE
posting a message should trigger a replication.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#223]
when you post a message, you obviously want that to go out to the network, so replication should be pritorized after posting a message.

**Comment by pfraze** [comment]
If there are pubs which the user knows they want to sync with, then we could track whether messages have been synced out to those pubs. The UI could then reflect that sync state, and let the user know if msgs have been sent out or not.

**Comment by dominictarr** [comment]
that is a good idea! use pubs the user follows. it's easy because you just have to remember which sequence number they have of yours.

**Comment by pfraze** [comment]
:+1:
