### ISSUE TITLE
race condition in plugins/invite

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#224]
This is a security bug that may enable a holder of an invite code to request a follow more times than they should.
https://github.com/ssbc/scuttlebot/blob/master/plugins/invite.js#L86

they would make many requests and then make the follow request at the same time. if these requests are received before the local database calls back, they count may not be consistent.

**Comment by dominictarr** [comment]
the solution is some sort of transaction system. One simple way to do this would be to only process one follow at a time. another way would be to keep the current number of uses in memory, incase a follow is in progress.

**Comment by pfraze** [comment]
Good catch. 

One-at-a-time may be feasible, at least in the short-term. If we know the average processing-time, we know the throughput. (eg, 5ms processing = 200 invites per second.) Knowing that limit, we just need to avoid mailing out invites to a crowd that could outmatch the throughput.

But, there may be other just-as-simple approaches.
