### ISSUE TITLE
installing 7.2.1 returned error

### ISSUE THREAD

**Issue by myf** [ssbc/scuttlebot#230]
use nvm for iojs-2.5.0, errored at the end when trying to chmod sbot.js

the previous version was built with the same method and it was okay.

`nvm use iojs-2.5.0`
`npm i -g scuttlebot`

```
make: Leaving directory '/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/ssb-keys/node_modules/chloride/build'
npm ERR! Linux 3.8.4-1-ARCH
npm ERR! argv "/home/myf/.nvm/versions/io.js/v2.5.0/bin/iojs" "/home/myf/.nvm/versions/io.js/v2.5.0/bin/npm" "i" "-g" "scuttlebot"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! path /home/myf/.npm_packages/lib/node_modules/scuttlebot/sbot.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/myf/.npm_packages/lib/node_modules/scuttlebot/sbot.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/myf/npm-debug.log
```

**Comment by dominictarr** [comment]
Ah this is becasue npm runs prepublish after you run `npm install .` even though _obviously_ prepublish should be run before _publish_.

They are gonna fix this one day: https://github.com/npm/npm/issues/6887

I think your installation should still work though... can you confirm?

I'll make it not error.

**Comment by myf** [comment]
@dominictarr currently I installed it locally in the directory and use `./bin` as `sbot`. If that's what you were referring to, the installation is working. The only thing that failed to work is using npm to install an executive `sbot`

sorry for the late reply

**Comment by dshimkoski** [comment]
Same deal here, only I can't get a `npm -f install` to work either.

**Comment by dominictarr** [comment]
I have removed the chmod command, so hopefully this will work, please reinstall scuttlebot@7.2.5 and let me know what happens

**Comment by pfraze** [comment]
Turns out the issue was that `.gitignore` had `sbot.js` listed. I added a `.npmignore` without that, and it now works (as of `7.2.6`)

**Comment by dominictarr** [comment]
oh, hmm... i wanted git to ignore that so that it wasn't checked in, but now i remember that npm uses .gitignore if there isn't a .npmignore because npm likes to be helpful like that... thanks npm.

**Comment by pfraze** [comment]
This has been solved
