### ISSUE TITLE
using scuttlebot as a backend for a data api

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#233]
to throw some spaghetti at my [suggested product angle](https://github.com/ssbc/scuttlebot/issues/146#issuecomment-103306434), i'm curious to see if it's possible and/or practical to use scuttlebot as a backend database, as with [holodex](https://github.com/open-app/holodex) [[demo](http://holodex.enspiral.com)] at the moment i'm [planning to re-build our data api](https://github.com/open-app/holodex/issues/80).

in the interest of practicality, i'm not aiming to achieve the ssb utopia where every agent (person or group) manages their own keys, their own feed, :sunny: and :rainbow:. rather, there should be a spectrum from the current way apps are deployed (on public servers controlled by a single agent and isolated from other servers' data) to the utopia, so developers can slowly migrate their users without interrupting the existing service.

some terminology:
- agent: a person or a group
- member: an agent who is part of a group
- host: an agent who runs a pub server that manages feeds for its members

> [notes from a previous self:](https://github.com/open-app/core/blob/05a22ab1705a34fa74b2794ca2069aa46cca0d8d/notes.md)
> - every agent should have complete control of their data and how it is shared. they have to trust their host (either them or a group they are a member of) who actually stores the data to enforce their control.
> - i've been thinking about nodes as agents, which includes people or groups (or projects which i think are short-term groups). then, as not every agent wants to host themselves in the network, group agents can host their members. we can achieve federated querying amongst network-of-networks with http://linkeddatafragments.org/.

in our current use case, [Enspiral](http://enspiral.com) would be a host agent for [the people and groups within Enspiral](http://holodex.enspiral.com). however, any of these members may be their own host, thus creating a federated mesh of hosts where each host has access to all the data of entire network of agents. for the Holodex implementation, i imagine "being a host" would be running the Holodex app on a public server, where we use scuttlebot as a backend to handle data operations (on each agent's feed), replication (across hosts), and queries (linked data), which we use to export a standard http / websocket api interface.

so, @dominictarr, some documentation on how to use scuttlebot as a backend for a data api would be magical. :sparkles:

**Comment by pfraze** [comment]
Hey @ahdinosaur, I'm documenting now! Get with me on IRC about your implementation.
