### ISSUE TITLE
Invite plugin references `req.keyId`, not sure where that comes from

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#236]
https://github.com/ssbc/scuttlebot/blob/309331056745beb18fba1442452c40bfc3f1f302/plugins/invite.js#L112

Is `req.keyId` correct? It's not validated by `use`, and `accept` doesnt seem to send it.

**Comment by dominictarr** [comment]
good spotting! this bug means that invite codes never expire! it should be `rpc.id`
