### ISSUE TITLE
Recommended use by other apps: embed, or run as an external service?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#238]
I'm working on docs for people to build on sbot, and I want to give instructions on how to package sbot in an application.

Say, for instance, you're building your own patchwork. How would you build your application, so that it works well if the user wants to use it _alongside_ patchwork?

Embedding: We could write it such that, if another app is already running with their embedded sbot server, then the current app just goes into "client-mode" to the existing sbot. 
- If the other app closes, the current app will try to start its sbot. If it fails to acquire the leveldb lock and the socket, it'll assume another app started its sbot first, and it will try connecting to it. 
- So, eventually, one of the user's apps will get the server going, and host all the others.

Service: We use something like https://github.com/tomas/satan that lets the service persist beyond the applications themselves. This might be more stable? But it also involves some management.

**Comment by pfraze** [comment]
One problem with embedding: versions. Applications may embed different versions, and have problems as a result.

Another option for embedding, is to have each application run their server independently, on different ports, with different data-directories, and different keypairs.

**Comment by pfraze** [comment]
If we're embedding, we might be able to use the shared config (`~/.ssb`) to coordinate versions. The sbot embed could write its version in the DB (we do that already, I believe, for the index rewriting logic). Then, if an sbot tries to start and sees it's out of date, it can abort and error.

**Comment by dominictarr** [comment]
If people are gonna run multiple ssb applications at once then writing those as a service will probably be easiest. But you gain extra flexibility by embedding ssb. And easier updates by making your application a brickhouse app... it's a tradeoff.

**Comment by pfraze** [comment]
Since Brickhouse will solve service management, I'm inclined not to invest in any solution until BH is ready. Since we're still in a developer preview, perhaps we should tell users to install sbot separately and run `sbot server` on their own, before running an application that depends on sbot?

**Comment by dominictarr** [comment]
the documentation does not have to be the final answer. it's interesting to get into a new technology on the ground floor because you can help figure it out! so we can just say you could approach it either of these 3 ways.
