### ISSUE TITLE
Is `npm ls` worth including in prepublish?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#240]
`npm ls` will fail if you have "extraneous" folders in your `node_modules`.
I have extraneous modules, fairly frequently, from switching between branches where package deps are added.

**Comment by dominictarr** [comment]
I put `npm ls` in because it is pretty good at preventing you publishing things with the wrong deps.
though I acknowlegde that this is just a hack around the fact that npm does a less than ideal job at ensuring you are on the same codebase (i.e. not as good as git)

**Comment by pfraze** [comment]
Yeah, just a pain to have to add and remove modules when you switch branches
