### ISSUE TITLE
Avoid discouraging the gossip process

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#242]
I've been noticing, after a period with an internet connection, the gossip won't resume. Looking at the sync page in PW, it's clear sync attempts aren't occurring (because the timestamp of the last attempt is old). I believe this is because each peer racks up a high failure-count during the downtime, and `plugins/gossip.js#choosePeer` doesnt require that a peer is selected.

One possible solution is to choose a peer at random, without any weighting, if the first weighted selection fails to return a hit.

**Comment by pfraze** [comment]
I'm at a place with spotty internet, so I get frequent drops. I added logging to gossip's peer selection and confirmed, after a short period of downtime, the peers rack up enough failures that selection becomes "discouraged."

This might be a sign that the peer selection may be a little too strict. But, more to the point, we should probably just choose a random peer if the weighted selection fails, right?

**Comment by pfraze** [comment]
Hmm, actually I'm noticing now that the scheduler hasn't tried to select a peer again. This may not be what I thought it was. It may be that `schedule` isn't getting called.

Adding more logging.

**Comment by pfraze** [comment]
Ah, yeah. The `count` variable is not decreasing properly. Trying a fix

**Comment by dominictarr** [comment]
oops, spotty network and couldn't post the following:

This shouldn't be linear, but it should be relative to the other peers... it should just pick the better peers.
this paper explains what dynamo db uses. 
http://vsedach.googlepages.com/HDY04.pdf

This is quite a long paper, but it isn't actually that compilicated. I havn't actually read the paper, but I understand the basic idea is that it calculates the probability that a given peer is alive, based on the probability that it has received a message (or a connection) from it.

It's not good manners to link to a paper that I havn't actually read, so I'm looking for the simple explaination of it... AHA there is a module: https://www.npmjs.com/package/phi-accrual-detector

**Comment by dominictarr** [comment]
hmm, this _might not_ be relavant since it is based on a model of regular heartbeats, which doesn't quite fit.
I also recall (i think in the  flowgossip paper http://www.cs.cornell.edu/home/rvr/papers/flowgossip.pdf) 

hmm, man I can't find the explaination that I was looking for...

basically, i suspect that the thing is the "badness" of a peer should never go to zero, and if there isn't a reasonable peer to connect to, it should randomly connect to any peer. then you still get eventual consistency.

**Comment by pfraze** [comment]
We can improve on the pub-rating algorithm, but it turns out that was not the specific cause of this issue. Rather, the problem was that the active-connection count was not decremented when a connection failed, and eventually this caused no connection to be scheduled at all. #248 solves this issue.

**Comment by dominictarr** [comment]
ohh, okay great
