### ISSUE TITLE
sbot crashed, re npm install failed

### ISSUE THREAD

**Issue by mixmix** [ssbc/scuttlebot#244]
didn't pay attention to why it crashed. 
I git pulled current master, deleted `node_modules` and ran npm install again. 

hit this 
```
TAP version 13
# test invite api
/home/scuttlebot/scuttlebot/test/invite.js:37
      if(err) throw explain(err, 'cannot create invite code')
                    ^
Error: cannot create invite code
    at /home/scuttlebot/scuttlebot/test/invite.js:37:21
    at Object._requests.(anonymous function) (/home/scuttlebot/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream.destroy (/home/scuttlebot/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:73:66)
  Error: unexpected end of parent stream
    at PacketStream.destroy (/home/scuttlebot/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:68:11)
    at PacketStream.write (/home/scuttlebot/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:121:41)
    at /home/scuttlebot/scuttlebot/node_modules/muxrpc/pull-weird.js:57:44
    at /home/scuttlebot/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:11:20
    at /home/scuttlebot/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at Object.cb (/home/scuttlebot/scuttlebot/node_modules/packet-stream-codec/index.js:98:24)
    at drain (/home/scuttlebot/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-reader/index.js:27:23)
    at /home/scuttlebot/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-reader/index.js:44:18
    at Object.cb (/home/scuttlebot/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:131:18)
    at drain (/home/scuttlebot/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/node_modules/pull-reader/index.js:24:14)
npm ERR! Test failed.  See above for more details.

```

**Comment by mixmix** [comment]
in good news `npm install -g scuttlebot` is working, so using that now !

**Comment by pfraze** [comment]
Yes, glad to hear -g is working. Testing sbot for myself now...

**Comment by pfraze** [comment]
Did you run those tests on a pub?

**Comment by mixmix** [comment]
no, i think those test were run by the pre-publish script when I ran `npm install` on the cloned repo
```
    "prepublish": "npm ls && npm test && noderify bin.js > sbot.js",
```

I think i saw a command like that one called before the tests started.

**Comment by pfraze** [comment]
Yeah that's probably what triggered it. Im having trouble diagnosing this one, though, because it doesnt happen for me.

So what I'm wondering is, did it happen on your pub, or on your personal device? If it's on a pub, it'll have a public IP, which may alter the behavior and account for why I dont get an error, but the pub does.

**Comment by mixmix** [comment]
Yes those tests were on pub, it was me trying to get the pub up and running
using the cloned master branch (because previously -g had been failing)

trying `npm install` on scuttlebot repo locally now. I'll assume that
works, but let you know if it doesn't

**Comment by pfraze** [comment]
Huh, tried it on a public device, didn't have a problem. Have you tried installing again?

**Comment by mixmix** [comment]
`npm install` worked fine locally.   haven't tried it on server since `npm
install -g` worked fine.

want me to try it again ?

**Comment by pfraze** [comment]
hmm, no that's ok. Going to leave this open, in case somebody else experiences it. Weird bug.

**Comment by dominictarr** [comment]
This might be a weird configuration edge case.
by default it refuses to create an invite unless you have a public ip address
https://github.com/ssbc/scuttlebot/blob/master/plugins/invite.js#L53-L57

but there is a option to turn that off via `allowPrivate`

this UX bug where npm runs the prepublish script when you run `npm install` even though you said you wanted prepublish not prepublishorinstall is _really_ annoying. The only person who seems to think it's the right idea is @isaacs. But a bit of digging https://github.com/npm/npm/issues/3059#issuecomment-55679766 revealed that if you run `npm install --production` it doesn't run.

Okay I have just made a PR to npm to fix this... https://github.com/npm/npm/pull/9722 :pray:

**Comment by ahdinosaur** [comment]
hehe @dominictarr :joy:.  to fix the `prepublish` script without help from the gods, [`in-publish`](https://www.npmjs.com/package/in-publish) should help.

**Comment by ahdinosaur** [comment]
felt a stroke of inspiration and did [another PR](https://github.com/npm/npm/pull/9733), it really should be changed.
