### ISSUE TITLE
Daemonized server

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#254]
1. The `sbot server` command should spawn as a background daemon by default.
2. Running as a foreground process should be a flag on the `server` command (eg `--fg`).
3. There should also be a command for connecting to the server and outputting the log.
4. The `server` command should have a flag for spawning the background daemon in the background, then spawning a logger-output process in the foreground (eg `--log`).

**Comment by bcomnes** [comment]
Can we not just let systemd handle demonization?  The most direct way to do that is to have the bin start a server that logs to stdout/err and write a systemd service file.  It monitors the process for crashes, collects logging from stdout/err and lets you start it in the correct context with the correct read/write permissions.

**Comment by pfraze** [comment]
Yeah this never really picked up steam, I say we dont worry about it

**Comment by bcomnes** [comment]
I'll PR some example service file stuff I've its polished.
