### ISSUE TITLE
Push-messaging via intermediaries, with capabilities

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#256]
Suppose you wanted someone to send messages to you, without friending them. This might be to manage an account on their service, or to speak with a stranger. The world uses email for this now, but you can't revoke the email address after giving it, and you can't hide your global identifier (the email address).

So, what if pubs had an API to accept `type: post` messages from other users, which it would encrypt to you, and post it on its feed. Since you follow the pub, you would receive the message. The message would have to include special information about the _real_ author, inside it.

Like with invites, you would request capabilities from the pub, to give out for this. The capability would be opaque and revokable.

Ideally, the message would be encrypted before giving it to the pub. This _might_ require encrypting the message twice: once by the sender, using a key included in the capability, and again by the pub to send to you. But, I bet there's a nicer way to do things if we poke at it a bit.

**Comment by dominictarr** [comment]
I have thought about this idea too, and I agree it should be encrypted twice - the relaying server does need to know it's content, but it does need to know their id, and the recipient needs to know that the server really did verify the sender created that message. (we don't want the sender to relay someone else's encrypted message)
