### ISSUE TITLE
blocking: handle new schema for block messages based on negative votes on a user.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#259]
This was the change:
https://github.com/ssbc/ssb-msg-schemas/compare/8cb9bdd4433237c3ccb69f0bdf439386e9670791...master

**Comment by pfraze** [comment]
is the `blocking` flag in `type: contact` not getting used?

**Comment by dominictarr** [comment]
it checks for `flagged`

**Comment by dominictarr** [comment]
https://github.com/ssbc/scuttlebot/blob/master/plugins/block.js#L54-L57

**Comment by dominictarr** [comment]
and https://github.com/ssbc/scuttlebot/blob/master/plugins/friends.js#L54-L58

**Comment by pfraze** [comment]
Hm. We got out of sync sometime all the way back in the summer. `flagging` hasn't been a part of `type: contact` since the big redeploy.

**Comment by pfraze** [comment]
Im a little bit confused, tbh, I'm pretty sure we reviewed all of this. Digging into it.

**Comment by pfraze** [comment]
Ok, looks like we moved to `blocking` inside of `type: contact` in late august (https://github.com/ssbc/ssb-msg-schemas/commit/7fce7ad1c6de82434645d1f82a3d76e5f3940d7b) and blocking was done in late july (https://github.com/ssbc/scuttlebot/pull/211).

**Comment by pfraze** [comment]
Two action points on this:
 - I shouldn't be making changes to ssb-msg-schemas without PRs, even if we discuss the changes prior. That's obviously interrupted our flow, twice now, for coordinating changes between sbot and pw.
 - We should decide, if downvotes or `type: contact, blocking: true` does blocking.

**Comment by dominictarr** [comment]
we should also figure out how the disconnect between blocking and flagging happened. did patchwork use `flagging` at one point?

**Comment by pfraze** [comment]
Yeah, but a long time ago -- when we had adverts in there. I think when blocking got written, `type: contact, flagging: true` may have been right, but we did a schemas rewrite a month after, and somehow blocking didnt get updated. 

It's weird though. Prior to today, I thought sbot was using `type: contact, blocking: true`.
