### ISSUE TITLE
Pub is maxing CPU

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#270]
Since updating to latest, my linode pub (slip.space) has been maxing out its CPU. The CPU usage, according to htop, tends to hover in the 80% range, but varies from 50 to 100. Node is 4.2.1, npm is 3.x, and sbot is 7.4.3. Clean npm install.

My immediate guess was that JS_CHLORIDE is being used, but there's no error output to indicate that's happening. Is there an easy way to check?

**Comment by aredridel** [comment]
Hm. This is happening to me too.

**Comment by pfraze** [comment]
We're starting to see some quota overage warnings (I think for johnny), maybe something weird is happening related to that?

**Comment by pfraze** [comment]
I'm seeing some high disk rate warnings too. @dominictarr is it possible that the quota rejection is not stopping the blob-sync from attempting to fetch files? Continuously fetching, validating, then removing (due to quota) a blob might explain this.

**Comment by dominictarr** [comment]
yeah I think it's something like that. If it doesn't have anything to download it just keeps on checking...

**Comment by gardner** [comment]
Is anyone good at profiling node apps? <img width="1552" alt="screen shot 2016-01-31 at 11 21 39 pm" src="https://cloud.githubusercontent.com/assets/787026/12701561/7a0993b8-c871-11e5-97e4-395be06f2c0b.png">

**Comment by pfraze** [comment]
@gardner some bugfixes have landed lately RE this issue, are you running everything up-to-date, the repo and npm deps?

**Comment by gardner** [comment]
I'm running scuttlebot@7.5.2 from the npm repo. I just did an npm update and npm upgrade. I'll bounce the vps and wait to see how it goes.

**Comment by evbogue** [comment]
This issue was solved somewhere along the way. Probably `persistent-gossip`? Now we still have high RAM usage, but not CPU as far as I can tell.
