### ISSUE TITLE
Is the gossip plugin supposed to use config's .gossip.seeds or just .seeds?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#277]
Currently the gossip plugin uses `config.seeds` instead of `config.gossip.seeds` (https://github.com/ssbc/scuttlebot/blob/master/plugins/gossip.js#L156) wanted to confirm that's the intended behavior

**Comment by dominictarr** [comment]
I guess it should be `config.gossip.seeds`. This should only affect the
tests though.

**Comment by evbogue** [comment]
gossip/init.js still uses `config.seeds`. https://github.com/ssbc/scuttlebot/blob/master/plugins/gossip/init.js#L9

but I think it's fine to close this issue, because `config.seeds` is seems to be how we load seeds these days.
