### ISSUE TITLE
Blobs.add doesnt output hash-id when used from the CLI

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#284]
Test with:

```
echo "hello, world" | sbot blobs.add
```

Does not return any hash

**Comment by dominictarr** [comment]
this would require the change (discussed previously) to add callbacks to one way streams on muxrpc.

**Comment by pfraze** [comment]
Hmm yeah, how do you figure we should deal with this in the short term? Should we special case the muxrpcli for this method?

**Comment by dominictarr** [comment]
this only happens when you do `blobs.add` without posting a message, see code for publish which has a special case to post attachments.

**Comment by pfraze** [comment]
That's true, but I think it'd be nice to have blobs.add work this way. Would you object to me adding a special case for that?

**Comment by dominictarr** [comment]
@pfraze go ahead!
