### ISSUE TITLE
Don't test on local install

### ISSUE THREAD

**Issue by bcomnes** [ssbc/scuttlebot#295]
I've been setting up my pub to run closer to HEAD and have discovered that the prepublish script is resulting a large set of tests running every time I `npm i`, `npm link` etc... 

Can we set up the npm scripts not to run these on install?  Its getting in the way of deployment of a `devel` install.

**Comment by pfraze** [comment]
I'd be fine with this, @dominictarr ?

**Comment by bcomnes** [comment]
I'll send a pr with what I would be happy with, preserving the existing behavior on another script and see what people think.

**Comment by evbogue** [comment]
Test doesn't run on `npm install` anymore, closing.
