### ISSUE TITLE
Retweet like functionality

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#301]
I was reading the docs (https://ssbc.github.io/ssb-msg-schemas/) about the schema for post message and stumpled upon the following:

"It is used by message-mentions (to reference non-post messages)."

Why not message mentions? This way it could be used to model retweets. Retweeting (yeah bad name I know ;)) is a great way to find other users in a network and would really help the gossip design along I think.

**Comment by dominictarr** [comment]
one way you could do this is just to embed another message ![commentary on message](message link)
because then you could repost any message type.

**Comment by dominictarr** [comment]
and also embed it in other messages. your classic "retweet" would just be a post embedding another post without extra commentary.

**Comment by arj03** [comment]
But why not use mentions as the protocol already supports this? It would make it easier to query. If you want to comment on the link you can always use the text field for that. And embed it as you suggest if you want.
