### ISSUE TITLE
Should "Server has no public ip address" be a warning?

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#302]
If I want to host my pub as a tor hidden service I wouldn't need to have a public IP for that to work. So I think this requirement should be relaxed and just be a warning?

**Comment by pfraze** [comment]
Yeah probably. @dominictarr you have any thoughts about this?

**Comment by arj03** [comment]
This is only a problem when creating invites btw.

**Comment by fczuardi** [comment]
I am also curious about a way to generate an invite for a scuttlebot pub running as an onion service

**Comment by arj03** [comment]
@fczuardi something like this:

sbot server --allowPrivate --host 4fqstkswahy3n7mupr2gvvp2qcsp6juwzn3mnqvhkaixxepvxrrtfbid.onion

And you might need:

127.0.0.1 	4fqstkswahy3n7mupr2gvvp2qcsp6juwzn3mnqvhkaixxepvxrrtfbid.onion

in /etc/hosts

Then the normal invite create should work. The whole system is a bit in flux right now, some hopefully things should improve in the future.
