### ISSUE TITLE
Static-hosting feeds over HTTP

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#303]
Granted I'm very new to scuttlebot, but I was thinking of a way to announce your feed somewhere for your followers to download your feed when you are offline, as a transfer medium or as an alternative to pubs. So it would be static files only.

A feed appears to be just a list of messages, so this could be replicated as one zipped file. Using http you can check if the file has changed on the server without the need to download it again, similar to rss feeds. The blobs would need to be hosted as well, but that could simply be files located next to the rss feed with the filename as the id of the blob.

I'm wondering if this should be a new field or if it could be encoded in the existing format. I'm open for suggestions here. As I see it, it would be a list of urls similar to mirrors. And this could get updated as more are added or removed similar to how the name or image can change over time.

The signature and strict chain of messages makes sure that the hosting server can't tamper with the contents of the feed without making it obvious that they did, so we don't need to trust them in any way. 

So this suggestion is not an improvement on the public key -> nick mapping in that respect it is exactly the same as with pubs.

Thanks for reading, if there are consensus about this idea I'll be happy to provide patches :)

**Comment by pfraze** [comment]
@arj03 and I have been discussing this in IRC, so I updated the title to improve clarity.

@clehner, we discussed this last night on the call

The basic idea is, we could improve discovery by letting people host feeds on websites, and giving users a way to click a link --> follow the feed.

This does introduces a trust decision, since the server can choose to send you just about anything. Even if you put the pubkey in the link, the original link you're given could be wrong.

**Comment by arj03** [comment]
Expanding on the idea if we add it as a new field to the about message, then the protocol is backwards compatibel. The field would have the same requirements as name and image with only one, so it allows voting.

Furthermore the link is only a best effort. Meaning that if one changes location then one just adds a new about message with the new location to the stream of messages. The client can still try the old one but is it is the job of the client to determine the freshness/reliability of the link and act accordingly.

**Comment by arj03** [comment]
I have created the following repo to test the waters https://github.com/arj03/ssb-exporter. Let me know what you think of the idea and if I should continue and integrate the functionality into scuttlebot as a plugin.

**Comment by pfraze** [comment]
Yeah, that looks like a good start. Perhaps that could be built into scuttlebot as an `export` command, and an `import` could be added as well
