### ISSUE TITLE
Blob wanters not notified of blob add

### ISSUE THREAD

**Issue by clehner** [ssbc/scuttlebot#306]
I have a situation in [ssb-git-repo](https://github.com/clehner/ssb-git-repo) where I add() a blob and then want() it. In debugging I find that the blob does not finish being added until after want is called. Then the want does not complete and eventually times out. I think this is because when `notify(hash)` is called in [blobs.add](https://github.com/ssbc/scuttlebot/blob/master/plugins/blobs/index.js#L89), nothing happens, since [replication.js](https://github.com/ssbc/scuttlebot/blob/master/plugins/blobs/replication.js#L37) does not use the `notify` argument.

**Comment by dominictarr** [comment]
looks like you forgot to make a PR for this?

**Comment by clehner** [comment]
I haven't worked out a fix yet

**Comment by dominictarr** [comment]
ah, okay I'm hitting this rn

**Comment by pfraze** [comment]
:+1:

**Comment by dominictarr** [comment]
fixed in 7.6.1

**Comment by clehner** [comment]
Cool, the test I added passes. I get an assertion failure in the new code though:
```

$ node test/blobs
TAP version 13
# test blob api
# (anonymous)
ok 1 (unnamed assert)
ok 2 (unnamed assert)
ok 3 should be equal
ok 4 (unnamed assert)
# a client can request a blob
alice.address 192.168.0.150:64945:@/ffTIHeUFhecMjd7ObFWl17Br9KbQdsp0jRLRHC3R9A=.ed25519
ok 5 should be equal
# replicate blobs between 2 peers - explicit want request
added: &faVVVEr5KV+lr1nglcOZyP/dydiannMS+m+nN2VNzSs=.sha256
got: &faVVVEr5KV+lr1nglcOZyP/dydiannMS+m+nN2VNzSs=.sha256
not ok 6 (unnamed assert)
  ---
    operator: ok
    expected: true
    actual:   undefined
    at: finishJob (/usr/local/src/scuttlebot/plugins/blobs/replication.js:73:26)
  ...
ok 7 (unnamed assert)
TEST ENDED
# replicate published blobs between 2 peers
&faVVVEr5KV+lr1nglcOZyP/dydiannMS+m+nN2VNzSs=.sha256
ok 8 file replicated:&faVVVEr5KV+lr1nglcOZyP/dydiannMS+m+nN2VNzSs=.sha256
# blob add resolves blob want
ok 9 read file hash
ok 10 blob want
ok 11 blob add
ok 12 added the wanted blob

1..12
# tests 12
# pass  11
# fail  1

```

**Comment by dominictarr** [comment]
@clehner pull and run your the tests again, I saw that and fixed it.

**Comment by clehner** [comment]
I'm on 830495c2dbada845ce1fd66d3f186a502f3075a3. Did you push?

**Comment by clehner** [comment]
Got it
