### ISSUE TITLE
`sbot publish` not reading from stdin

### ISSUE THREAD

**Issue by clehner** [ssbc/scuttlebot#307]
Docs say:

```
cat ./message-content.json | publish
```

Observed behavior:

```
$ cat msg.json | sbot publish
UsageError: Param 0 is required
...
```

When passing in a type parameter, it seems the stdin is ignored:

```
$ echo '{"bar":true}' >bar.json
$ ssb_appname=ssb-test sbot publish --type foo <bar.json
{
  "key": "%Ep2AYzdzZl+/O9u4QV27GD7q5fSnDnR+xOt7dDBtoKA=.sha256",
  "value": {
    "previous": "%zvgFcKXenlB6nmvu1g0hwlPuugFVlXLa2mjsos92rxg=.sha256",
    "author": "@3HO6R2i60XNR3h6XCHAWCdt1k9Dwy+gaa2rVs6LzZ6Y=.ed25519",
    "sequence": 107,
    "timestamp": 1456637046513,
    "hash": "sha256",
    "content": {
      "type": "foo"
    },
    "signature": "Jvi3ZR2Bj3yHb7fdjXJYh70Scu0iihIYf/9TT8AvaPwqj+DwLwMzBcW6IUDHjZ3nx+Zo25neYP4RA+Vw7yo9Dw==.sig.ed25519"
  }
}
```

**Comment by dominictarr** [comment]
piping json to a command should parse and pass that argument to any command. was this introduced when switching to muxrpcli? cc @pfraze

**Comment by pfraze** [comment]
It mustve been. I'll check into it

**Comment by pfraze** [comment]
The docs are wrong. It should be:

```
cat ./message-content.json | publish .
```

Without the `.`, it doesn't know to use stdin. We either need to change that, or fix the docs.

In the second part, the message that's streamed in, is not currently merged with any flags. You're either using stdin or the cli flags. We can change that, as well, if we think we should.

**Comment by dominictarr** [comment]
should it be merged with flags?
I've also been wondering if it would be good to have a way to set config options via the command line.
one thing that might work would be to put more options after `--` minimist already supports this.
`sbot publish --type post --text hello -- --testnet` for example
