### ISSUE TITLE
Wifi Sync between friends SLOW :dog:

### ISSUE THREAD

**Issue by mixmix** [ssbc/scuttlebot#308]
case : 
1. josh and I **have been friends on patchwork for ages**
2. he hasn't used patchwork in a month and opens the app
3. we're at home on bad internet, it looks like he's trying to connect to pubs on the net
4. I spin up a phone hotspot and **turn off 3G**, we both join
5. we watch his `data-feed`, and my `activity` feed as messages/posts/votes appear in the view at a rate of about 1 every second. **[this seems really slow]**

**Comment by mixmix** [comment]
we'd both just pulled to v2.6.1 

I think (?) we also tried `npm update` and tried again and got the same thing

**Comment by dominictarr** [comment]
I'll fix this is the current sprint about perf

**Comment by mixmix** [comment]
Thanks. Have enough scuttlebots around to help test this easily when you
have a solution. Let me know.

I think scuttlebot should just get everything they can on wifi
exhaustively, (maybe just ignoring rate limits in this context) before
going elsewhere.
