### ISSUE TITLE
Connection timeout/failure

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#31]
Gossip was working great for a while (on my local machine, with one process seeded to reach the other). Then, it began logging the connect attempt, but then doing nothing. The Gossip plugin only attempts to make a new connection after the current one completes, and the current one does not seem to be making progress.

I haven't figured out why the connection started to fail. However, in this case, we either have a failure to establish the connection (which should result in a timeout) or there's some kind of error/exception (which should result in an error or close event). Presumably, neither is happening- or, if they are, the gossip plugin isn't listening for it.

What's the right way to handle timeout and connection errors on muxrpc?

**Comment by gwenbell** [comment]
Reading this thread to see if it can be closed. I'm not seeing this bug now. Are you, @pfrazee? I'll close and if you are still experiencing it, please reopen (best case, on git-ssb).
