### ISSUE TITLE
Heavy replication appears to lock the thread

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#311]
What Im seeing is, the patchwork HTTP server is not responding with the page-load quickly (Chrome's status: "Waiting for available socket"). It can be many seconds (like, >30). This appears to coincide with heavy replication -- eg, with a new user.

**Comment by dominictarr** [comment]
that is strange. can you advise how to reproduce this?

**Comment by pfraze** [comment]
Create a new user, have them follow enough people to get a lot of incoming data, and you should see the slowdown

**Comment by pfraze** [comment]
This may be fixed, by disabling quotas
