### ISSUE TITLE
Make it easy to run your own P2P scuttlebot network

### ISSUE THREAD

**Issue by bitalias** [ssbc/scuttlebot#332]
E.g. for testing purposes or inside a company.

**Comment by pfraze** [comment]
This would relate to running a Test-Net as well. Should be doable through the handshake-capability.

**Comment by arj03** [comment]
Does that mean that if I change the value in ssb-cap.js I'm sure that my messages will never be replicated to the official and only to the nodes running my secret key?

**Comment by pfraze** [comment]
It would mean your node could only make direct connections to nodes using
the same ssb-cap.js. The log messages could in theory make their way to
other nodes; for instance, if one of the nodes then changed its ssb-cap.js
to match another networks'.

**Comment by uiureo** [comment]
I'm creating an app for private networks (such as one inside a company) using scuttlebot.

Changing the handshake key isn't enough for my case.
Because, for example, when you connect to company **B**'s network after connecting to company **A**'s network, you don't like to share messages on company **A** with members of company **B**.

So I need a way to separate data safely. Do you have any idea on this case?

**Comment by dominictarr** [comment]
@uiureo yes. We just need to also use the app key in the signature -
the simplest would be to prepend the appkey to the message before signing,
then messages from the wrong network would appear invalid. This would also be worthwhile for creating a test network.

https://github.com/ssbc/ssb-keys/blob/master/index.js#L105-L116JB

**Comment by evbogue** [comment]
I think this issue is resolved. You can now pass a different `appkey` or `caps` into sbot and it seems to recognize it along the entire stack. http://github.com/evbogue/decent shows how to do this. 

Does this qualify as 'easy' though? Unsure.

**Comment by nichoth** [comment]
Is this what is meant by this issue? You can pass in the app key as an argument when you start sbot:

```
sbot server -- --caps.shs="abc"
```

This is the object syntax from minimist https://github.com/substack/minimist/blob/master/test/parse.js#L180

Then in ssb-client, pass in the same key

```js
Client(keys,{
    path: '/Users/me/.ssb',
    appKey: 'abc',
}, (err, sbot) => {})
```
