### ISSUE TITLE
Messages missing msg.value.content property

### ISSUE THREAD

**Issue by clehner** [ssbc/scuttlebot#335]
A couple times I got this crash:
```
TypeError: Cannot read property 'type' of undefined
    at /usr/local/src/scuttlebot/plugins/friends.js:50:10
    at /usr/local/src/scuttlebot/node_modules/pull-stream/sinks.js:37:37
    at /usr/local/src/secure-scuttlebutt/node_modules/pull-cat/index.js:40:13
    at drain (/usr/local/src/secure-scuttlebutt/node_modules/pull-pushable/index.js:11:22)
    at Array.read (/usr/local/src/secure-scuttlebutt/node_modules/pull-pushable/index.js:19:5)
    at next (/usr/local/src/secure-scuttlebutt/node_modules/pull-cat/index.js:27:19)
    at /usr/local/src/secure-scuttlebutt/node_modules/pull-cat/index.js:42:9
    at next (/usr/local/src/scuttlebot/node_modules/pull-stream/sinks.js:29:11)
    at /usr/local/src/scuttlebot/node_modules/pull-stream/sinks.js:42:15
    at /usr/local/src/secure-scuttlebutt/node_modules/pull-cat/index.js:40:13
```
I applied the following patch to try to see what the messages were that were getting processed:
```diff
diff --git a/plugins/friends.js b/plugins/friends.js
index 345b27c..0850365 100644
--- a/plugins/friends.js
+++ b/plugins/friends.js
@@ -47,7 +47,8 @@ exports.init = function (sbot, config) {
     }

     var c = msg.value.content
-    if (c.type == 'contact') {
+    if (!c) console.error("msg no content", msg)
+    if (c && c.type == 'contact') {
       mlib.asLinks(c.contact).forEach(function (link) {
         if ('following' in c) {
           if (c.following)
```
and got output such as the following:
```js
msg no content { key: '%UqCYaImE2NdHnxRlAwUgOibIx6sKMy6rYb0tSi9uRww=.sha256',
  value:
   { previous: '%kP3ZKwK1F8rB0vuxs6j9qRFPQpX+v2h+wpF3Wx2Tcl4=.sha256',
     author: '@8Qee0I/DwI5DHSCi3p5fsl6FyLGArrnDz3ox9qZr5Qc=.ed25519',
     sequence: 130,
     timestamp: 1459625139370,
     hash: 'sha256',
     content: undefined,
     signature: '3mTgU1mJLyMBUJ0gBYqejq7RPUA3MeCg5rpC2QGm6yJbiAfv8Tn6me3QafgqhE3MDkSdlE59HmYYd2Z4gyf+Cg==.sig.ed25519' },
  prefix: [],
  keyEncoding: undefined,
  valueEncoding: undefined,
  type: undefined,
  timestamp: 1459641729532.001 }
```
When I run `sbot get %UqCYaImE2NdHnxRlAwUgOibIx6sKMy6rYb0tSi9uRww=.sha256`, I get that the message does in fact have a content property, and it is a string of encrypted data. Is something hapenning to remove the content property, or should such encrypted messages not go through that code path?

I also am sometimes seeing the error/issue `TypeError: undefined is not an object (evaluating 'c.type')` appear in Patchwork, but I haven't got a stack trace for that yet.

**Comment by pfraze** [comment]
This definitely shouldnt be possible. Especially because `createLogStream` scans the log-order index for msg keys, and then pulls from the `key->value` index for messages. If `sbot get %UqCYaImE2NdHnxRlAwUgOibIx6sKMy6rYb0tSi9uRww=.sha256` has the content, then so should `createLogStream`

Is it possible there's anything weird with your node_module deps?

**Comment by clehner** [comment]
output of `npm-check-updates` in scuttlebot/ (after updating muxrpc-validation from 2.0.1 to 3.0.0):
```
 broadcast-stream   ~0.0.0  →  ~0.1.1
 ip                 ^0.3.3  →  ^1.1.2
 minimist           ~1.1.0  →  ~1.2.0
 nomnom              1.8.0  →   1.8.1
 non-private-ip     ~1.1.0  →  ~1.3.0
 pull-abortable     ~4.0.0  →  ~4.1.0
 pull-notify         0.0.0  →   0.0.2
 ssb-config         ~1.2.1  →  ~2.0.0
 ssb-msgs           ~5.0.0  →  ~5.2.0
 level-sublevel    ~6.3.15  →  ~6.5.4
 noderify           ~1.0.0  →  ~1.1.9
 ssb-msg-schemas    ~3.2.0  →  ~6.2.1
 tape               ~4.0.0  →  ~4.5.1

The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, use -a/--upgradeAll.

 multiblob     ^1.8.1  →  ^1.8.2
 muxrpc        ^6.1.1  →  ^6.2.2
 pull-stream   ^3.0.0  →  ^3.2.3
 secret-stack  ^2.3.0  →  ^2.5.0
```

**Comment by clehner** [comment]
I tracked down the TypeError in patchwork to [ui/com/msg-thread.jsx:141](https://github.com/ssbc/patchwork/blob/f9dd464ce7ad9569c124b2db885880442684c272/ui/com/msg-thread.jsx#L141): handling new messages. Not sure what to make of this yet.

**Comment by pfraze** [comment]
This is certifiably weird.

**Comment by dominictarr** [comment]
is this caused by messages that failed to decrypt?

**Comment by pfraze** [comment]
That's what it looks like, but that shouldnt be possible, bc there's no code there that tries to do the decrypt. The message shouldnt even be emitting there, much less with an `undefined` content

**Comment by dominictarr** [comment]
that is really weird. I did
`./bin.js log | grep %UqCYaImE2NdHnxRlAwUgOibIx6sKMy6rYb0tSi9uRww=.sha256 -C 10`
and I got the content. what node version are you on @clehner ?

**Comment by pfraze** [comment]
It's encrypted for me, but I get the string, not undefined

**Comment by dominictarr** [comment]
@clehner just a hunch, maybe you are getting it on live logs not old logs, because that has been through a decrypt

**Comment by dominictarr** [comment]
oh, for a live feed, it could be mutated by something else which is following the live feed, that listened first

**Comment by pfraze** [comment]
Ah that could be it

**Comment by clehner** [comment]
> oh, for a live feed, it could be mutated by something else which is following the live feed, that listened first

Sounds like that's it. I see a place where ssb-notifier would mutate an encrypted message. I will do some testing to try to positively identify that as the cause

**Comment by dominictarr** [comment]
we should freeze the objects in secure-scuttlebutt, and that will then throw and show us where the mutation is

**Comment by clehner** [comment]
It could be the lines setting `value.content` after unboxing a message:
- https://github.com/ssbc/patchwork/blob/f9dd464ce7ad9569c124b2db885880442684c272/api/processor.js#L386
- https://github.com/clehner/ssb-notifier/blob/e137e9137980ea08a82c5b8db4b9f859475973d6/notifications.js#L26

This reminds me: can a sync method like `private.unbox` be called async in sbot/plugin context? I would like to call it in a way that would work with either a sbot instance or with a ssb-client instance.

**Comment by dominictarr** [comment]
@clehner yes. I recall @pfraze recently added that, I don't remember exactly where that happens though. I think it was part of secret-stack though.

**Comment by dominictarr** [comment]
yup, here it is: https://github.com/ssbc/secret-stack/commit/e49cd17edd344c860df112bcfb384134363ad684

**Comment by clehner** [comment]
Ok, great. I've updated ssb-notifier to not modify messages and so far haven't seen these errors again. (Although I am still seeing ssbc/patchwork#360). also, this is with node v4.3.1

**Comment by pfraze** [comment]
Good to close?

**Comment by clehner** [comment]
Yes, I haven't seen this error since
