### ISSUE TITLE
gossip command options confict with config settings

### ISSUE THREAD

**Issue by clehner** [ssbc/scuttlebot#344]
gossip.add and gossip.connect take their arguments as either an address or a
host, port and key option:

```
$ sbot gossip.connect
UsageError: Param 0 is required
Add an address to the peer table, and connect immediately.

connect {addr}
connect --host {string} --port {number} --key {feedid}

-   `addr` (address string): An address string, of the following format: `hostname:port:feedid`.
-   `host` (host string): IP address or hostname.
-   `port` (port number)
-   `key` (feedid)
```

The way with host doesn't work. It appears that the host (and port?) overrides
the config host (and port) option that controls where the ssb-client connects
to:

```
$ sbot gossip.connect --host cel.hype --port 8008 --key @5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519
Error: Could not connect to the scuttlebot server.
Use the "server" command to start it.
```

Using the addr syntax works:

```
$ sbot gossip.connect cel.hype:8008:@5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519
{
  "domain": null,
  "_events": {
    "closed": [
      null,
      null,
      null
    ]
  },
  "_eventsCount": 2,
  "gossip": {},
  "friends": {},
  "replicate": {},
  "blobs": {},
  "invite": {},
  "block": {},
  "private": {},
  "plugins": {},
  "patchwork": {},
  "git-ssb-web": {},
  "notifier": {},
  "closed": false,
  "id": "@5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519"
}
```

I suggest removing the `--host ...` syntax since it conflicts with the config

**Comment by dominictarr** [comment]
oh right... hmm, I think this is because of how minimist is used by both rc (which manages config) and the cli. I think the solution would be to make the cli only set config options after a `--`
that way you could set configuration via cli also
` sbot add --type post --text 'hello' -- --host localhost --key ...`
etc
