### ISSUE TITLE
uploading too much data

### ISSUE THREAD

**Issue by NHQ** [ssbc/scuttlebot#351]
Per request an issue about bandwidth metering.  Solutions?  Go!

**Comment by dominictarr** [comment]
how much data is too much, for you? do you know how much scuttlebot has been sending?
is upload metered differently to download?

**Comment by NHQ** [comment]
Over about a week or so, I did 1gb down and 1/2gb up.  The upload was mostly sbot idling, afaict; I don't know what else it could have been; I was being conservative as possible, not visiting i.e. gmail or major news sites.

**Comment by dominictarr** [comment]
hmm, okay some ideas here:

* metering (so we know what actually happening)
* command to go offline (disable syncing)
* ensure that the longlived connection is actually working correctly... might need to get some people to upgrade...

Those are probably the best things we can do right now.
Also, I want to rewrite the replication protocol... but that's gonna be later i think.

assuming you are also using github/npm etc?
If I'm just coding entirely on 3g I'll probably do 5gb a month.

**Comment by NHQ** [comment]
Would having a preference for finding syncage thru pubs first do anything?
I notice I connect to lots of peers that don't follow me.

**Comment by dominictarr** [comment]
maybe, but that is what metering will tell us
