### ISSUE TITLE
Scuttlebot.io returns 502 Bad Gateway over HTTP

### ISSUE THREAD

**Issue by voxadam** [ssbc/scuttlebot#355]
When connecting to scuttlebot.io over unencrypted HTTP the nginx returns 502 Bad Gateway. Connecting over HTTPS works as expected.

**Comment by pfraze** [comment]
Thanks for the heads up. I'll need to fix this in the server config

**Comment by pfrazee** [comment]
@voxadam what browser were you using? I tried connecting to the following URLs and all of them correctly redirected me to https://scuttlebot.io:

http://scuttlebot.io
http://www.scuttlebot.io

**Comment by voxadam** [comment]
Firefox 47 and Chrome 52 on Linux.

**Comment by pfrazee** [comment]
Hmm. Seems weird that this could be a linux-specific bug, but I guess it's possible. Soon as I get a linux machine, I'll try to fix this

**Comment by ahdinosaur** [comment]
could not reproduce on my Linux machine with Firefox 38 and Chrome 52

**Comment by pfrazee** [comment]
Thanks Mikey. Adam do you have any ideas for how we could reproduce?

**Comment by voxadam** [comment]
I'm going to go ahead and close this. As it seems that I'm the only one person seeing this behavior I'm willing to bet that there's something wonky with my local network.

Sorry for the bad report.

**Comment by pfrazee** [comment]
@voxadam no worries, I appreciate your filing it. Strange bug

**Comment by voxadam** [comment]
So, while out at the pub I attemptedb to pull up scuttlebot.io and received the same 502 error as I'd encountered before. I wasn't connected using the same machine as before nor was I using my home network. At home I connect using Comcast and while mobile I connect using Verizon. 

Now that I think about it I wonder if the issue is isolated to IPv6 connections. I have dual-stack connectivity in both connections. I'm still mobile, and without a real keyboard, so I haven't been able to test my latest theory.

**Comment by pfrazee** [comment]
A lead! I'll check the IPv6 settings

**Comment by clehner** [comment]
Confirmed:

$ curl -6 http://scuttlebot.io/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

$ curl -6 https://scuttlebot.io/
curl: (7) Failed to connect to scuttlebot.io port 443: Connection refused

**Comment by pfrazee** [comment]
I configured scuttlebot.io's nginx to accept ipv6 connections and restarted
it. However, I have been completely unable to connect to scuttlebot.io via
IPv6, from my machine or from my other cloud machines. (I get 'No route to
host'.)

What are yall getting now?

**Comment by clehner** [comment]
> What are yall getting now?

Works for me now

**Comment by voxadam** [comment]
Works for me! Thanks for the fix.
