### ISSUE TITLE
local broadcast: should be able to specify UDP port

### ISSUE THREAD

**Issue by mmckegg** [ssbc/scuttlebot#358]
At the moment the [**local**](https://github.com/ssbc/scuttlebot/blob/master/plugins/local.js) plugin just uses the port specified in the config file. This works for most cases, but in my app (mostly for local testing purposes), I am assigning a random port on startup. This means the local peers cannot find each other

@dominictarr What do you think about making the broadcast port configurable separate from sbot? Or is there a better way to do this?

**Comment by ahdinosaur** [comment]
i think i'm missing something, but in case it's helpful you can [pass config options as arguments beyond `--`](https://github.com/ssbc/scuttlebot/blob/master/bin.js#L16-L21) or anything supported by [`rc`](https://github.com/dominictarr/rc) where `appname` is `"ssb"`.

**Comment by mmckegg** [comment]
@ahdinosaur The config option is shared with the scuttbot port though. If you change scuttlebot to use port `12345`, the broadcast will also be on port `12345`. I want to be able to configure the broadcast to be on a different port from scuttlebot. Like I said though, this really is only a problem when trying to test multiple peers locally. In the wild, you can use a fixed port since only one instance can use a scuttlebutt database at a time.

There should be a separate config option `broadcastPort` or something. It should fall back to `port` if `broadcastPort` is not specified.

**Comment by mmckegg** [comment]
Actually just trying this out. Only one app can bind to the local broadcast port at a time, so this won't even help solve that problem.

Will try and come up with something else. Closing.

**Comment by dominictarr** [comment]
The tcp port can be randomized, but the UDP port needs to be static, because to receive the messages you are transmitting, I need to listen on the port you are. I don't know how to test it with just one computer, because two processes can't bind to the same port. );
