### ISSUE TITLE
Heroku for Pub Install?

### ISSUE THREAD

**Issue by jasonwhat** [ssbc/scuttlebot#364]
Has anybody setup a Pub on Heroku. It seems like a good free option. I'm one of those people who would like to get involved, but lack the technical skills. I can follow most step-by-step instructions, but even the guide is a overwhelming for me.

I'd love to try on Heroku. Even better would be having a one-click install on Heroku.

**Comment by evbogue** [comment]
hey @jasonwhat. Let me know if you need help any help getting an sbot pub up and running. Have you made it onto the sbot network yet?

No one has used Heroku. Most people are using straight up VPSes.

**Comment by DanielHeath** [comment]
I agree that a heroku-button or similar would help grow the network, but the work required would be reasonably significant (eg moving all config into a buildpack / database)

**Comment by staltz** [comment]
I'm not even sure if we can use Heroku, because sbot needs to talk with other peers using TCP sockets, but Heroku only allows HTTP.

**Comment by DanielHeath** [comment]
Ahh, that would prevent it acting as a pub, yeah
