### ISSUE TITLE
[flume] gossip plugin doesn't use `config.connections`

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#372]
i was missing some messages from people i follow, and am on good wifi, so wanted to increase the number of active connections.

as documented [here](https://scuttlebot.io/docs/config/configure-scuttlebot.html), you can configure the gossip plugin to change how many simultaneous connections to have active.

i tried this, but it doesn't work. here's a note to myself if i feel like fixing it, the code is [what's passed in as `quota` in `plugins/gossip/schedule.js](https://github.com/ssbc/scuttlebot/blob/flume/plugins/gossip/schedule.js).

**Comment by clehner** [comment]
i think gossip.dunbar could also affect this. however, i couldn't find if it is used in the flume branch either

also looks like

**Comment by dominictarr** [comment]
my hunch is that this is really in that the tcp connection stays open, but somehow the shs connection breaks or something like that without sbot realizing. or the tcp connection fails, but again, sbot thinks is still active, so doesn't reactivate the schedule
