### ISSUE TITLE
wiki pub servers registry addition

### ISSUE THREAD

**Issue by jekrb** [ssbc/scuttlebot#377]
if this becomes inactive people can ping me via email jake@doge.haus 

`pub.doge.haus:8008:@7nTbqZVRYRo7FokY8BBYGpXvvveRPb4u+G1vunRmNn4=.ed25519~r9/izCRmOyMVuKPynuyab/AOwXNX0ZDqQQFBO1M4MEo=`

**Comment by clehner** [comment]
@jekrb cool. want to add it to https://github.com/ssbc/scuttlebot/wiki/Pub-Servers ?

**Comment by jekrb** [comment]
@clehner Yes, please!

I saw this on the wiki:

> You can add a pub by opening an issue on the repo.

And wanted to add my pub to it :)

**Comment by clehner** [comment]
oh, i didn't realize editing the wiki required permissions. i've added pub.doge.haus now. cheers!
