### ISSUE TITLE
proposal: rename `scuttlebot` repo / pkg to `ssb-server`

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#378]
see discussion on ssb [here](https://viewer.scuttlebot.io/%25BIn4rQl8o7PxeolhiZCw77fUN5gGpOv6I3gDXhMfP%2BM%3D.sha256).

also if we do this, maybe we should split out bin script to `ssb-cli`.

**Comment by staltz** [comment]
👍 for the renaming and for `ssb-cli`.

**Comment by christianbundy** [comment]
I'd like to make this change. Do we know what the blockers are on this, if any?

**Comment by christianbundy** [comment]
I think our steps on this would be:

- Rename GitHub repo
- Remove internal name references:
  - [scuttlebot](https://github.com/ssbc/scuttlebot/search?q=scuttlebot&unscoped_q=scuttlebot)
  - [sbot](https://github.com/ssbc/scuttlebot/search?utf8=%E2%9C%93&q=sbot&type=)
- `npm publish` as ssb-server
- [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) as scuttlebot

Any others I'm missing?

**Comment by christianbundy** [comment]
I think my above message may be missing the changes for `scuttlebot-release`. My *personal* preference would be to drop that repo and just use a lockfile in this repo, but I may be alone in that preference. What do you all think?

**Comment by staltz** [comment]
Christian I'm with you on that. I don't see the point of scuttlebot-release

**Comment by christianbundy** [comment]
@staltz I've started a discussion on SSB here, if you're interested:

```
%RZW7keS4V1Fv4AvUaVvdo7A4hgtLZOdoKDWXByALdE8=.sha256
```

**Comment by x11x** [comment]
Hey sorry to post on a closed issue, but the Docs -> Basics section on https://scuttlebot.io/docs/basics/install-the-database.html still recommends `npm install -g scuttlebot`. Seems like this still needs updating? (I assume ssbc organization runs that website?) Having found this issue and #456 I now understand, but it took me a bit of digging. I wonder whether a snippet in the readme of this repo explaining "formerly scuttlebot, sometimes still referred to as such ..." would be possible too, so new users don't have to dig through old issues to work out which component is which.
Thanks
