### ISSUE TITLE
mysterious "server error: wrong number"

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#380]
there have been some reports of a strange error occuring now and then.
https://github.com/ssbc/scuttlebot/pull/379#issuecomment-288968320

I think the error comes from here ([original post](https://github.com/ssbc/scuttlebot/pull/379#issuecomment-288847524)):
> you should only see "wrong number" when answering the call (as the server) https://github.com/auditdrivencrypto/secret-handshake/blob/master/protocol.js#L92
> pretty sure that error is getting dumped out here: https://github.com/dominictarr/multiserver/blob/master/compose.js#L65

Some claim that they see it sometimes even when there isn't something replicating on the network with them.

If anyone sees the error @ahdinosaur @staltz can they report it here and we'll try to get to the bottom of this. If you can post the error, and also describe the network, situation etc. I would expect this to happen when another device using ssb is running on the same network, so try to disprove this if you can.

**Comment by staltz** [comment]
I ran vanilla `sbot server` and saw only logs of `Connected pub.address:pubkey`, no errors. I'll keep an eye out when/if I see the error.

**Comment by clehner** [comment]
i would imagine this could happen on a LAN if an address is re-used by the DHCP server for a different host. then sbots with the old address in their peer table might connect to the address with the wrong key (the key that previously was associated with that address)

**Comment by dominictarr** [comment]
@staltz @ahdinosaur @mixmix if you reinstall scuttlebot, you should get multiserver@1.8.1 which will include the remote address on the server error message. This should help trackdown the source of the incoming connection attempt.

I guess another possible explaination, is that you are connecting back to your self some how (we'll see a 127.0.0.1 address on the error) possibly a side effect of changing networks (and thus ip-addresses) or something like that.

**Comment by mmckegg** [comment]
Actually me and @ahdinosaur did see a few mysterious connections to 127.0.0.1 and wondered what that was about. 

Is it possible someone has broadcasted that as a pub address? `type: "pub"`

**Comment by mixmix** [comment]
Yes i think so.. Andre mentioned publishing some messages that might have
been those... Not sure if it was pub messages though

**Comment by mmckegg** [comment]
Found this:

```
{
  "key": "%0s/CPf/EDMQumcO4sGBTyM0H2XHOF32IoidK1wM8vdI=.sha256",
  "ts": 1487337083863,
  "value": {
    "previous": "%qzP3rDSG4Rgcoqtt9iriaqWGTmyBExCfkdYCjWjHGDg=.sha256",
    "author": "@srxxGe5cEmZOWriuS9jaUbhIPFbTTfIP0Kf8t6GbrIE=.ed25519",
    "sequence": 2,
    "timestamp": 1487337033171,
    "hash": "sha256",
    "content": {
      "type": "pub",
      "address": {
        "host": "localhost",
        "port": 8080,
        "key": "@G20wv2IZkB7BA/LKe7WMuByop3++J0u9+Y32OoEVOj8=.ed25519"
      }
    },
    "signature": "+rBaWyS04Shfr7O1eLBgEGBpQ9IKjToiUhGPyckV/EnU5KVJ/XlB4FGuBcPNO1mreQMyZZMgc1bUoOO+e4msBg==.sig.ed25519"
  }
}
```

**Comment by dominictarr** [comment]
Yup. There are definitely some spurious invalid pub announcements, the gossip plugin ought to ignore pub announcements for localhost, certainly. for private network address (192.168..., fc00...) gets difficult because ignoring those would mean you can't have a pub on cjdns, etc

**Comment by staltz** [comment]
Found a (hopefully reproducible) case:

I had sbot running in a phone *simulator* on my computer, and so it shared the same LAN IP as the computer. The phone sbot was running on port 8008, so I decided to run an sbot on my computer using a different port and a different path. Upon running, it would create its key from scratch, so this is a new peer.

Then, when I ran `sbot whoami --port=4000` (I wasn't sure if this command supported --port but I tried it anyway) from another terminal, it answered `"Error: Could not connect to the scuttlebot server. Use the "server" command to start it."` and from the sbot server terminal:

```
sbot server --path=/Users/staltz/oss/easy-ssb-pub/lepoop --port=4000
Loading plugins from /Users/staltz/oss/easy-ssb-pub/lepoop/node_modules
Log level: notice
server error Error: wrong number
    at abort (/Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:80:45)
    at Object.cb (/Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:92:20)
    at drain (/Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:35:23)
    at more (/Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:51:13)
    at /Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:62:9
    at /Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/Users/staltz/.nvm/versions/node/v6.10.1/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

Computer sbot was running scuttlebot@9.4.6.

Maybe the question here is can we run multiple peers on the same machine under different ports?

**Comment by dominictarr** [comment]
@staltz nearly! to pass a configuration option to a sbot command (_except for `server`_) you need to separate by `--`, `sbot whoami --port ...` passes `{port: ...}` to `whoami` the correct is `sbot whoami -- --port ...` instead

**Comment by mmckegg** [comment]
```
server error, from net:::ffff:127.0.0.1:54060~shs:
Error: wrong number
    at abort (/Users/matt/Code/patchwork/node_modules/secret-handshake/protocol.js:80:45)
    at Object.cb (/Users/matt/Code/patchwork/node_modules/secret-handshake/protocol.js:93:20)
    at drain (/Users/matt/Code/patchwork/node_modules/pull-reader/index.js:35:23)
    at more (/Users/matt/Code/patchwork/node_modules/pull-reader/index.js:51:13)
    at /Users/matt/Code/patchwork/node_modules/pull-reader/index.js:62:9
    at /Users/matt/Code/patchwork/node_modules/pull-reader/index.js:20:7
    at drain (/Users/matt/Code/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/Users/matt/Code/patchwork/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

Red handed!

**Comment by dominictarr** [comment]
you where trying to connect with yourself!

**Comment by dominictarr** [comment]
okay, new theory on this, given that I see this error when I'm at tangleball, where @robinpaulson also hangs out. I saw this error: `server error, from net:::ffff:127.0.0.1:45618~shs:` and thought, maybe the local broadcasts say localhost? I checked `gossip.peers` and saw a peer with robin's pub key, but 127.0.0.1 for the address. My theory: the address is not broadcasting the right host, or maybe the local plugin should just take the host from the broadcast packet. Either way, it's thinking it's localhost when it should be the actual ip address

**Comment by optikfluffel** [comment]
I set up [ahdinosaur/ssb-pub](https://github.com/ahdinosaur/ssb-pub) on a little VPS at Scaleway and really get a lot of these messages. This are only a couple of minutes after starting: [Log Output](https://paste.fluffel.io/?5327a7f1c683eb98#EBJrvNddUPQYdbP5dKn6QDexuDV2jLiqi3h57xHeD4k=).

**Comment by cryptix** [comment]
Mmmh.. I also tried ssb-pub and see lots of `Error: wrong number`s.
A lot of cpu power is wasted on creating lots of ephemeral keys.. :-/
