### ISSUE TITLE
Can't find any running Pub Servers

### ISSUE THREAD

**Issue by zeke** [ssbc/scuttlebot#382]
👋  scuttlebot ignoramus here, just trying to see what it's about.

None of the "active" pubs on this list are useable for me: https://github.com/ssbc/scuttlebot/wiki/Pub-Servers

Should I be able to request invites to these pubs using my web browser, or should I be using some kind of client to access the pubs?

cc @pfrazee @dominictarr

**Comment by dominictarr** [comment]
sorry, yeah that is out of date. we do have pubs with web interface invites now, one is here: http://ssb.rootsystems.nz/

**Comment by dominictarr** [comment]
ah, that was actually already on the wiki page. I've reorganized the page a bit to make this more obvious, @zeke does it make sense now? https://github.com/ssbc/scuttlebot/wiki/Pub-Servers

**Comment by zeke** [comment]
Progress! Thanks for the clarification, @dominictarr.

![screen shot 2017-03-29 at 9 26 07 pm](https://cloud.githubusercontent.com/assets/2289/24487714/5b52195c-14c6-11e7-8905-863f083a599e.png)
