### ISSUE TITLE
New Pub Server

### ISSUE THREAD

**Issue by BrianOtto** [ssbc/scuttlebot#387]
I have setup a new **easy-ssb-pub** server that gives out invites at http://ssb.exitsystemcall.com

Feel free to add it your list of [Pub Servers](https://github.com/ssbc/scuttlebot/wiki/Pub-Servers). It will be up 24/7.

**Comment by clehner** [comment]
Added. Thanks!

**Comment by glennbb** [comment]
Just tried your pub server and it works great, thanks. 

One issue to note though: when it gives out invitations they contain the URL ssb.mydomain.com.

**Comment by BrianOtto** [comment]
@glennbb I had to restart the server recently, and it looks like I used the wrong domain.

Thanks for letting me know! This has been fixed now.

**Comment by greenpeteuk** [comment]
http://ssb.exitsystemcall.com doesn't work for me :-(

**Comment by flyingoctopus** [comment]
Server response 503 when trying to visit http://ssb.exitsystemcall.com

**Comment by BrianOtto** [comment]
Sorry, go ahead and remove the server from the list. I have had to shutdown the pub and re-purpose the server for another project.

**Comment by greenpeteuk** [comment]
As a new person to SB this isn't inspiring. That a server can just be taken off line because of another 'project' and seemingly without even bothering to tell anyone. Sad.

**Comment by staltz** [comment]
When a pub goes down no data is lost

**Comment by greenpeteuk** [comment]
@staltz "When a pub goes down no data is lost" - I realise this, but that is not my point.
As a new user of SB, I am looking for people to connect with. So far I have have had a few problems and managed to connect with not one person yet.
A Pub not being available adds to the feeling that the network (yes, I know there can be many and private and not all connected) isn't viewed as being worth the time and effort to support (from an admin's point of view).
Therefore new users, such as my self may well just turn away, which doesn't help get the project going.

**Comment by staltz** [comment]
@greenpeteuk Who do you want to be connected with? This is a network-of-friends, or at least trust-based connections, so if you want to get in connection with people, just reach out to people who are using SSB and ask an invite to those specific people. For instance there are some people on Twitter who can be contacted (I myself as well), some people on IRC (freenode), and some familiar folks you can find among GitHub issues such as this one itself.

**Comment by greenpeteuk** [comment]
@staltz I was thinking simply of like minded people. That's what I thought the 'pubs' are for? When I join one, I see plenty of people but all they have done is subscribed to a pub, with very few (I have found 2 so far) that actually post anything, so you have no idea what they are interested in.
I realise that if I wanted to get some afk friends on 'a' decentralised network, I could use SB.
Then it just struck me that a pub, going down without notice and 'for another project' which sounds like a lack of interest in SB, is not ideal.
Maybe I have the wrong end this here stick!?

**Comment by staltz** [comment]
I think a better analogy for a "pub" is "internet-accessible mirror for several accounts" where "several accounts" depends on who got connected to that mirror server. *Who* gets connected to that pub means who the pub owner sent invitations and depends on how far the friends-of-friends scope of the mirroring goes (this is configurable, most configure hops=2 which means friends-of-friends but not friends-of-friends-of-friends).
