### ISSUE TITLE
syntax error when starting server

### ISSUE THREAD

**Issue by masukomi** [ssbc/scuttlebot#388]
on macOS Sierra after running 
```
npm install scuttlebot@latest -g

npm ls secure-scuttlebutt -g
```
I try to run `sbot server` and get the following error.
```
$ sbot server
/usr/local/lib/node_modules/scuttlebot/sbot.js:7700
        rate, // rate of messages written to sbot
            ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by mmckegg** [comment]
Looks like you're using an old version of node that doesn't support ES6. Try running `node -v`.

We're mostly using the [LTS version v6](https://nodejs.org/en/download/). But I think v4 works as well.

**Comment by mmckegg** [comment]
@dominictarr would this be a good enough reason to ditch that one sneaky ES6 instance? Are there any other reasons it wouldn't run `< v4`.

**Comment by dominictarr** [comment]
hmm, hang on what version of node is this? I suspect that if @masukomi is running a really old node version there will be other problems with native modules, in particular.
