### ISSUE TITLE
Pub crash checklist and bandaids

### ISSUE THREAD

**Issue by ezdiy** [ssbc/scuttlebot#389]
Currently, one needs to run a Pub in a while true loop, because busy server crashes every few hours or so. 

The crashes are especially frustrating when a newly coming user accepts an invite and their connection triggers a crash - over and over. Moreover, frequent crashes seem to make feed updates stuck when it comes during a feed queue transfer (this seems to be fixed in new patchwork).

The patches here are against spots in modules used by sbot, not sbot by itself. This is probably wildly incorrect, as sbot should be the one trying to catch the exception. I didn't try to investigate the actual flow to accomplish that, just attempted to make a safe exit from bad situations (ie disconnect the client, or error mark the stream).

If you encounter other crashes, please share here (preferably with a bandaid).

```
diff -ruN .nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/crypto.js node_modules/scuttlebot/node_modules/secret-handshake/crypto.js
--- .nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/crypto.js       2017-03-27 23:21:30.000000000 +0200
+++ node_modules/scuttlebot/node_modules/secret-handshake/crypto.js     2017-04-09 08:00:17.000000000 +0200
@@ -29,7 +29,9 @@

 function assert_length(buf, name, length) {
   if(buf.length !== length)
-    throw new Error('expected '+name+' to have length' + length + ', but was:'+buf.length)
+    return 0;
+  return 1;
+  //  throw new Error('expected '+name+' to have length' + length + ', but was:'+buf.length)
 }

 exports.initialize = function (state) {
@@ -65,7 +67,8 @@


 exports.verifyChallenge = function (state, challenge) {
-  assert_length(challenge, 'challenge', exports.challenge_length)
+  if (!assert_length(challenge, 'challenge', exports.challenge_length))
+    return null

   var mac = challenge.slice(0, 32)
   var remote_pk = challenge.slice(32, exports.challenge_length)
@@ -133,7 +136,8 @@
 }

 exports.clientVerifyAccept = function (state, boxed_okay) {
-  assert_length(boxed_okay, 'server_auth', exports.server_auth_length)
+  if (!assert_length(boxed_okay, 'server_auth', exports.server_auth_length))
+     return null

   var b_alice = shared(curvify_sk(state.local.secretKey), state.remote.kx_pk)
   state.b_alice = b_alice
@@ -150,7 +154,8 @@
 //server side only (Bob)

 exports.serverVerifyAuth = function (state, data) {
-  assert_length(data, 'client_auth', exports.client_auth_length)
+  if (!assert_length(data, 'client_auth', exports.client_auth_length))
+    return null

   var a_bob = shared(curvify_sk(state.local.secretKey), state.remote.kx_pk)
   state.a_bob = a_bob
```

```
diff -ruN .nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/pull-next/index.js node_modules/scuttlebot/node_modules/pull-next/index.js
--- .nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/pull-next/index.js       2016-10-23 10:46:02.000000000 +0200
+++ node_modules/scuttlebot/node_modules/pull-next/index.js     2017-04-09 22:57:05.213475348 +0200
@@ -14,6 +14,8 @@
         catch(err) { return cb(err) }
         if(!stream) return cb(true)
       }
+      if (typeof stream !== "function")
+       return cb(true);
       stream(null, function (err, data) {
         if(err) {
           stream = null
```

**Comment by dominictarr** [comment]
a well designed p2p protocol should function with unreliable nodes or hardware or network, and mostly this does work which is why we just use the loop. but if a client action causes a crash every time, we definitely need to fix this. The first thing one should be fixed if you have `secret-handshake@1.1.5`, I'm gonna update the various modules to make sure everything is using the latest here...

**Comment by dominictarr** [comment]
okay i figured it out, 1.1.5 hadn't actually been published. I probably had spotty internet at the time or something

**Comment by dominictarr** [comment]
okay if you just `rm -rf node_modules` and npm install these should be fixed. just check you have secret-handshake@1.1.5 using `npm ls secret-handshake`

**Comment by ezdiy** [comment]
@dominictarr Ah, should've checked that repo first, figures. Indeed the crashes with incorrect crypto lens were happening on 1.1.4.

I'll try to add some sentinel code around 'stream' in a bid to track down where it comes from, or at least figure out whatever is in it, if not a function or null in the meantime.

**Comment by dominictarr** [comment]
that other one was the fix in pull-next@1 which you should get

**Comment by ahdinosaur** [comment]
tangential but related to keeping pubs up:

[%geKebzGVGoYkxrROE3AVzKcuwIgA0uGy1CtieNgGfpA=.sha256](http://viewer.scuttlebot.io/%25geKebzGVGoYkxrROE3AVzKcuwIgA0uGy1CtieNgGfpA%3d.sha256)

**Comment by ezdiy** [comment]
@ahdinosaur Plenty of memory here :)

@dominictarr Pulled, thanks for prompt fix. Will see if stays up now.

**Comment by ezdiy** [comment]
Ok, so now pub does not crash, but It gets stuck in infinite loop somewhere (and stops being responsive). ctrl+c doesn't yield a stack track, any ideas how to get one?

I'm using node v7.8.0 which is different from recommended from the how to, I suppose that's not the cause?

**Comment by dominictarr** [comment]
@ezdiy oh damn, that is worse. i'm also using 7.8.0, can you describe how to reproduce? does `./bin.js whoami` work? (say, run from another shell on the same machine)

**Comment by ezdiy** [comment]
@dominictarr No, it's completely dead, not just lagged. RPC is what I'm using for detect & kill (ie the rpc is dead too). I'll try to get it into devtools next time round.

One thing is for certain: there seems to be *something* out there triggering the infinite loop, as they often go in quick succession, then whatever is causing it probably gives up. It seems it's none of the clients listed, more like pre-rpc connect (or somewhere in the middle), or a blob.

```
Connected @t17q9M1AdS9sdj+K4pFD5APJK3f0hpfnMB7+m2JDNC0=.ed25519
Connected @dBQlwh9Gtr3i5YMOGtIOKtGNVepeu+nyb6KGl1vtOcM=.ed25519
Connected @6oThOSDUjORjZb9KoARAMfDWAVXhXNjsC3DTgVqpJto=.ed25519
Connected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Connected pub.jnh.li:8008:@HtUm8F5Wl1uBnd+zSRYsxaDftD+xULZ7gazQfkLg20s=.ed25519
Terminated
Loading plugins from /home/ezdiy/.ssb/node_modules
Log level: notice
Connected 104.236.242.204:8008:@uP7sDZW9ETaOhNMFIYaEcGVwtFijX8/OnRtsHCKZYS8=.ed25519
Connected pub.jnh.li:8008:@HtUm8F5Wl1uBnd+zSRYsxaDftD+xULZ7gazQfkLg20s=.ed25519
Connected @dBQlwh9Gtr3i5YMOGtIOKtGNVepeu+nyb6KGl1vtOcM=.ed25519
Connected @LVgvT3/A17IJ4d9SAwLz12WVDWAFpVEe6UAA+SvJAXY=.ed25519
Connected @t17q9M1AdS9sdj+K4pFD5APJK3f0hpfnMB7+m2JDNC0=.ed25519
Disconnected pub.jnh.li:8008:@HtUm8F5Wl1uBnd+zSRYsxaDftD+xULZ7gazQfkLg20s=.ed25519
Connected @6oThOSDUjORjZb9KoARAMfDWAVXhXNjsC3DTgVqpJto=.ed25519
Connected @yKb1Pbs9rwSx8dCLfDIPO/xYNvgoT6xTORbLq0Jquo0=.ed25519
Connected @A14NZKIX2XSVh3DeGMoFyoWFg9rxNNRMGMsqz+sKdRY=.ed25519
Connected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Connected pub.jnh.li:8008:@HtUm8F5Wl1uBnd+zSRYsxaDftD+xULZ7gazQfkLg20s=.ed25519
Disconnected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Connected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Terminated
Loading plugins from /home/ezdiy/.ssb/node_modules
Log level: notice
Connected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Connected 104.236.242.204:8008:@uP7sDZW9ETaOhNMFIYaEcGVwtFijX8/OnRtsHCKZYS8=.ed25519
Connected @LVgvT3/A17IJ4d9SAwLz12WVDWAFpVEe6UAA+SvJAXY=.ed25519
Connected @t17q9M1AdS9sdj+K4pFD5APJK3f0hpfnMB7+m2JDNC0=.ed25519
Connected @dBQlwh9Gtr3i5YMOGtIOKtGNVepeu+nyb6KGl1vtOcM=.ed25519
Disconnected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Connected @6oThOSDUjORjZb9KoARAMfDWAVXhXNjsC3DTgVqpJto=.ed25519
Connected 209.177.93.42:8008:@CQSMJsDjpn5t59MXqMp1q3JJ3+19K9Jn0Z3LQfZkVBI=.ed25519
Connected pub.afofo.com:8008:@y4jMEp81JmsGzJUh3WzjxME0J0tWfSx0b/tMH9dvVuo=.ed25519
Terminated
Loading plugins from /home/ezdiy/.ssb/node_modules
Log level: notice
....
```

On unrelated note, another bandaid (it was getting stuck even before this was hacked, so its not the cause):


```
@multiblob/index.js:177

      stat(toPath(dir, hash), function (err, stat) {
        if (!stat)
          stream.abort(new Error('blob missing'))
        else if(opts.size != null && opts.size !== stat.size)
```

(really should check for err, but no idea whats supposed to be here, js noob :)

**Comment by ezdiy** [comment]
Ok, got it stuck just now:

```
[pid  7896] futex(0x3506740, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  7896] mmap(0x2d56a1900000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x2d56a1900000
[pid  7896] mmap(0x249e52c80000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x249e52c80000
[pid  7896] futex(0x3506720, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  7893] mmap(0x25bdea880000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x25bdea880000
[pid  7893] mmap(0x12790200000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x12790200000
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946351, 885270000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946351, 903158000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946351, 903245000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x3506720, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  7898] <... futex resumed> )       = 0
[pid  7898] mmap(0x14f0f4500000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x14f0f4500000
[pid  7898] mmap(0x347b87e00000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x347b87e00000
[pid  7898] futex(0x3506720, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  7893] mmap(0x321cdd580000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x321cdd580000
[pid  7893] mmap(0x323a23200000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x323a23200000
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 89163000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 106559000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 106642000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x3506720, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  7895] <... futex resumed> )       = 0
[pid  7895] futex(0x3506740, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid  7893] futex(0x3506740, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  7895] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  7893] <... futex resumed> )       = 0
[pid  7895] futex(0x3506740, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  7895] mmap(0x25bdea880000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x25bdea880000
[pid  7895] mmap(0x12790200000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x12790200000
[pid  7895] futex(0x3506720, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  7893] mmap(0x1976c5e00000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1976c5e00000
[pid  7893] mmap(0x2eb7bd000000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2eb7bd000000
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 170085000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 187980000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 188073000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid  7893] futex(0x3506720, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  7897] <... futex resumed> )       = 0
[pid  7897] mmap(0x321cdd580000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x321cdd580000
[pid  7897] mmap(0x323a23200000, 524288, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x323a23200000
[pid  7897] futex(0x3506720, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  7893] mmap(0xb846e000000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb846e000000
[pid  7893] mmap(0x324794100000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x324794100000
[pid  7893] futex(0x354fff0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {1491946352, 347254000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
(not much else there, only futex and mmap)
```

Worse still, no SIGUSR1 debugger. This might be a deadlock inside leveldb live feed or something.

**Comment by dominictarr** [comment]
@ezdiy that multiblob error is ignorable. if the file doesn't exist there is no stat, so you'd do the same thing to handle that error.

I'm seeing cpu churn on my server too. can you give me your kill script? unfortunatly I've gotta do some work work today );

**Comment by ezdiy** [comment]
``` while true; do if ! ./bin.js whoami && (sleep 30) && ! ./bin.js whoami; then kill -TERM $(pgrep -f bin.js); fi; sleep 60; done```

(im running ./bin.js, you may need to change that to 'sbot')

**Comment by dominictarr** [comment]
awesome, I will run the same script.

**Comment by ahdinosaur** [comment]
i think we're getting this on ssb.rootsystems.nz now. randomly will start using 100% CPU and become unresponsive. but restart and it's okay, until it happens again. hmm.. :thinking:

**Comment by ezdiy** [comment]
A word of caution: if your server is not particularly fast (ie running on potato vps instances), you may need to increase number of tests In the whoami script, and delays between them, otherwise it will keep killing it over and over for indexing refs of some new feed into leveldb. For example:

`while true; do if ! ./bin.js whoami && sleep 120 && ! ./bin.js whoami && sleep 300 && ! ./bin.js whoami && sleep 600 && ! ./bin.js whoami;  then kill -TERM $(pgrep -f bin.js); fi; sleep 300; done`

What it means: if the RPC becomes dead, it checks another 3 more times with increasing steps of 2, 5 a and 10 minutes, and only then the kill command is issued.

@ahdinosaur It could be that frequent crashes (majority of which are now fixed) simply masked the hang problem and it never went to that point. Less likely some new code introduced this.

In any cases, there are old threads on sbb about "dreaded hang", could that possible be this?

**Comment by ahdinosaur** [comment]
i just had a thought: the "problem" at the moment is pubs become frequently unresponsive, presumably by doing something expensive in a tight loop, which restricts all the CPU resources from handling other concurrent calls. could we fix this just by using `setImmediate` in these loops? i wonder what would happen if we implemented this in [`looper`](https://github.com/dominictarr/looper), which hopefully is how most loops are implemented. what do you think @dominictarr?

**Comment by ahdinosaur** [comment]
this also isn't limited to just pubs. when on-boarding @booleanvalue last night, my computer was replicating to his over the local network, so then my Patchwork became unresponsive as the replication was hogging the cycles. i wonder if there's a good balance between speed (sync `while` loops) and concurrency (`setImmediate`), like every 10 loops do a `setImmediate` (although seems like a configuration option since dependent on algorithm).
