### ISSUE TITLE
Error when using --port and creating invites > 1

### ISSUE THREAD

**Issue by cblgh** [ssbc/scuttlebot#390]
I'm running sbot with the following options:
`sbot --host <my host> --port <my port>`

to connect to that sbot instance i then have to supply the `<my port>` like
`sbot invite.create --port <my port>`

however if i create more than one invite i get the following error:
```
/usr/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^

Error: unexpected end of parent stream
    at PacketStream.destroy (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:68:7)
    at PacketStream.write (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:131:41)
    at source (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:43:24)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-goodbye/endable.js:6:7
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at source (/usr/lib/node_modules/scuttlebot/node_modules/pull-pair/index.js:21:7)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:7:11
    at Array.forEach (native)
    at abortAll (/usr/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:6:7)
```

**Comment by dominictarr** [comment]
all the options are parsed with minimist, and for all commands except server, any option passed to the method. it's `sbot {command} {command arguments} -- {config settings}`

so you are calling `sbot.invite({port: ...})` to pass a config option on the command line, _and_ make a command, separate the config with -- `sbot invite {invite args} -- --port ...`

config is with [rc](https://github.com/rc) so you can also put any option in a enviroment var or `.ssb/config`

**Comment by cblgh** [comment]
Thanks, this helped a lot! 

I put host and port in ~/.ssb/config like:
```
host=<my host>
port=<my port>
```
and it worked! Also haven't seen the minimist way of specifying settings before, interesting!

I have another issue with my pub though, which are a couple of errors that I'm not sure what to do about. Details in https://github.com/ssbc/scuttlebot/issues/391.

**Comment by rhodey** [comment]
I ran into this bug and can report it failing for exactly 1 invite as well.

**Comment by evbogue** [comment]
I've seen this issue as well, because I often run decent with the command `node bin server --appname=ssb`. 

@rhodey Keep in mind that this issue is not the same as the bug reported above. Your error was:

```
 /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/plugins/invite.js:109
             cb(null, [addr.host, addr.port, addr.key].join(':') + '~' + seed.toString('base64'))
             ^
 TypeError: cb is not a function
     at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/plugins/invite.js:109:13
     at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/level-sublevel/shell.js:53:51
     at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/level-sublevel/nut.js:109:13
```

I think this qualifies as a bug, not a configuration issue, as I didn't know why I was getting the above error in decent.

**Comment by rhodey** [comment]
@evbogue thanks for the clarification, I'll go ahead an open a second issue proper and link to the two :+1:
