### ISSUE TITLE
sbot seems to either "lose interest in" or "forget" to connect to certain pubs

### ISSUE THREAD

**Issue by neutralinsomniac** [ssbc/scuttlebot#392]
I'm friends with ssb.rootsystems.nz and staltz's pub, along with a pub a friend is running at ssb.tapenet.org. It seems that my sbot instance doesn't want to connect to rootsystems or staltz's pub, as seen in this log:

`[jeremy@fedurra patchwork]$ npm start

> ssb-patchwork@3.3.1 start /home/jeremy/patchwork
> electron index.js

Log level: notice
RELOAD INDEX: {"version":13,"since":1491843343523}
RELOAD INDEX: {"version":0,"since":1491840040330}
Connected eu6.woll-e.net:8008:@H1j0ybFVLhnfYx47DekUadGysJPOaOAWtKFx5Le4+hQ=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Disconnected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Connected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
Disconnected ssb.tapenet.org:8008:@zjpqlL8E6IRNrVmS8UKplIsRDyabo4x2l4m4x95ydtE=.ed25519
`

Is this expected? It seems that my feed ends up getting quite behind as a result of not checking in with the "main" pubs.

**Comment by neutralinsomniac** [comment]
Now that I said this I just now saw one connection to one of staltz's pubs:
`Connected 94.237.35.82:8008:@0YTV22Eg35HneBaqZtbebkG5bTyRZxxKvjnsYtI2adY=.ed25519`

What determines the frequency/selection of check-ins?

**Comment by neutralinsomniac** [comment]
haha.... nevermind. Apparently ssb.rootsystems.nz is actually down. That would explain why I can't connect to it. Closing this issue. Sorry for the noise!

**Comment by ahdinosaur** [comment]
@neutralinsomniac the code for "gossip" is here: [scuttlebot/plugins/gossip](https://github.com/ssbc/scuttlebot/tree/master/plugins/gossip). basically, you connect to random(ish) pubs in your social network (using pub announce messages), if you get an error then you keep track of that pub as being maybe unreliable, and all this information is stored in `~/.ssb/gossip.json` to be used every time you boot up Patchwork.

**Comment by dominictarr** [comment]
Also, check out the `./plugins/gossip/schedule.js` there is various logic around when you try to connect to various pubs. it's pretty ugly in there. it does try to not connect to pubs that are giving errors, but it does check them again later incase they come back online.
