### ISSUE TITLE
Password protect private key

### ISSUE THREAD

**Issue by 2color** [ssbc/scuttlebot#394]
Hello,

I just got started with scuttlebot and saw the private key is stored in plain text in the `~/.ssb/secret` file. Are there any plans in the roadmap to password protect(encrypt at rest) it similar to how OpenSSL does it?

**Comment by dominictarr** [comment]
I would certainly merge such a pull request! but I am personally mainly focused on improving reliability and performance.

**Comment by 2color** [comment]
@dominictarr I'm guessing that work on this would belong in the [ssb-keys repo](https://github.com/ssbc/ssb-keys) right?

**Comment by dominictarr** [comment]
@2color correct!
