### ISSUE TITLE
disable encryption for amature radio users

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#395]
@frostyfrog asks if end-to-end can be disabled for amature radio users
https://github.com/ssbc/patchwork/issues/499

moving that issue to here, because it's more of a protocol issue.

issues: we'd need to disable both point-to-point (secret-handshake) and end-to-end (private messages)
that radio users would have to only follow feeds that didn't use private messages, although out-of-order messages could let them be involved in public threads.

if an amature radio user is keen to make the PRs, I'm happy to merge them, but there is a bit of work here. Are you ready to take this on?

**Comment by arj03** [comment]
Well you can now use `noauth` transform, so that should take care of this I think, see https://github.com/ssbc/ssb-config#connections

**Comment by cryptix** [comment]
If you can Interface you’re Radio with a tcp Socket, yes. Noauth should do the trick.

**Comment by christianbundy** [comment]
Would that give others the ability to post to your feed? Warning for US residents: amateur radio laws in the US would also require not replicating *any* private messages, so many/most feeds would be off limits.

**Comment by dominictarr** [comment]
sorry! @arj03 @cryptix  noauth isn't quite right: no auth assumes you _are_ authorized as the local key. if you provide no auth over a network connection, they'll be able to call any authorized api. But if we had something just like noauth, but treated the connection a connection from someone else. (but this would be a one-line change)

oh, turns out: just a configuration change: https://github.com/ssbc/multiserver/blob/master/plugins/noauth.js#L9 you just need to create noauth instances with something other than your own publicKey (my recommendation: a random value `crypto.randomBytes(32)`)

@christianbundy is correct. you'd have to have a feeds that were marked as non-private that didn't have private messages, or something like that.

I also recall, though, that encryption is forbidden, but authentication and integrity is not. so signatures are good - that means you could still have an authentication handshake, but just not an encrypted one. This would be pretty easy to whip up because authentication is not as difficult to design as privacy!
