### ISSUE TITLE
migrate ssb crypto to use `sodium-universal`

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#396]
from https://github.com/mafintosh/node-sodium-prebuilt/issues/10#issuecomment-293849292, it'd be great to upgrade our `libsodium` crypto to use the successor to `node-sodium-prebuilt`: [`sodium-universal`](https://github.com/sodium-friends/sodium-universal) (which is a wrapper for [`sodium-native`](https://github.com/sodium-friends/sodium-native) and [`sodium-javascript`](https://github.com/sodium-friends/sodium-javascript)).

- [ ] `secret-handshake`
- [ ] `private-box`
- [ ] `ssb-keys`
- [ ] `pull-box-stream`

help wanted!

**Comment by ahdinosaur** [comment]
oh, just noticed https://github.com/dominictarr/chloride/issues/4.

**Comment by evbogue** [comment]
We're using `sodium-native` now, which I think solves this issue.
