### ISSUE TITLE
scuttlebot.io in repo description is broken

### ISSUE THREAD

**Issue by carloslfu** [ssbc/scuttlebot#397]
This should be replaced by [https://www.scuttlebutt.nz/](https://www.scuttlebutt.nz/)

**Comment by dominictarr** [comment]
Thanks, but if you make a PR someone can just hit merge and we'll all be moving along faster. We've had a huge surge in interest and totally appreciate the enthusiasm - but it's also quite exausting to get so many emails - I know this is just a simple thing, and maybe I could have just done it in the time it took to write this, but I'd rather see your name on the commit log than another one by me.
