### ISSUE TITLE
New Pub Server

### ISSUE THREAD

**Issue by sardaukar** [ssbc/scuttlebot#402]
I have setup a new easy-ssb-pub server that gives out invites at http://ssb.nootch.net/

Feel free to add it your list of Pub Servers. It will be up 24/7.

**Comment by dominictarr** [comment]
anyone can edit the wiki, so feel free to add it your self!

**Comment by sardaukar** [comment]
Oh OK, the list mentions "You can add a pub by opening an issue on the repo." Sorry

**Comment by dominictarr** [comment]
oh sorry, I just changed it to say to add your own pub.

**Comment by sardaukar** [comment]
Done! Thanks.
