### ISSUE TITLE
Cannot connect to ssb.celehner.com and pub.doge.haus with reusable invite codes 

### ISSUE THREAD

**Issue by lpww** [ssbc/scuttlebot#409]
I'm having trouble connecting to the following pub servers from [the wiki](https://github.com/ssbc/scuttlebot/wiki/Pub-Servers). Is anyone else experiencing this? The other reusable invite pubs are working just fine. 

> ssb.celehner.com, run by cel@celehner.com ssb.celehner.com:8008:@5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519~NMJvRYIGDSwyPyER8E1q6rHHpY/AWEMSebtXAFgsHl4=

> pub.doge.haus, run by jake@doge.haus pub.doge.haus:8008:@7nTbqZVRYRo7FokY8BBYGpXvvveRPb4u+G1vunRmNn4=.ed25519~ZnWdvbLNzL/hu2QV4a1fj8zgvEHV1PgQBnFGl46uFNg=

**Comment by lpww** [comment]
Update: I got an error when attempting to join but now `pub.doge.haus` is displaying as a connected pub?

**Comment by ahdinosaur** [comment]
hey @lpww, the most likely explanation is that those pub invites are "all used up". as in, when you create an invite you specify how many times it can be used, and those have probably been used that many times.

/cc @clehner @jekrb

**Comment by lpww** [comment]
> the most likely explanation is that those pub invites are "all used up"

Ok, that would make sense. Thanks, @ahdinosaur

> you will connect with any public peers in your "neighborhood" (friends and friends-of-friends) to ask about mutual friends. using an invite will cause you to become friends with the pub, but you might also talk with non-friend pubs to ask about mutual friends.

I think what you're saying is that once I'm connected to the network, aka my "neighborhood", it will leverage other pubs to connect me to as many neighbors as possible? 

I'm assuming this is because all those pub servers belong to the same neighborhood so I only really need to connect to one to become discoverable?

**Comment by jekrb** [comment]
Hey thanks for spotting this!

Yeah pub.doge.haus likely ran out of invites. 
I'll update it with easy-ssb-pub so invites can continuously be requested by users  (I did the same for pub.tshirt.horse) 

Enjoy your weekend!

**Comment by jekrb** [comment]
Also as to why pub.doge.haus was showing up as connected, one of your friends is also probably friends with pub.doge.haus.

Pubs are just like any other peer (just with static IP addresses) and I _believe_ by default patchwork will replicate data with peers of up to two hops away (friends of your friends)

**Comment by lpww** [comment]
> Also as to why pub.doge.haus was showing up as connected, one of your friends is also probably friends with pub.doge.haus.

Ahha, thanks for explaining that

> Pubs are just like any other peer (just with static IP addresses) and I believe by default patchwork will replicate data with peers of up to two hops away (friends of your friends)

Is a pub comparable to a torrent tracker?

**Comment by jekrb** [comment]
Hey @lpww I just updated [pub.doge.haus](https://pub.doge.haus/) (with SSL for added security 😄  )

You should be able to go to [pub.doge.haus](https://pub.doge.haus/) and get a new invite code on the fly by pressing the blue button in the center.

Here is is a link to a ssb thread that explains pubs a bit more: https://viewer.scuttlebot.io/%25lxUClUyoEVHQ0OIRq2uslFPcPJeJ2UmPROKdl996RFU%3D.sha256

**Comment by lpww** [comment]
Thanks, it's working now! Also looking forward to getting more information on pubs from that thread 👍
