### ISSUE TITLE
How to repair a forked feed

### ISSUE THREAD

**Issue by regular** [ssbc/scuttlebot#410]
Hi @mixmix and @dominictarr , thanks for trying to help me fix my (potentially) forked feed problem. I thought maybe we can establish a communication channel here so I don't disturb @jfr3000 while she's coding :)

My situation:
I posted some stuff a week ago and was surprised to see no response whatsoever. I finally figured that it might be the problem that @cryptix ran into by posting with a client that had not fully synced its own identity's feed. So I followed the advise in that patchwork thread and `rm -rf ~/.ssb/db`. (I have a second client in the LAN that has my content).

I ran `sbot server` stand-alone, hoping it would sync from the other client.
Then I started patchwork. I can see the other client under "Local" (its key at least, not its name) and it has the green dot with the green circle around it (indicating that it is syncing?) However, there's no sync progress (no progress bar at the top, no green circle progress) and I can leave this sitting for hours and it won't change. There's a spinner under "Active Channels" and one in the main view saying "Loading ...`". That's it. Oh, when patchwork started, it asked me to describe myself, which I cancelled, in oder to not create a message in my feed.

In the thread mentioned above (I'd link to it but can't find it), @dominictarr talks about "manually following a pub". I don't know how to do that. Doesn't following mean to create a contact message on my feed? Wouldn't that cause another feed fork? Or can I connect to a pub with `sbot gossip.add` maybe?

**Comment by regular** [comment]
```
➜  dev sbot whoami
{
  "id": "@nti4TWBH/WNZnfwEoSleF3bgagd63Z5yeEnmFIyq0KA=.ed25519"
}
➜  dev sbot createHistoryStream --id @nti4TWBH/WNZnfwEoSleF3bgagd63Z5yeEnmFIyq0KA=.ed25519
--> 82 messages, (including the ones that don't sync)
```
@dominictarr said (on ssb)
> The latest message i have from @regular is %KI+rqpWWL0qsG9VvHtn1AGR8rhNxnB8zYCGcTpq30fk=.sha256 it's encrypted. That is at message sequence 27.

> If he can run this command to check their 27th message:
> sbot  createHistoryStream --id @nti4TWBH/WNZnfwEoSleF3bgagd63Z5yeEnmFIyq0KA=.ed25519 --sequence 27 --limit 1
and if it has a different hash to the above, it's a forked feed. The simplest fix in that case, is delete the database (not the secret file) and resync.
> If it's the same hash, it's a different problem.


```
➜  dev sbot  createHistoryStream --id @nti4TWBH/WNZnfwEoSleF3bgagd63Z5yeEnmFIyq0KA=.ed25519 --sequence 27 --limit 1
{
  "key": "%Ifiy/eiYfaSCXAAI+GopQ3+3crqdup841KMFIrHg6lU=.sha256",
  "value": {
    "previous": "%zMoMZdI1fhrR3UcXqx95X2sv/08IQUOZBl/Fy+bhNNg=.sha256",
    "author": "@nti4TWBH/WNZnfwEoSleF3bgagd63Z5yeEnmFIyq0KA=.ed25519",
    "sequence": 27,
    "timestamp": 1475855079873,
    "hash": "sha256",
    "content": "Vuxo7UOV1SYccv4kSJYQM0mpzrXcsjKS/g24nLdeVDfxCwjMRVnCnX/4epFpOOZ5MHOyCfuNljtWBYODAFRUKfvjvypgKovWhzRKwRDNwbJ9D41WRh4vyysZhy/f0kl822S8ah5qHUgu6dFsOjzepsEuT/g3mHNQvsu1RjqjmtNQopnLfKYEZ/AkyIKyn/QtJgIdjHkL/tdZ633x03Ke8KktyFH8HuRVp9mkhSON9Xm9vGIEwDg+eVKMiLXfEXzcBkRsZXN0fbl1N/Ab3VflWxmIIFHZEK8xxmZbJiwoJnNNETFDmQBHn2vSBE8CZzbPZH94YekJYH+HWofhU+qhzbjZLYVC1+76CVP212PysLjcnb6qbBy18MfE97AcCNfWNH2IUqh8h9sva/bKcAimW/Ws0IjmL4gZoJNQRY5Oflz6FtNIYtPDX5WjJmBCIqElzo2efUOW+6vpb+dcFVhz4SVL0toVdtBBIWrqq+d3x9E+m9G1dDhOTYswHOw3MwGttI2D9+ue.box",
    "signature": "wfyYPWfBsuH1juf9Wwv1xQ92u9IwU1iW2pNa0/KHFfRQ2qsnB0M3b4Vm/7hI1QjmkB6HhAFTc73I05iJLeKSCw==.sig.ed25519"
  }
}
```
The key doesn't match the hash you see, so that would mean I indeed have a forked feed? Seems like the other client in the LAN has that fork too (and the rest of the world does not)

**Comment by kseistrup** [comment]
I see the key `%KI+rqpWWL0qsG9VvHtn1AGR8rhNxnB8zYCGcTpq30fk=.sha256` for your sequence 27, timestamped 1474662814833 (Fri Sep 23 20:33:34.833 UTC 2016).

The key `%Ifiy/eiYfaSCXAAI+GopQ3+3crqdup841KMFIrHg6lU=.sha256` is reported as missing.

**Comment by dominictarr** [comment]
first check if your node remembers any pubs. there should be a `~/.ssb/gossip.json` since I don't remember what version. If that still exists your node should just connect to a pub by it self.
check by doing `sbot gossip.peers` if the response is empty, you can add a peer manually.
`sbot gossip.add net:128.199.132.182:8008~shs:DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=
`
will add my pub, and then it should resync everything.

**Comment by regular** [comment]
Thanks, @kseistrup , that's consistent with what @dominictarr sees.

**Comment by regular** [comment]
`sbot gossip.peers` has a lot of output (2000+ lines). I added your pub. My feeling is that I am syncing with peers that have different world views. The one on the LAN got infected with my forked feed ... So I'll disconnect it, `rm -rf ~/.ssb/db`, restart sbot and add your pub.

**Comment by kseistrup** [comment]
Perhaps you should move `gossip.json` out of sight before you add the pub so that your client doesn't connect to peers with the forked again.

**Comment by regular** [comment]
So, I took down the other local sbot, and also my own pub (I think it also had my forked feed), deleted the database, started sbot, added your pub as gossip peer, and indeed, I now get the same hash as you do for sequence numbeer 27.

However, pathwork still refuses to show anything. It is in the same state as described above. Spinning forever, not showing any content.

It spits out an error "NotFoundError: could not find matching timestamp for index:", not sure if that is related or not:

```
> ssb-patchwork@3.4.0 start /Users/regular/dev/patchwork
> electron index.js

Log level: notice
RELOAD INDEX: {"version":0,"since":1496747329096}
RELOAD INDEX: {"version":13,"since":1496748362308.0273}
connect { host: 'pub.37i.net',
  port: 8008,
  key: '@ZZSaYcKvwzqlIw43LyfJhGMu7HzXtsX3s4emi/GP0ew=.ed25519',
  source: 'stored',
  announcers: 3,
  duration:
   { mean: 68245.44230769231,
     stdev: 152530.5422789171,
     count: 52,
     sum: 3548763,
     sqsum: 1451996349631 },
  stateChange: 1496748389659,
  client: true,
  ping:
   { rtt: { mean: 2138, stdev: 0, count: 1, sum: 2138, sqsum: 4571044 },
     skew: { mean: -25, stdev: 0, count: 1, sum: -25, sqsum: 625 } },
  failure: 0 }
connect { host: 'freedombone.net',
  port: 8008,
  key: '@aCjZYf6p0k7VINLoXF2J361VLW7SX7SzzBuiE4JoQEQ=.ed25519',
  source: 'stored',
  announcers: 2,
  duration:
   { mean: 24757.9,
     stdev: 23254.447657168723,
     count: 40,
     sum: 990316,
     sqsum: 46148917930 },
  stateChange: 1496748426858,
  client: true,
  ping:
   { rtt: { mean: 1712, stdev: 0, count: 1, sum: 1712, sqsum: 2930944 },
     skew: { mean: -332, stdev: 0, count: 1, sum: -332, sqsum: 110224 } },
  failure: 0 }
connect { host: '176.58.117.63',
  port: 8008,
  key: '@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519',
  source: 'pub',
  announcers: 61,
  duration: null }
Connected freedombone.net:8008:@aCjZYf6p0k7VINLoXF2J361VLW7SX7SzzBuiE4JoQEQ=.ed25519
Connected pub.37i.net:8008:@ZZSaYcKvwzqlIw43LyfJhGMu7HzXtsX3s4emi/GP0ew=.ed25519
NotFoundError: could not find matching timestamp for index:{"timestamp":1496743568251.3342}
    at /Users/regular/dev/patchwork/node_modules/streamview-links/index.js:164:31
    at /Users/regular/dev/patchwork/lib/private-with-index.js:85:29
  NotFoundError: missing timestamp:1496743568251.3342
    at /Users/regular/dev/patchwork/lib/private-with-index.js:85:32
    at /Users/regular/dev/patchwork/node_modules/level-sublevel/shell.js:101:15
  NotFoundError: Key not found in database
    at /Users/regular/dev/patchwork/node_modules/level-sublevel/shell.js:101:18
    at /Users/regular/dev/patchwork/node_modules/level-sublevel/nut.js:121:19
[more pub-related stuff]
```

**Comment by regular** [comment]
Do I have to delete more stuff? Some index for example?

**Comment by regular** [comment]
Got it! 🎉  I needed to `rm -rf ~/.ssb/private`. Now patchwork starts up fine! Hope this helps someone in the future.
