### ISSUE TITLE
Error: Cannot find module './plugins/friends'

### ISSUE THREAD

**Issue by substack** [ssbc/scuttlebot#422]
Is there a file missing from git?

**Comment by substack** [comment]
Got it working by making a stub file and fixing some other things.

**Comment by dominictarr** [comment]
in scuttlebot@10 it's in ssb-friends module instead of plugins/friends.js

**Comment by evbogue** [comment]
This was an upgrade issue when the `ssb-friends` module was being rolled out, closing.
