### ISSUE TITLE
SSL out of date for scuttlebot.io

### ISSUE THREAD

**Issue by herwix** [ssbc/scuttlebot#428]
Hey folks, 

just wanted to let you know that your SSL certs seems to be out of date which makes browsers block access to your sites until you have manually validated the cert. Hope this is the right avenue to make you aware of this! :)

Thank you and keep up the great work!

**Comment by clehner** [comment]
Thanks for the alert. I am working on fixing this now.

**Comment by clehner** [comment]
Fixed. Thread on SSB for further discussion: [%TtE3p5KzVK8NU1U1gV6aF7W0CIvWfKSHCI24a3JLEDI=.sha256](https://viewer.scuttlebot.io/%25TtE3p5KzVK8NU1U1gV6aF7W0CIvWfKSHCI24a3JLEDI%3D.sha256)

**Comment by mmckegg** [comment]
Unfortunately I'm getting a dns resolution problem when I try:

<img width="624" alt="screen shot 2017-07-27 at 4 50 04 pm" src="https://user-images.githubusercontent.com/66834/28654875-b9f9afaa-72eb-11e7-98b6-36c9176b12e9.png">

**Comment by clehner** [comment]
@mmckegg can you paste output of `dig viewer.scuttlebot.io` or `host viewer.scuttlebot.io`?

**Comment by mmckegg** [comment]
```
$ dig viewer.scuttlebot.io
; <<>> DiG 9.8.3-P1 <<>> viewer.scuttlebot.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 27347
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;viewer.scuttlebot.io.		IN	A

;; Query time: 2778 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Jul 27 17:33:22 2017
;; MSG SIZE  rcvd: 38
```

```
$ host viewer.scuttlebot.io
;; connection timed out; no servers could be reached
```

**Comment by clehner** [comment]
Ok, I'm guessing the router at 192.168.0.1 is caching some outdated info. It should refresh at some point.

Are git.scuttlebot.io and scuttlebot.io any different?
