### ISSUE TITLE
sbot invite.create {n} produces the same invite code over and over again

### ISSUE THREAD

**Issue by regular** [ssbc/scuttlebot#434]
This behaviour started out of the blue and even persists after a restart. I am getting the exact same code everytime, even if n differs.

Any idea? I'll dive into the code soonish.

**Comment by regular** [comment]
sorry, i' wrong, I don't sleep enough lately. :/

**Comment by dominictarr** [comment]
haha, this would be a very weird error (broken system randomness?) but sleep is important!

**Comment by mmckegg** [comment]
Turns out @regular was living the same day over and over!

**Comment by regular** [comment]
Sure, keep laughing! One day, when humanity used up all of the universe's entropy, then you'll come back to this issue, and you will ... realise! And ... and then ... !

**Comment by dominictarr** [comment]
make sure you keep some of these invite codes around, so that if the world is doomed you'll be able to travel back to 2017 and possibly avert the disaster
