### ISSUE TITLE
Update to use sodium-native v2 for latest node/electron builds

### ISSUE THREAD

**Issue by mmckegg** [ssbc/scuttlebot#449]
The version of sodium-native that scuttlebot currently uses doesn't have prebuilds for the latest versions of node and electron.

We need to update chloride (I think) to bring this in. Although apparently v2 has [some small breaking changes](https://github.com/sodium-friends/sodium-native/issues/34#issuecomment-342398627).

cc @dominictarr

**Comment by cryptix** [comment]
+:100:

**Comment by mmckegg** [comment]
Also need to update: https://github.com/ssbc/scuttlebot/blob/d4162feb359ca070d0c7a138f94b2e17190adc88/package.json#L58

**Comment by cryptix** [comment]
> Also need to update

Also? is there something else that needs updating in this repo?
