### ISSUE TITLE
indexes.forEach is not a function

### ISSUE THREAD

**Issue by fuzzyTew** [ssbc/scuttlebot#451]
I just install scuttlebot and tried to accept an invite code.  The server immediately crashed and will not restart:
```
$ sbot server
flumelog-offset: blockSize and codec params moved into an object. https://github.com/flumedb/flumelog-offset
Log level: notice
.................................................. (indexes:0%)/usr/lib/node_modules/scuttlebot/node_modules/flumeview-query/index.js:25
    indexes.forEach(function (index) {
            ^

TypeError: indexes.forEach is not a function
    at /usr/lib/node_modules/scuttlebot/node_modules/flumeview-query/index.js:25:13
    at reduce (/usr/lib/node_modules/scuttlebot/node_modules/flumeview-level/index.js:88:25)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-write/index.js:35:23
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-write/index.js:41:13
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-cursor/cursor.js:32:13
    at getMeta (/usr/lib/node_modules/scuttlebot/node_modules/flumelog-offset/inject.js:43:14)
    at next (/usr/lib/node_modules/scuttlebot/node_modules/pull-cursor/cursor.js:27:11)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-cursor/cursor.js:20:11
    at Function.many.once (/usr/lib/node_modules/scuttlebot/node_modules/obv/index.js:39:7)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-cursor/cursor.js:13:13
````
Any ideas?

**Comment by christianbundy** [comment]
Having the same problem on my first build. Unsure of whether I'm doing something wrong or whether this is a new regression.

**Comment by fuzzyTew** [comment]
It seems the ssb-query module is instantiating the flumeview-query module with the value 1 for the indexes parameter, while flumeview-query is expecting this value to be an array.

The only way I can get sbot running is with the patchwork binary, and the modules are bundled up in it so I can’t inspect them to see what’s different.

**Comment by dominictarr** [comment]
oops, I accedentially published a breaking change, fixed in flumeview-query@4.0.1 and ssb-links@2.0.1 and ssb-query@1.0.1, if you reinstall scuttlebot's node_modules you should get all this stuff.

**Comment by kseistrup** [comment]
How do I ‘reinstall scuttlebot's node_modules’? If I remove scuttlebot and reinstall it I get flumeview-query@3.0.7, ssb-links@3.0.0, and no ssb-query module.

**Comment by cryptix** [comment]
Yeah, I fear the problem here is the major version bump so the packages that use these also have to update...

**Comment by av8ta** [comment]
You could try going into your scuttlebot directory inside the node directory where global packages are installed.

In package.json delete the lines for each of those three packages.
In a terminal in that directory
```bash
npm i --save flumeview-query@4.0.1
npm i --save ssb-links@2.0.1
npm i --save ssb-query@1.0.1
```
Then to be sure, delete the node_modules directory.
```bash
npm i
```
The dependencies will install and hopefully you can run in one terminal
```bash
sbot server
```
And in another terminal
```bash
sbot whoami
```
Hopefully it outputs your public key to show sbot is working. Then run patchfoo and it should talk to the sbot you just started.

**Comment by cryptix** [comment]
didn't test it but the hack of depending on a higher version in the root project even if the _to be updated_ dependencies are nested two levels deeper sounds reasonable to me.

**Comment by kseistrup** [comment]
@av8ta,

Thanks for your suggestion, but unfortunately it didn't help. The `sbot server` runs fine (as did it before), but accdessing it through patchfoo yields an exception. I tried editing all the plugins' `package.json` files and doing an install after removing the `node_modules` directory for each plugin, but in the end it didn't seem to make a difference.

**Comment by fuzzyTew** [comment]
If I wipe my install completely and reinstall scuttlebot, it seems to be working fine now.  Not getting this particular error anymore.
