### ISSUE TITLE
viewer.scuttlebot.io is down :(

### ISSUE THREAD

**Issue by dcposch** [ssbc/scuttlebot#455]
### example
https://viewer.scuttlebot.io/%25yNeBjEGdw1ymqbwAaGveKYu1jxiRAXRlSNz4L6mf4qM%3D.sha256

### result
hangs for a long time (30+ seconds), then returns the following stacktrace

![image](https://user-images.githubusercontent.com/169280/33973288-e1b40186-e036-11e7-9201-ef8e292a21ca.png)

i've tested links to messages, gatherings, and user profiles--all appear broken

i've created a Gathering for my birthday bbq and wanted to invite people to come (and also to install Patchwork and test-drive the decentralized web!)

to invite people on twitter and facebook, i need to be able to create a link

### expected result

![image](https://user-images.githubusercontent.com/169280/33973347-3865058e-e037-11e7-98d7-8ad9b4f74b71.png)

**Comment by dcposch** [comment]
cc @jondashkyle

**Comment by arj03** [comment]
Hi @dcposch 

This is not really a bug in scuttlebot. The viewers are run by the community. Try one of the other viewers:

http://between-two-worlds.dk:8807/%25syRnY6a9kb1AOZBZD7sSJzOtxm%2BkQSJUUSUamuMGBOk%3D.sha256
