### ISSUE TITLE
Name consistency

### ISSUE THREAD

**Issue by donpdonp** [ssbc/scuttlebot#456]
As someone who is learning the ropes of scuttlebot, it is particularly confusing that the project uses 3 or 4 different yet very similar names.

The project, as I know it, it called "scuttlebot". Looking around the readme's, etc. I've come across scuttlebot, sbot, scuttlebutt, secure-scuttlebutt, and ssb. 

For example, the Matrix.org project has the Matrix protocol, and the Synapse server. Its clear when someone is talking about the project vs the implementation.

Its be nice to get a definite answer at least as far as  -bot/-but/-butt

ps. also a nit-pick is the default config dir of ~/.ssb. "ssb" by itself it not descriptive. After not thinking about scuttlebot for a few months and going through my dot files, "ssb" is a big "what was that again?". ~/.scuttlebot would be clearer.

**Comment by evbogue** [comment]
@donpdonp At some point someone suggested re-naming `scuttlebot` and thus `sbot` to `ssb-server`. Everyone in the ssbc supported this decision, but action was never taken on the rename.

**Comment by dominictarr** [comment]
at some point we'll rewrite it and the plan was to rename then

**Comment by donpdonp** [comment]
out of curiosity, what is the motivation for a rewrite?

**Comment by ahdinosaur** [comment]
yeah, this has come up before:

- [%BIn4rQl8o7PxeolhiZCw77fUN5gGpOv6I3gDXhMfP+M=.sha256](https://viewer.scuttlebot.io/%25BIn4rQl8o7PxeolhiZCw77fUN5gGpOv6I3gDXhMfP%2BM%3D.sha256)
- https://github.com/ssbc/scuttlebot/issues/378
- https://github.com/ssbc/secure-scuttlebutt/issues/159
- https://github.com/ssbc/ssb-handbook/blob/master/modules.md#an-explanation-of-terms-repos-and-project-history

keen for a rename!

**Comment by donpdonp** [comment]
thanks for those references! that last link is the best part. 

 I'm all for ssb-server and ssb-cli but 'ssb' doesnt mean anything (Single Side Band to Ham Radio people). Once all the packages were ssb-<something> I'd push for renaming them to scuttlebutt-<something>, including the cli program from sbot to scuttlebutt, and the config dir from ~/ssb to ~/.config/scuttlebutt.  the name scuttlebot, cute as it is, would silently be dropped as it became the reference implemetation.

**Comment by staltz** [comment]
Hi Don. :) 
The word "*name*" also doesn't mean anything. The semantic association comes with time. I hope the same can happen with SSB, I find it decent and neutral as a name for a protocol (on the same neutrality level as "TCP").

**Comment by donpdonp** [comment]
okay thanks for the project history in these responses. I'll close the issue and hope it adds at least a little weight to make a name change, to whatever that ends up being.
