### ISSUE TITLE
10.5.0: syncing stuck

### ISSUE THREAD

**Issue by cryptix** [ssbc/scuttlebot#463]
Hey,

I had my sbot running for quite some time but it would just print `skip gossip`. I don't understand half of the code in the scheduling but it seems like `server.lastMessageAt` doesn't get removed when a gossip connection dies. The 2nd half of the [the if](https://github.com/ssbc/scuttlebot/blob/master/plugins/gossip/schedule.js#L142) was always false when I checked it with the inspector.

I'm not sure what caused it but it doesn't sync for me. I'm currently writing code to use the `sbot.status` api for tale:net maybe I understand better what's going on once that is working.

**Comment by evbogue** [comment]
I'm not 100% stuck, having just upgraded to 10.5.0. However, I am seeing the `skip gossip` message a lot in my terminal.

**Comment by mmckegg** [comment]
That console.log shouldn’t be there. 

This code is supposed to suspend gossip connections if you are currently downloading messages from a pub to prevent downloading the same messages from multiple pubs. That means the “skip gossip” message will be showing whenever there are new messages to download. That’s a good sign that it is working, just shouldn’t be logging that out. 

@cryptix are you seeing “skip gossip” continuously being logged to console?

**Comment by cryptix** [comment]
> @cryptix are you seeing “skip gossip” continuously being logged to console?

yup

**Comment by dominictarr** [comment]
kinda weird that it would be continuiously logging... because `time > Date.now() - 500` should only be true if you have received a message in the last half second. (i.e. you are actively replicating)

**Comment by cryptix** [comment]
Didn't see this for quite some time.
