### ISSUE TITLE
Can't clone repos

### ISSUE THREAD

**Issue by cazala** [ssbc/scuttlebot#464]
I've setup a pub in a DO droplet: http://ssb.caza.la and I can't clone any repo on my local machine using `ssb`:

```
git clone ssb://%ALMgAp5VaIx3WFaBTkgzKlPss7CG+2X+M4h5syyIEDg=.sha256 test
Cloning into 'test'...
Repo not found with ID %ALMgAp5VaIx3WFaBTkgzKlPss7CG+2X+M4h5syyIEDg=.sha256
```

Everything works fine when cloning via http tho:

```
git clone http://ssb.caza.la/%25ALMgAp5VaIx3WFaBTkgzKlPss7CG%2B2X%2BM4h5syyIEDg%3D.sha256 test
```

I'm running the server (on the droplet) using `sbot server --host ssb.caza.la` and on my local machice using `sbot server`

Any ideas why?

**Comment by evbogue** [comment]
@cazala Do you have `git-ssb` installed and are already running `scuttlebot`? If not it's probably easiest to clone from github.

**Comment by cazala** [comment]
yes sorry I forgot to mention that, I do have installed `git-ssb` on my local machine. I would love to host this repo on github but that's not an option :(

**Comment by cazala** [comment]
Okay I managed to make it work by doing `sbot invite.create 1` on my server and then `sbot invite.accept {code}` on my local machine, after that cloning worked just fine. So if people want to clone my repos they will need me to give them an invite first? Is that the only way?

**Comment by evbogue** [comment]
@cazala Yah, you could probably offer a clone url by running `git-ssb-web` on your server. The best person to talk to about this would probably be @clehner http://celehner.com/ or contact him via the main ssb network. He's actively working on improving the `git-ssb` experience right now, as far as I know. He's a bit harder to talk to on the oldernet.

Your `git-ssb` repo will be clone-able via everyone on the main ssb network. Is that alright for your usecase? I'm not sure if you're looking for something more private, or if just decentralized is enough.
