### ISSUE TITLE
Is it possible to get the server config over websockets?

### ISSUE THREAD

**Issue by evbogue** [ssbc/scuttlebot#465]
I've been experimenting with fast network switching using ssb.

Imagine you have three ws:// addresses in a drop down in your client. Using this dropdown, you can quickly switch between the main ssb network, decent, and other future ssb altnets.

It occurred to me that if the client could access the server config, then it could quickly grab the necessary configuration options. Once you have that info, the client could use whatever ssb network it wants, without needing to rebuild the client while pointing it at a different network configuration.

Is it already possible to access the `sbot.config` over websockets? If not, I'm interested in researching the best way to serve some (or all) of the configuration options on a web server.

This is more of a informational thread than an actual issue, so I'm also open to hearing about implementation strategies here. Also, are there any downsides to this that I'm overlooking?

**Comment by dominictarr** [comment]
there isn't currently a way to update configuration while sbot is running, it would need to change the setting, and then various sbot plugins may need to reinitialize

**Comment by staltz** [comment]
This may be correlated to a bug I found with sbot in react native where the app crashes when changing from Wi-Fi to 4G or vice-versa.

**Comment by evbogue** [comment]
@dominictarr You're right about this, it doesn't seem to be possible to reconfigure server-side sbot on the fly. 

I ended up sharing server config and importing it into the client. This allows the entire client to configure itself to the host it is pointing at -- if the host is sharing the necessary ssb configuration information. 

It's not realtime altnet switching, but I think this is good enough for now. https://github.com/evbogue/decent/tree/next

**Comment by evbogue** [comment]
This is resolved. Example: https://github.com/evbogue/mvd/blob/master/bin.js#L50
