### ISSUE TITLE
error in the 'read your log' documentation

### ISSUE THREAD

**Issue by joelamouche** [ssbc/scuttlebot#471]
in http://scuttlebot.io/docs/basics/read-your-log.html

var pull = require('pull-stream')
pull(
  sbot.createUserStream({ id: yourId }),
  pull.collect(err, msgs) {
    if (err)
      throw err
    console.log(msgs)
  })
)

should be

var pull = require('pull-stream')
pull(
  sbot.createUserStream({ id: yourId }),
  pull.collect(function(err, msgs) {
    if (err)
      throw err
    console.log(msgs)
  })
)

**Comment by dominictarr** [comment]
I can't see a difference - is this correct?

**Comment by arj03** [comment]
Missing function( in pull.collect line
