### ISSUE TITLE
What's this licenced under?

### ISSUE THREAD

**Issue by pietgeursen** [ssbc/scuttlebot#474]

**Comment by dominictarr** [comment]
it says MIT

**Comment by pietgeursen** [comment]
Oh, damn, sorry, where? It doesn't see it in the readme.

**Comment by cryptix** [comment]
[It's in the package.json](https://github.com/ssbc/scuttlebot/blob/master/package.json#L92) but quite hard to find there...

**Comment by soapdog** [comment]
@cryptix and @pietgeursen it was a silly fix but I sent a PR...
