### ISSUE TITLE
Using Scuttlebot/butt for a large scale implementation with individual user-scoped instances

### ISSUE THREAD

**Issue by csuwildcat** [ssbc/scuttlebot#487]
Hello Scuttlers,

We (Microsoft and others) are working on an open source initiative related to decentralized identity, specifically secure, decentralized personal datastores called Identity Hubs. What we aim to enable is a way for users to select or run several instances of a personal datastore that replicate changes between each other.

The first, most pressing question is if we can fire up multiple instances that act as little meshes for each user's selected ring of devices. For example:

Alice has a Hub at `foo.com` and `bar.com`, she wants to publish a new feed to one and have that feed replicated to the other Hub. Both `foo.com` and `bar.com` Hubs may contain similar rings for millions of users, which reference different external instances of the user's choosing.

How possible is this today with Scuttlebot/butt?

**Comment by arj03** [comment]
Hello

Scuttlebutt contains feeds for each user that are immutable logs of messages. This means that its easy to replicate them to multiple places. In that way pubs are very similar to your hubs. You don't control who gets the messages, they will be replicated based on gossipping with a number of hops. The hops is based on how feeds are connected. The idea is that your gossipping strategy is independant of your feeds. So you can have a mega hub with tons of users, or a smaller hub for an organisation. Blobs (files) follow similar rules.

**Comment by csuwildcat** [comment]
All that is understood, but our question is a bit deeper:

In the DID world, one decentralized identifier can be backed by N keys used across N devices and tokens. These keys all represent the same user. We would like to understand how feasible it would be to instantiate a wholly separate Scuttle instances for *each user* so they can commit to the same shared log for their DID in a way that is unified and merged across all devices, in a multi-master replicated fashion.

**Comment by arj03** [comment]
It seems like what you are after there is similar to https://github.com/ssbc/ssb-same-as.

**Comment by staltz** [comment]
Hi @csuwildcat , interesting identity topic that you're working on, it's very important.

To clarify a bit about same-as, linked by arj03, it's a quite simple solution that works only as a client-side approach, where different instances are not merged in the data level, but simply merged in the UI. The different instances are treated as mutual friends, and by default sbot would replicate feeds from friends, up to a friends-of-friends hop of 3.

**Comment by evbogue** [comment]
> We would like to understand how feasible it would be to instantiate a wholly separate Scuttle instances for each user so they can commit to the same shared log for their DID in a way that is unified and merged across all devices, in a multi-master replicated fashion.

I think you could do this, but no one has structured an ssb network this way (yet). 

Actually, your idea might just be brilliant and solve the multi-device issue that we haven't solved yet.

I think what you're asking for is an altnet for each user, and then you treat the altnet as the users' identity. 

Take a look at how I'm handling quick altnet switching in Decent here: https://github.com/evbogue/decent/blob/master/config/inject.js#L18-L29

Let me see if I can repeat back to you what you're trying to do.

+ Create a different ssb altnet for each 'user' identity
+ Treat every identity on the altnet as the 'user'
+ Treat all of the messages from the altnet as messages from the 'user'

Next you can create a new and completely different social network UI, which treats all of the keys from each altnet as the same identity. 

This approach might have unintentional problems that I haven't thought up yet, and would require a bit of coding to make happen with the current implementation.

**Comment by dominictarr** [comment]
@csuwildcat it sounds like you are asking a couple different questions tangled together. I'm gonna try and tease them apart and see if I can answer them.

firstly, hubs: ssb users don't directly choose who can replicate them (like twitter users don't choose who can follow them). the pub design we currently have assumes that it's only replicating a few thousands of feeds (network of it's owner) if you wanted a pub to replicate _millions_ of feeds, that could be achived efficiently with some tweaks (waiting to see who the users asks to replicate before making your requests)

second: multimaster replication per user. yes, this is the intended design of ssb. the core concept is a feed (with strictly a single master), to represent a user with many devices, it would be represented as several feeds (linked to each other) and each device replicates the other device feeds (but only appends to the one which represents itself). To identitfy the user, you'd probably use a reference to the "main" device.

third: run a scuttlebutt "instance" per user. yes, but I don't think this is necessary there is no obligation that a particular user replicates any other user - you could put the millions of feeds into a "single instance" (no promise that the current implementation could scale to this many users!) and each user only replicates their own feeds. It sounds like you are only proposing that each user replicates their own data (not their friends, etc) is that correct? We've used ssb to implement a social network type application, but using it to replicate just your own data is even easier, of course.

**Comment by csuwildcat** [comment]
I'll take the next couple days to consider this feedback, then ask some follow-ups.

Is anyone here aware of the W3C Decentralized Identifier spec? There are a few concepts we'd hope to bring to SSB if we decide to leverage it, and I was wondering how familiar folks in this community were with it.
