### ISSUE TITLE
rename config to config.json

### ISSUE THREAD

**Issue by jedahan** [ssbc/scuttlebot#511]
It would be nice to use file extensions, yeah?

**Comment by dominictarr** [comment]
It doesn't use file extentions because it follows the standards in https://github.com/dominictarr/rc (unconfigurable configuration loader)

**Comment by jedahan** [comment]
@dominictarr rc looks really cool!
If you are amicable to merging https://github.com/dominictarr/rc/pull/85 that would be nice - I opened this issue after observing my friend have trouble getting started with scuttlebot.

Whether you merge or reject the idea, I will continue discussion in https://github.com/dominictarr/rc and leave this issue as a tracker for a) updating the rc dependency or b) closing.

**Comment by dominictarr** [comment]
thanks
