### ISSUE TITLE
test fail: not ok 4 .end() called twice

### ISSUE THREAD

**Issue by cryptix** [ssbc/scuttlebot#537]
I'd like to get the tests in order before advancing #536 but I have no idea why they fail like [this](https://travis-ci.org/ssbc/scuttlebot/jobs/424400713#L1560), also for me locally.

```
ok 1 should be equal
{ '@BKGGT1UeL1qYxvq/1AUb/S0iZv3RlC0walRCj5YDSf8=.ed25519': 1,
  '@exe+/ZFy0wKL2b0gKjuvFnajpqpDRbdXwx0+oNr3KRk=.ed25519': 1 }
ok 2 should be equal
{ '@BKGGT1UeL1qYxvq/1AUb/S0iZv3RlC0walRCj5YDSf8=.ed25519': 1,
  '@exe+/ZFy0wKL2b0gKjuvFnajpqpDRbdXwx0+oNr3KRk=.ed25519': 1 }
ok 3 should be equal
not ok 4 .end() called twice
  ---
    operator: fail
    at: EventEmitter.<anonymous> (/home/travis/build/ssbc/scuttlebot/test/block2.js:43:9)
  ...
1..4
# tests 4
# pass  3
# fail  1
```

I pushed the last versions as tags but looking at the [travis build history](https://travis-ci.org/ssbc/scuttlebot/builds) this seems to be think for some time now... :cold_sweat:

**Comment by christianbundy** [comment]
@cryptix 

I think this *might* be https://github.com/dominictarr/epidemic-broadcast-trees/issues/20 -- does that look like the same issue to you?

**Comment by dominictarr** [comment]
emitting `replicate:finish` twice would definitely cause an error like this, but looking at the code I'm not sure why this would happen.

**Comment by cryptix** [comment]
perfect. thank you!
