### ISSUE TITLE
technology.ssb-pub.com redirects to different page

### ISSUE THREAD

**Issue by radmen** [ssbc/scuttlebot#538]
I'm trying to sing into one of the listed pubs.

I got interested in technology.ssb-pub.com, yet it looks like this page redirects to a different page (http://pickuphighlights.com/) which seems to be something different.

**Comment by staltz** [comment]
Hi! Thanks for letting us know. This is not an issue in scuttlebot, but if the Wiki needs updating, I think you have the write rights to edit it.

**Comment by radmen** [comment]
I did as you said. Thanks!
