### ISSUE TITLE
local replication broken (or not configured?) in scuttlebot@12

### ISSUE THREAD

**Issue by evbogue** [ssbc/scuttlebot#545]
@gwenbell and I were trying to replicate over our [local sneakernet](http://gitmx.com/#%KXYmaRuB5LwP0eXHo2auGMwaXiPnPLWkRNwIRv6VxjA=.sha256), and discovered that it no longer works in scuttlebot@12. 

I [pinged](http://gitmx.com/#%KxTTqcekb81O3v+3k7Y+gjE+ZcrHfF9q+xR/vDVgZ88=.sha256) @arj03 but didn't get a response yet, so I thought I'd file an issue here, as I've been unable to figure out what is wrong.

How do you turn local replication on in scuttlebot@12 or is it broken?

There are no errors to report, unfortunately, local replication just doesn't work out of the box anymore.

**Comment by christianbundy** [comment]
I'm less familiar, but I'd still be happy to help debug. Are you just running `sbot server`, or doing it in Node by passing a `config` object? If you're passing a config object it might be useful to post the contents of `config.connections`. I think I broke local replication one time by *only* using the unix socket connection, so it may be worth double-checking that `config.connections.incoming.net` exists on sbot startup.

**Comment by evbogue** [comment]
@christianbundy Here's my ssb config: https://github.com/evbogue/mvd/blob/master/config/inject.js#L71-L79

```
    connections: {
      incoming: {
        net: [{ port: 8008, host: "localhost", scope: "local", "transform": "shs" }],
        ws: [{ "scope": "public", "transform": "shs" }]
      },
      outgoing: {
        net: [{ transform: "shs" }],
        ws: [{ "scope": "public", "transform": "shs" }]
      }
    },
```

**Comment by evbogue** [comment]
I noticed that standard `ssb-config` has 

```
    connections: {
      incoming: {
        net: [{ port: 8008, scope: "public", "transform": "shs" }]
      },
      outgoing: {
        net: [{ transform: "shs" }]
      }
    },
```

So maybe I should switch incoming to `scope: "public"`?

**Comment by evbogue** [comment]
I'm going to go home and see if 

```
    connections: {
      incoming: {
        net: [{ port: 8008, scope: "public", transform: "shs" }],
        ws: [{ scope: "public", transform: "shs" }]
      },
      outgoing: {
        net: [{ transform: "shs" }],
        ws: [{ scope: "public", transform: "shs" }]
      }
    },
```

works to enable local replication.

**Comment by evbogue** [comment]
@arj03 Cool. So this is broken right now, or is there a correct configuration I can use? If so, what is the correct configuration option? Can I have two net options, one public and one private, or will that break things?

**Comment by arj03** [comment]
The one you posted should work. The default config also works.

**Comment by evbogue** [comment]
@arj03 The config I posted, and the default scuttlebot config doesn't work for me. You said I needed at least one private interface, would 

```
        net: [{ port: 8008, scope: "private", transform: "shs" }],
```

work?

Or maybe I've run into an issue with local replication not working? 

I tried standard (non-mvd) scuttlebot@12.1.0, and that didn't sync over local wifi either. 

I'm about to go to work for five hours, but I'll check in tonight and try a few more things when we get home.

**Comment by arj03** [comment]
A public interface can work if no private is found. So I think the problem for you is that it doesn't really know which public to use for the local plugin, as you have both ws & net defined. ws needed to be public for you to have getAddress working. Can you somehow get in your mvd client get it to ask for the address using a different scope. Like sbot.getAddress('ws')

And then in config:

```
    connections: {
      incoming: {
        net: [{ port: 8008, scope: "public", transform: "shs" }],
        ws: [{ scope: "ws", transform: "shs" }]
      },
      outgoing: {
        net: [{ transform: "shs" }],
        ws: [{  transform: "shs" }]
      }
    },
```

Also when you tested two standard scuttlebot 12.1 was that both with default configs?

Thanks for testing!

**Comment by evbogue** [comment]
@arj03 Ok, trying this now (last night I just wanted to fold the jeans, close the store, have a PBR, and go to bed). 

`sbot.getAddress('ws')` is much more eloquent than my current code, so I'm down for adding it. 

Then I'll try this new config and see if that works!

**Comment by evbogue** [comment]
hmm, now nothing is working at all. 

I think part of the problem is I'm using a plugin system that dominic designed to serve the lite client, and now somehow that is no longer compatible with the new connections system. 

The other part of the problem is that I don't quite understand the new connections system, so I'm just stabbing around in the dark trying to get this to work, which must be frustrating for everyone to watch.

**Comment by evbogue** [comment]
Maybe I can use the new `noauth` option and rip a whole bunch of hacky stuff out of `mvd` and this will work...

**Comment by arj03** [comment]
Well there are two things here:

1) Getting WS working. NoAuth will help you here and make things smoother as its much faster as it doesn't have to do crypto for a connection to your own machine. But don't use it against a remote! :)

2) Local gossipping. Did you try with two sbots 12.1 with the default config on both machines? I have a feeling that by changing the configs to make ws work, you might have accidently broken local sync.

**Comment by evbogue** [comment]
@arj03 yah, I agree about not enabling `noauth` for remotes. Right now `mvd` doesn't require that you're friends with people in order to show you content and allow you to post -- you just won't replicate. But right now we're using `shs` over the wire, so I'd prefer to keep doing that.

scuttlebot@12.1.0 wasn't working for us the other day, but I want to test again to make sure.

In order to check and make sure that local replication is not broken I am going to

+ install a fresh scuttlebot@12.1.0 on both machines and do a new `npm` install on both repos
+ go back home to local-area meshnet area
+ post a message and see if it syncs between new scuttlebot installs

@gwenbell Is doing a new install of scuttlebot right now, then we'll head back and try this.

**Comment by arj03** [comment]
Thanks! Also make sure you have the default config enabled. At least the default connections. You can always add the ws stuff to check your clients after it has synced :)

**Comment by evbogue** [comment]
Ok, tested. local wifi replication works in scuttlebot@12.1.0. The first time I tested it, it was an uncontrolled experiment, and thus turned out to not be accurate.

What I'm going to do next is refactor `mvd` to better use the new connections configuration, and see if that fixes local replication.

**Comment by arj03** [comment]
Great news @evbogue! Feel free to ask again here if you need help with the connections for mvd.
