### ISSUE TITLE
Respect config.port and config.host for backward compatibility

### ISSUE THREAD

**Issue by regular** [ssbc/scuttlebot#552]
ssb-client/test/index.js fails with scuttlebot@>=12 (at least), because sbot ignores config.port.
This also breaks every single application using a non-standard port/anything else but localhost. This breaking change can easily be avoided by using config.port and config.host for the default net connection.

Breaking changes are evil, please try to avoid them whenever possible. @arj03 @cryptix

**Comment by regular** [comment]
Ok, looking at the code, it seems like thats exactly what is happening. hm ..

**Comment by regular** [comment]
ah, in the init function of secret-stack, a default net connection without port and host is created. That's where opts.host and opts.port get ignored. Adding port: opts.port, host: opts.host in line 98 fixes ssb-client/test/index.js

**Comment by regular** [comment]
I am unsure however, if this is really the best place to put this default connection?

**Comment by regular** [comment]
[this PR](https://github.com/ssbc/secret-stack/pull/27) fixes it.

**Comment by cryptix** [comment]
PR merged in secret-stack@4.2.4
