### ISSUE TITLE
sbot@13 bin.js has no support for websockets at all

### ISSUE THREAD

**Issue by regular** [ssbc/scuttlebot#554]
- ws.getAddress now is an unknown command (bad, breaks backward compatibility)
- getAddress returns no ws address either.

Currently there is no way to connect to a stock sbot from a browser.

**Comment by regular** [comment]
To reproduce:

```
git clone https://github.com/regular/ssb-integration-tests.git
cd ssb-integration-tests
npm i
npm t
```

**Comment by christianbundy** [comment]
Can confirm, although I'm not familiar enough with the plugin logic to understand why this is happening. It seems like this may be related to #551, but I'm not sure what the fix might be.

**Comment by regular** [comment]
it's because the ws plugin's create function is only called when there is config.connections.incoming,ws, which is not the case by default (but it should, because sbot used to support ws out of the box before the connection refactor) This is fixed in https://github.com/ssbc/ssb-config/pull/22

**Comment by regular** [comment]
fixed in ssb-config 2.3.6

**Comment by christianbundy** [comment]
Sweet, since this repo installs `ssb-config@^2.3.0` does that mean this issue is ready to close?

**Comment by regular** [comment]
Yes, I think so
