### ISSUE TITLE
non-feed key when loading clock @isfcnrnxl80iiy2ibgenfgepqqfq3vu5qyxcu+mssei=.ed25519

### ISSUE THREAD

**Issue by evbogue** [ssbc/scuttlebot#570]
I'm seeing this error in the latest sbot master. 

```
non-feed key when loading clock @isfcnrnxl80iiy2ibgenfgepqqfq3vu5qyxcu+mssei=.ed25519
```

That looks like a fake key to me?

**Comment by christianbundy** [comment]
It was added recently [here](https://github.com/ssbc/ssb-ebt/blob/a21467b71f089cb7044de71343555ca8df26a897/index.js#L61), although I'm unclear on what it means.

**Comment by dominictarr** [comment]
this is safe to ignore. I think some people followed names (not keys) from the command line, stuff like that.
I added checks to make sure it didn't save that, but some peers may have still requested those, and their clocks saved.

I have removed warnings about this in latest ssb-ebt
