### ISSUE TITLE
Broken link: Secure Scuttlebutt, Scuttlebot's global database protocol

### ISSUE THREAD

**Issue by jcalfee** [ssbc/scuttlebot#588]
https://github.com/ssbc/scuttlebot/blob/master/README.md#key-concepts

[https://ssbc.github.io/secure-scuttlebutt/](Secure Scuttlebutt), 
404 https://ssbc.github.io/secure-scuttlebutt/

**Comment by christianbundy** [comment]
Interesting, I wonder whether that should point to https://ssbc.github.io/scuttlebutt-protocol-guide/ now? Thanks for the bug report!

**Comment by jcalfee** [comment]
See: 
https://ssbc.github.io/scuttlebot/api.html

Key Concepts:
Secure Scuttlebutt: a global database protocol

**Comment by christianbundy** [comment]
Oh, it looks like that's built off of the `gh-pages` branch. We can fix it, but I wonder whether that should even be maintained anymore -- it's been abandoned for about three years.
