### ISSUE TITLE
Which type of stream should be used if order doesn't matter?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/scuttlebot#593]
It looks like I can either use `createLogStream()` or `createFeedStream()`, is one faster than the other (or better in any way)?

**Comment by dominictarr** [comment]
what are you using it for? are you just gonna dump the messages? or do you want to stream some now and more later? (i.e. from the point that you streamed already)

as it is currently, they are both about the same internally - they have a flumeview-level that maps a timestamp to an offset. createLogStream uses the received time and createFeedStream uses the claimed time.

using the claimed time means that a given range returned by createFeedStream, if called again after receiving additional messages, may return different results, but createLogStream is stable. Wether you want this is how i'd choose.

but also: there is a third option: `createLogStream({raw: true})` which skips the level view and gets you the raw offset log (even with offsets - if you have `seqs: true` hmm, which is on by default). If you are tracking the stream and streaming more, this would be the best to use.

**Comment by christianbundy** [comment]
Yeah, I'm just dumping the messages. I've prototyped some basic feed deletion, and now I'm working on pruning stray blobs afterward:

1. Stream all messages.
2. Collect blob references from each message.
3. Stream list of blobs.
4. Delete blobs that aren't referenced by a message.

It sounds like it doesn't really matter which I use (?), but it's good to know about `{raw: true}`! I tried setting `{ raw: true, seqs: false}` but it still included the sequence numbers, do you think that's a bug or is there another way to disable those? Thanks for letting me pick your brain.

**Comment by dominictarr** [comment]
thats a bug. pretty sure I found and fixed that in 9e2f0e84

**Comment by dominictarr** [comment]
that was: https://github.com/ssbc/ssb-db/commit/9e2f0e8499ba09363d5a4d1a72fa35696ba09de4

**Comment by christianbundy** [comment]
Coolo, thanks!
