### ISSUE TITLE
get invite flow as smooth as possible (thinking out loud)

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#61]
At this early stage we want developers to start using scuttlebot and running their own servers.
Although developers are smart, we must make the flow for setting up a server, and for using invite codes as smooth as possible...

The readme in my gossip pull request documents how easy it is currently:
https://github.com/dominictarr/scuttlebot/blob/gossip/README.md

I had to tidy up quite a few loose ends to get it this smooth, but it could be a bit better...

here are my ideas:
- instead of returning a json object, return a string which would be `<host:port>,<id>,<secret>` one string makes it easy to copy-paste and use as a command line argument in another script.
- I made scuttlebot follow the server you connect to... but really this is not secure (trusting the host) and the id should be part of the invite... it should only follow if that is the server that is connected to.

maybe:
- should the pub message and the follow message should be a part of the same message? maybe you follow a pub server and that message contains it's ip address? so you are saying "these are the pubservers I know about"
- should servers replicate with the first N friends, even if they are multilple hops away? this would bootstrap the network early on...

**Comment by gwenbell** [comment]
**sbot** it is -- thank you & closing now
