### ISSUE TITLE
proposal: bundled web frontends

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#63]
i'm going to suggest we ditch the ssbui package and make sbot our primary install. to make that work, we should make phoenix the default web frontend in sbot. if run without additional config, the interface will only be available locally, so its not a danger

for pub servers, we can add a flag to the server command that replaces the frontend with a redirect. the pub server owner can use that to redirect to their html frontend. eg `sbot server --redirect https://grimwire.com`. then they can setup a public-facing frontend on port 80/443

**Comment by dominictarr** [comment]
what are you suggesting to host on the sbot server? A redirect to another webserver?

**Comment by pfraze** [comment]
by default, we should host phoenix. however, for people running pub servers we should do a redirect that they configure. that would make it easy to setup another server process of your own making on port 80/443.

the alternative for pub servers would be for pub-owners to create frontend plugins like phoenix, and that's still an option, but it would be more convenient if you can just use your own familiar stack. plus, the redirect can get onto the normal http/s ports

**Comment by dominictarr** [comment]
what about down the road we make it host a hyperbootable client, but for now, just host a ssb broshure/docs site?

**Comment by pfraze** [comment]
that can work
