### ISSUE TITLE
connection timeouts dont put peers back into the gossip pool

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#71]
when connections timeout during connect, the rpc `closed` event never fires, so gossip plugin never marks `peer.connected = false`. that results in the peer never trying to connect again

**Comment by pfraze** [comment]
just put a lot of logging in and started turning grim off/on. everything actually seems to be correct - the gossip handler is getting the `closed` event now, and grim returns to the pool. either this got resolved or i misdiagnosed

**Comment by dominictarr** [comment]
okay cool. lets leave this open for a bit and see if it's a problem again.

**Comment by pfraze** [comment]
I havent experienced this, I think it got fixed
