### ISSUE TITLE
invite code allows too many uses

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#72]
two bugs with invite code use

 1. one user can use an invite code multiple times. we should check if sbot is already following and, if so, return success without actually using the code
 2. i created an invite code with 1 use, but it's allowed me to use it multiple times. not sure why

**Comment by dominictarr** [comment]
are you testing this manually or in a script?
I admit there may be a racecondition if you request invites really fast... hmm, that is an attack vector that should be plugged.

**Comment by pfraze** [comment]
manually in the phoenix ui

**Comment by dominictarr** [comment]
okay that shouldn't happen. I guess we should have a way to check how many follows have been used, too.
