### ISSUE TITLE
occasional HD usage spikes

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#75]
i get alerts from linode every so often saying that grimwire is peaking its hard-drive usage. i'm running a few other services, but i'd bet it's scuttlebot causing it

the email I get is usually something like `Your Linode, linode147928, has exceeded the notification threshold (1000) for disk io rate by averaging 5047.67 for the last 2 hours`. that number refers to i/o blocks per second. it hasnt happened recently so i dont have a fine-grained graph to look at, but iirc it's usually very short peak (< 5 mins, maybe < 1 min) that are much higher (in the 30k-65k range)

not sure if this represents an issue or not

**Comment by pfraze** [comment]
hot dog, just happened

![linode147928](https://cloud.githubusercontent.com/assets/1270099/5786628/ee8d1e84-9dad-11e4-8b04-f3fc03f64c5f.png)

**Comment by dominictarr** [comment]
Since it's occasional massive peaks I feel like that could be leveldb compaction?
Do we know if this is reads or writes?

It could also be from reads during replication handshakes - we should add our own logging for this probably.

**Comment by pfraze** [comment]
i'm 99% certain this is due to #82, closing
