### ISSUE TITLE
Feature Request: Email Bridge, or Scuttlebutt email

### ISSUE THREAD

**Issue by 3arn0wl** [ssbc/scuttlebot#753]
With governments getting increasingly intrusive, it might be a good time to start keeping our emails on our own device, rather than others' servers...

Would it be possible to use the Scuttlebutt for emails?  Or to have a bridge between Scuttlebutt and emails.

**Comment by clehner** [comment]
Hi @3arn0wl, there is a ssb-email project here: https://git.scuttlebot.io/%25DPCm87tUVcABWLBOHlxgfz3lblJASWDDH6IaIp4B3oQ%3D.sha256 (repo id `ssb://%DPCm87tUVcABWLBOHlxgfz3lblJASWDDH6IaIp4B3oQ=.sha256` by `@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519`)
