### ISSUE TITLE
OpenError: IO error: lock /root/.ssb/blobs_push/LOCK: Resource temporarily unavailable

### ISSUE THREAD

**Issue by samuk** [ssbc/scuttlebot#763]
Trying to run on [OrangePi Piratebox](https://github.com/Agroecology-Lab/edu-hotspot/blob/master/README.md)

root@orangepizero:~# sh ~/run-server.sh --logging.level=info
ssb-server 15.3.0 /root/.ssb logging.level:notice
my key ID: lY3Smp2YlOIC8gbtYnBFGLwYAJDn75q3BtsBbDLAhgk=.ed25519

/root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/levelup/lib/levelup.js:119
      return callback(new OpenError(err))
                      ^
OpenError: IO error: lock /root/.ssb/blobs_push/LOCK: Resource temporarily unavailable
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/levelup/lib/levelup.js:119:23
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
Emitted 'error' event at:
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/levelup/lib/levelup.js:60:19
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/levelup/lib/levelup.js:119:14
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    [... lines matching original stack trace ...]
    at /root/.nvm/versions/node/v10.24.1/lib/node_modules/ssb-server/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

**Comment by staltz** [comment]
Are you running two processes that use this folder? That would be the only explanation i can think of why the "blobs" folder would be locked

**Comment by samuk** [comment]
Not intentionally! I'll reboot it and try again.

**Comment by clehner** [comment]
Also, it may be a good idea to run the server from its own user account rather than as root.

**Comment by samuk** [comment]
Well after a reboot it no longer seemed to have ssb-server installed. After reinstalling it now starts!

Unfortunately, when It came back up it did not bring up the Wifi hotspot, but that's another problem.
'''
root@orangepizero:~# ssb-server start --logging.level=info
Command 'ssb-server' not found, did you mean:
  command 'ss-server' from deb shadowsocks-libev
Try: apt install <deb name>
root@orangepizero:~# npm install -g ssb-server
/usr/bin/sbot -> /usr/lib/node_modules/ssb-server/bin.js
/usr/bin/ssb-server -> /usr/lib/node_modules/ssb-server/bin.js

> sodium-native@3.2.0 install /usr/lib/node_modules/ssb-server/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> leveldown@5.6.0 install /usr/lib/node_modules/ssb-server/node_modules/leveldown
> node-gyp-build


> level@5.0.1 postinstall /usr/lib/node_modules/ssb-server/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

+ ssb-server@15.3.0
added 791 packages from 281 contributors in 141.82s
root@orangepizero:~# ssb-server start --logging.level=info
ssb-server 15.3.0 /root/.ssb logging.level:info
my key ID: lY3Smp2YlOIC8gbtYnBFGLwYAJDn75q3BtsBbDLAhgk=.ed25519
ssb-friends: stream legacy api used
'''
