### ISSUE TITLE
install fails on node 0.11

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#78]
this was on osx with node 0.11.14

error output: https://gist.github.com/anonymous/d165fca7b7c2f5c9c55c

do we need to update leveldown?

**Comment by pfraze** [comment]
we're already at latest with level. it looks like this is an existing issue. https://github.com/rvagg/node-leveldown/issues/130. i installed node 0.11 in a vm and confirmed.

**Comment by ralphtheninja** [comment]
@pfraze Are you still having the same issues?

**Comment by pfraze** [comment]
@ralphtheninja I havent tried recently, want me to give it another go?

**Comment by ralphtheninja** [comment]
Yep!

**Comment by pfraze** [comment]
Just used nvm to switch over to 0.11 and install. No errors. I think we're good!
