### ISSUE TITLE
blob tests stalled out

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#79]
https://travis-ci.org/ssbc/scuttlebot/builds/47685915

when i run npm test, it does tend to stall for a while, but usually resolves soon enough. race condition?

**Comment by pfraze** [comment]
happened again, different tests https://travis-ci.org/ssbc/scuttlebot/builds/47701321

**Comment by dominictarr** [comment]
yeah, I've observed this too. It does take a little while, but then it completes.

**Comment by pfraze** [comment]
haven't experienced this in a while, closing
