### ISSUE TITLE
pub server croaking with high swap

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#82]
after leaving my pub overnight, i sshed into the vps and tried to create an invite (`./bin.js invite.create 5`). the ssh session was lagging, so i already knew something was up. then the invite never emitted - the command just hung.

i ran `iotop` and got this output:

![screen shot 2015-01-22 at 9 36 20 am](https://cloud.githubusercontent.com/assets/1270099/5858693/be51d266-a21a-11e4-84af-85af65e0e59d.png)

`node ./run` is scuttlebot. as soon as i restarted the process, swap dropped back to 0 and all was well

unfortunately, i didnt grab the `htop` stats before restart, but here it is after

![screen shot 2015-01-22 at 9 56 06 am](https://cloud.githubusercontent.com/assets/1270099/5859097/629b7bd6-a21d-11e4-90c2-1bcb531ad3ba.png)

if i'm interpreting correctly, we've got 69MB in resident memory and over a gig in virtual, which suggests quite a bit of memory is swapped out (though i'm unsure why the swap meter on top left only shows 46 mb). either way, the virtual footprint seems way too high. 

also, since taking that screenshot (about 5 min ago) the res & virt has climbed 5mb. it looks like it's climbing by about a `mb` a minute.

**Comment by pfraze** [comment]
wouldnt be a node project without an unbounded memory issue

**Comment by pfraze** [comment]
these graphs arent mind-blowing, but i collected them anyway. these are collected with https://nodetime.com on my local sbot instance over the course of ~half an hour. the graphs referring to heap snapshots are using data collected from captured heaps

![screen shot 2015-01-23 at 10 52 22 am](https://cloud.githubusercontent.com/assets/1270099/5878706/92927778-a2ee-11e4-9999-673f6c932837.png)
![screen shot 2015-01-23 at 10 52 31 am](https://cloud.githubusercontent.com/assets/1270099/5878707/9296159a-a2ee-11e4-85da-8246e3403f24.png)
![screen shot 2015-01-23 at 10 52 40 am](https://cloud.githubusercontent.com/assets/1270099/5878708/9296b09a-a2ee-11e4-9a76-cbec8c441617.png)
![screen shot 2015-01-23 at 10 53 23 am](https://cloud.githubusercontent.com/assets/1270099/5878709/92982e34-a2ee-11e4-8be6-b75153a80cfe.png)
![screen shot 2015-01-23 at 10 53 37 am](https://cloud.githubusercontent.com/assets/1270099/5878711/929c57d4-a2ee-11e4-9b4c-fb802495c214.png)
![screen shot 2015-01-23 at 10 53 46 am](https://cloud.githubusercontent.com/assets/1270099/5878710/92991420-a2ee-11e4-8d20-4fb429df88cb.png)
![screen shot 2015-01-23 at 10 54 04 am](https://cloud.githubusercontent.com/assets/1270099/5878712/929d41e4-a2ee-11e4-9c2a-dfd8fc4b4895.png)
![screen shot 2015-01-23 at 10 54 14 am](https://cloud.githubusercontent.com/assets/1270099/5878714/92a641ae-a2ee-11e4-8de5-21d8ff9c2150.png)
![screen shot 2015-01-23 at 10 54 47 am](https://cloud.githubusercontent.com/assets/1270099/5878713/92a1ac2a-a2ee-11e4-91df-98669b22f6ff.png)

**Comment by pfraze** [comment]
i got node-inspector going and started tracing through retained objects. there are a lot of closures that arent getting cleaned up, particularly through-out the rpc stack. (muxrpc, packetstream.)

**Comment by pfraze** [comment]
found an elegant fix for grimwire

```js
setTimeout(function () {
  process.exit()
}, 1000*60*60)
```

since the process is supervised, it auto restarts

:tophat: the classy path

**Comment by dominictarr** [comment]
@pfraze can you link me to any documentation on how you use node-inspector to see into closures cleanup?

**Comment by pfraze** [comment]
https://github.com/felixge/node-memory-leak-tutorial
http://strongloop.com/strongblog/how-to-heap-snapshots/
https://developer.chrome.com/devtools/docs/memory-analysis-101
http://addyosmani.com/blog/taming-the-unicorn-easing-javascript-memory-profiling-in-devtools/

**Comment by pfraze** [comment]
spent some time debugging leaks, see https://github.com/ssbc/scuttlebot/pull/100. the muxrpc and packet-stream PRs definitely seem to help, though muxrpc's PR has an open question

i'm finding that node-inspector's "record heap allocations" profiler very useful. i'm 90% sure i've got this right:

![screen shot 2015-01-27 at 1 34 20 pm](https://cloud.githubusercontent.com/assets/1270099/5925457/43aada40-a629-11e4-8019-6ac2a6f7eb19.png)

the blue bars represent allocated memory that hasnt GCed yet. the gray bars represent mem that was GCed. blue bars that never go away are probably (but not always) leaks. make sure the timeline has gone fairly far beyond a blue bar before you consider it a leak, though -- its valid lifetime may not be up yet, eg because the connection is still underway, or because there's a timer, etc

what i see currently is about 200kb allocated per connection, and about 100kb of that collected. a lot of the objects seem related to the leveldb hooks system, though i haven't tracked that down yet.

if the inspector tells you a preview isnt available, i believe that means the item was GCed after it was captured in the heap dump. not 100% sure but i think that's the case

**Comment by dominictarr** [comment]
hmm, hooks could be optimized, currently all the ranges are in an array that is iterated over.
We could optimize this by constructing examples with artificially large numbers of listeners and events.

**Comment by dominictarr** [comment]
question: what code are you running to do GC stuff? Are you just running scuttlebot with against the real data?
We should probably have a network of bots, that produce a lot more content, etc, etc, which will generate a lot more data, and thus give us stronger effects to measure.

**Comment by pfraze** [comment]
yeah, latest sbot on my local and on grim. i think we'll be able to squash most of these leaks before having to get a bot network going, and then we can reanalyze when we get there

**Comment by pfraze** [comment]
phoenix's live-build of the frontend (`--dev` mode) seems to be leaking a lot when it builds css, visible by requesting `http://localhost:2000/css/home.css` repeatedly and watching the memory usage climb. i didnt observe the same issue for the js build w/browserify

**Comment by dominictarr** [comment]
I bet you could avoid that by building in a child process - memory leaks are probably not a design concern for those tools since generally you run them as a command and when they finish they exit.

**Comment by No9** [comment]
OK I dived into this a little tonight 
Ran MDB and got the data here 
https://gist.github.com/No9/f50028a7ef8d9a3f1a49 

I think ```lte, gte, reverse``` could be worth isolating more as it has an order of magnitude more objects than any of the other calls that I can see

```
Object Add         Count          Properites Constructor 
40358353fea1    38569        3 Object: lte, gte, reverse
403583512dd9   117426        1 Array
403583517e19    44452        3 Array
```

Although the point @dominictarr makes about hooks being iffy is also highlighted too 
As ```getLatest``` seem to be claiming some resources. 

```
403583534211     1207       37 EventEmitter: getLatest, ...
4035835046e9    28407        2 Object: size, ts
403583504679    38574        2 Object: range, hook
```

Finally this also might be worth investigation. 
 
```ready, reading, ended, read, ...
    40358353cc69     1960        8 Array
    4035835878c9    16685        1 p: limbs
```

Haven't had chance to investigate exactly where in the code these are being called from yet but I might get a shot at it tomorrow.

**Comment by pfraze** [comment]
between merged and waiting PRs, i figure we're about half-way through the out-standing leaks. will take another pass at this next week.

**Comment by ralphtheninja** [comment]
@pfraze Where does `iotop` come from?

**Comment by pfraze** [comment]
@ralphtheninja http://guichaz.free.fr/iotop/

**Comment by ralphtheninja** [comment]
Nice. Seems like a good tool to have in your toolbox.

**Comment by pfraze** [comment]
This is still a problem.

I started getting high disk I/O alerts from linode. I couldn't find any coincidental peak in network traffic, so the I/O wasn't caused by downloading/uploading a lot of data. This made me suspect page thrashing, so I started watching memory usage.

This is pulled from htop, today. It shows clear runaway growth. The intervals are inconsistent, because I was just glancing periodically during the day.

```
time    VIRT   RES
0930AM  1243M  311M
1145AM  1368M  434M
1215PM  1396M  464M
1245PM  1418M  485M
0130PM  1470M  536M
```

**Comment by gardner** [comment]
I noticed sbot was hogging memory. The log contained quite a few of these:

```
packet-stream asked to read after closed { value: false, end: false, req: -132 }
Device sleep detected, triggering pub sync
(node) warning: possible EventEmitter memory leak detected. 11 edge listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Graphmitter.addListener (events.js:239:17)
    at Graphmitter.exports.traverse (/Users/gardner/src/patchwork/node_modules/graphmitter/algorithms.js:85:8)
    at Object.<anonymous> (/Users/gardner/src/patchwork/node_modules/scuttlebot/plugins/friends.js:112:22)
    at apply (/Users/gardner/src/patchwork/node_modules/muxrpc-validation/index.js:171:15)
    at Object.<anonymous> (/Users/gardner/src/patchwork/node_modules/muxrpc-validation/index.js:95:14)
    at Object.hooked [as createFriendStream] (/Users/gardner/src/patchwork/node_modules/hoox/index.js:10:15)
    at replicate (/Users/gardner/src/patchwork/node_modules/scuttlebot/plugins/replicate.js:91:20)
    at EventEmitter.<anonymous> (/Users/gardner/src/patchwork/node_modules/scuttlebot/plugins/replicate.js:173:7)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

```

**Comment by evbogue** [comment]
Is specific set of memory leaks still a problem? 

I know we have a few related issues open on git-ssb about sbot needing to be restarted, but it's unclear to me whether or not this can be closed.
