### ISSUE TITLE
pub server is connecting to itself

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#83]
grim is connecting to itself. i'm not sure yet if this is a config issue (hostname set incorrectly) or a code issue. filing issue to i can get back to it

**Comment by pfraze** [comment]
was a config issue, solved

**Comment by dominictarr** [comment]
we should check for this - what was the config that caused this?

**Comment by dominictarr** [comment]
hmm, oh so this issue disappears with https://github.com/ssbc/scuttlebot/pull/84/files

**Comment by pfraze** [comment]
correct
