### ISSUE TITLE
blob polling increases when a new ext link is discovered

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#86]
this has been observed twice. i added some logging to see when sbot was sending queries for blobs. what appears to happen is that, when a new blob is published (via an ext link) the blob pluign starts polling its already-connected peers repeatedly. as far as i saw, other connections could be created afterward and those peers did not get added to this pool of rapidly-queried targets

havent yet diagnosed possible causes

```
info 64Fm BLOB  want "qH8g5u/EFdx46SOxudBomUbFyRZ0MA5LRR699yo71+s=.blake2s"
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false ]
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false, false, false, false, false, false, false ]
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false ]
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false, false, false, false, false, false, false ]
etc
```

**Comment by pfraze** [comment]
this is behaving somewhat better since https://github.com/ssbc/scuttlebot/pull/87 (not sure if related)

the polling no longer increases in its rate. what does happen, however, is that the number of queries increases once for each discovered blob

here's the log output after 3 new blobs:

```
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
BLOBS QUERYING TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false, false, false, false, false ]
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false, false, false, false, false ]
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false, false, false, false, false ]
```

it happens 3 times, simultaneously

**Comment by pfraze** [comment]
ok, i'm seeing an apparently random number of simultaneous queries now (during the same execution of sbot as previous). sometimes now it's just one, sometimes its two. i no longer think it's related to the number of discovered blobs.

**Comment by pfraze** [comment]
this may be resolved (?)

**Comment by dominictarr** [comment]
what is the _correct_ behavior here? I'm thinking there should be a maximum rate of requests per connection?

**Comment by pfraze** [comment]
yes, and i figure it's best if all queries are batched into one call, but it's probably not a big deal so long as the simultaneous calls aren't redundant (which i havent checked yet)

**Comment by dominictarr** [comment]
correct - and there should also be a maximum batch size.

**Comment by gwenbell** [comment]
@dominictarr @pfrazee reading through this now. Can I confirm that this is resolved and okay to close?
