### ISSUE TITLE
blob tmp-storage needs to be cleared

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#89]
i encountered an error condition which caused a lot of tmp files to be created (in `$SSB/blobs/tmp`) and never destroyed. this is bad. we should use the system's tmp directory so that we know theyll get auto-cleaned

**Comment by pfraze** [comment]
we've decided to just clear the tmp cache on startup https://github.com/dominictarr/multiblob/issues/3

**Comment by dominictarr** [comment]
cool
