### ISSUE TITLE
reducing blob-sync load: registering interest

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#96]
i think we're going to have congestion issues if we don't add sophistication to the blob-syncing strategy. even if every user is a good citizen, the dataset will get large fast. if a pub follows 100 users, each of which has posted 10mb of data, that's a gig of data for the initial sync. that can't work!

most peers, i think, need to download blobs only after registering interest in them. we can come up with different ways to do this, but i think they'd break down to either
- "give me every blob this feed posts"
- "give me every blob in this message"
- "give me this blob"

i think phoenix's UX should focus around the latter two, and maybe make the first an option

with pubs, we could use the first strategy and auto-download every blob its members post (perhaps under a size limit) but ignore blobs by friends of friends. another thing we could do is let users "push" blobs to a server - that is, request that the pub take the blob. this would allow members to upload non-members' blobs.

pubs can deal with a slightly higher load overall, but they may need to have a prioritization tool so that they only fetch blobs when feed-syncing doesnt ned to take precedence.

**Comment by pfraze** [comment]
> pubs can deal with a slightly higher load overall, but they may need to have a prioritization tool so that they only fetch blobs when feed-syncing doesnt ned to take precedence.

blob fetching could easily move to additional threads, since it doesnt involve the db

**Comment by dominictarr** [comment]
Oh, if you follow someone who has been using the system for a long time, you probably don't want to download all their history, but just their recent stuff, unless you actually try to view that attachment.

We probably want to have rate limits (mb/day) per user and overall. prehaps some users get to publish more (to me) but by default I will only take a little from each user.

**Comment by pfraze** [comment]
@dominictarr you may already be planning this, not sure

one strategy could be to track where blobs are available without downloading them immediately. when they are requested by some local software (`GET /ext/<hash>`) the blob could be fetched from a known location by sbot. the `GET` request's response would pipe that blob

if there are no reachable known locations, sbot could send additional `has()` polls to reachable peers to see if they may have recently received it. since this will take longer, sbot could respond with a 404 that shows the search's progress and redirects to the file once it's found

**Comment by dominictarr** [comment]
@pfraze yeah, that sounds reasonable... knowing where to get that file would be less work than actually getting it. maybe a request for this file could be gossiped to some degree too?
 you could request it from a peer, and if they have not got it they could ask their peers - but then they'd need to tell you what peer had it...

It's cross that bridge when we come to it...

**Comment by gwenbell** [comment]
This is resolved with blobs.wants. Closing.
